sidewalk-webpage/public/javascripts/SVLabel/build/SVLabel.css, sidewalk-webpage/public/javascripts/SVLabel/build/SVLabel.js, sidewalk-webpage/public/javascripts/SVLabel/css/svl-status-progress-pov.css, sidewalk-webpage/public/javascripts/SVLabel/src/SVLabel/Keyboard.js, sidewalk-webpage/public/javascripts/SVLabel/src/SVLabel/Util/UtilitiesSidewalk.js, sidewalk-webpage/public/javascripts/SVLabel/src/SVLabel/mission/MissionProgress.js
Same changes as in https://github.com/ProjectSidewalk/SidewalkWebpage/pull/75 moved to working branch off of master instead of my fork. This should make staying updated for me easy and predictable.
I will make a few more mission bar color schemes and present them either with a comment here or via our email thread.
=> Mission Progress Colors + Context Menu Keyboard Shortcuts

public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
We now have a selection of smiley faces to make the completion message less serious.
=> Mission Complete Emoji

public/javascripts/SVLabel/src/SVLabel/Keyboard.js
Even though this is a built in feature in GSV, it was not working in ours for some reason. Maybe because of the other layers interfering with the focus. 
This is not quite done. I am looking for feedback here. Sometimes the links on the SV (the arrows on the ground) do not respond. When they do respond you go  in the correct direction. I originally thought my math was wrong but I am not sure now.
=> Using Arrow Keys to Move in Panorama

public/javascripts/SVLabel/src/SVLabel/Map.js
Current mission neighborhood used instead of unspecified "neigborhood"
=> Jumped back to Particular Neighborhood Message

public/javascripts/SVLabel/build/SVLabel.js, public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/Map.js, public/javascripts/SVLabel/src/SVLabel/mission/Mission.js, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
Updated the methods that gets mission tasks. Use it to get tasks in the current mission. You should render the path contained in these tasks in green. You should render the tasks completed in previous missions in blue. Currently you set the color other way around.
@danZzyy
=> Updated methods in Mission.js

app/views/audit.scala.html, public/javascripts/SVLabel/css/svl-modal.css, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js, public/javascripts/SVLabel/src/SVLabel/neighborhood/Neighborhood.js
Addressing https://github.com/ProjectSidewalk/SidewalkWebpage/issues/124
=> Modal Mission Complete Small Fixes

public/javascripts/SVLabel/spec/SVLabel/modal/ModalMissionCompleteProgressBar-spec.js
Before the timeout was in a beforeEach statement. It is now in each 'it' surrounding the expect statements
=> ModalMissionCompleteBar spec refactor

app/models/audit/AuditTaskTable.scala, app/models/daos/UserDAOImpl.scala, app/models/label/LabelTable.scala, app/views/admin/index.scala.html
Displays Today’s and Yesterday’s labels, users and audit tasks
=> Bug 167 Resolution

public/javascripts/SVLabel/img/misc/people.svg, public/stylesheets/index.css
=> Fix #289; specify default size in the svg file

.gitignore, Gruntfile.js, app/views/faq.scala.html, public/javascripts/FAQ/src/tableOfContents.js
=> Fix #186 and #301; update FAQ Page

public/javascripts/SVLabel/img/icons/Sidewalk/Icon_CurbRamp.svg
=> Fix label icons for firefox

app/views/faq.scala.html, public/stylesheets/faq.css, public/stylesheets/main.css
71d976d fixes #302.
17df99f fixes #309.
=> Fix Faq Page's Aesthetics + Add FAQ Item For Grey GSV

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
=> Fix enter/escape shortcuts when typing description

build.sbt
=> Use gt-epsg-wkt instead of gt-espg-hsql and update version

public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
=> Fix example text

app/views/admin/index.scala.html, public/javascripts/Admin/src/Admin.js
New implementation of #182 (admin map checkboxes) that resolves conflicts with current master branch.
=> New admin map checkbox implementation

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
=> Remove number bindings #371

app/views/admin/index.scala.html, public/javascripts/Admin/src/Admin.js, public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js
=> Differentiate gray label types

app/views/about.scala.html
=> About page update

Gruntfile.js, app/views/audit.scala.html, public/javascripts/SVLabel/css/svl-alert.css, public/javascripts/SVLabel/css/svl-modal.css, public/javascripts/SVLabel/css/svl-ribbon.css, public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/Onboarding/Onboarding.js, public/javascripts/SVLabel/src/SVLabel/alert/Alert.js, public/javascripts/SVLabel/src/SVLabel/alert/KeyboardShortcutAlert.js, public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js, public/javascripts/SVLabel/src/SVLabel/ribbon/RibbonMenu.js, public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js
=> Implement 287 make keyboard shortcuts visible

public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/mission/Mission.js, public/javascripts/SVLabel/src/SVLabel/mission/MissionContainer.js
=> Fix #297: Add an offset variable and calculate it when data is loaded

public/javascripts/SVLabel/css/svl-modal.css, public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js, public/javascripts/SVLabel/src/SVLabel/mission/Mission.js, public/javascripts/SVLabel/src/SVLabel/mission/MissionContainer.js, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionCompleteMap.js, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionCompleteProgressBar.js
=> Fix 216 route animation

app/views/index.scala.html
=> Fix #150: change figure caption

app/views/faq.scala.html, public/stylesheets/faq.css, public/stylesheets/main.css
=> FAQ: fix #229 and #279

app/models/daos/UserDAOImpl.scala, app/views/admin/index.scala.html
Needs a more refined solution. Works for now.
Resolves #353 and #365
=> #353 Added last audited column for anonymous user table

app/models/street/StreetEdgeTable.scala, app/views/admin/index.scala.html
=> #350 Add coverage total distances to admin interface

deploy.py, test_deploy.py
Solves #379. Created a test deploy script to test it on the server once the environment is setup. Working with UMIACS to get that done.
=> Modify deploy script

public/javascripts/SVLabel/src/SVLabel/Onboarding/Onboarding.js
=> Change Onboarding

public/javascripts/SVLabel/src/SVLabel/Onboarding/Onboarding.js, public/javascripts/SVLabel/src/SVLabel/alert/Alert.js, public/javascripts/SVLabel/src/SVLabel/alert/KeyboardShortcutAlert.js, public/javascripts/SVLabel/src/SVLabel/canvas/Canvas.js, public/stylesheets/main.css
Fixes #427 
Fixes #428 
Fixes #431
=> Changes to alert box

public/javascripts/SVLabel/src/SVLabel/onboarding/InitialMissionInstruction.js
Fixes #269.
Calculating the portion of the panorama scene that the user has viewed was more complicated than I expected. Although I tried to use the simplest possible algorithm, but it is still quite complicated. I can explain it to whoever that tries to review this PR.
=> Fix #269: "Intersection done dialog pops up before it is completed"

.gitignore, deploy.py, test_deploy.py
Fixes a bug in the issue #379 that prevents the application from starting
=> Functional deploy script

app/models/daos/UserDAOImpl.scala, app/views/admin/index.scala.html, public/javascripts/Admin/src/Admin.js
- Fixed bug in calculating number of contributing users
- Changed the ordering of the different tables on the page
- Changed the sorting order of Users Table
=> Made few minor updates to the admin interface

deploy.py, test_deploy.py
Came up while testing it on the server.
=> Minor fix to sort files in the script

public/javascripts/SVLabel/spec/SVLabel/keyboard/Keyboard-spec.js, public/javascripts/SVLabel/spec/SVLabel/mission/MissionProgress-spec.js, public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js, public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js, public/javascripts/SVLabel/src/SVLabel/navigation/NavigationModel.js, public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js
=> Disconnected path (#243)

public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js
=> Bug fix for anonymous users' task marked as incomplete issue

app/views/faq.scala.html
=> Added a FAQ entry for the issue on disappearing navigation arrows

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js, public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js
=> Add force argument to setPano function and use it in the onboarding.

public/javascripts/SVLabel/src/SVLabel/Main.js
=> Add shortcut tooltips to zoom in and out buttons.

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js, public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js
Fixes the problem of infinite loop at the end of neighborhoods.
=> Finish neighborhood infinite loop

app/views/audit.scala.html, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
=> Added congratualory message to the end of neighborhood completion msg

public/javascripts/SVLabel/src/SVLabel/mission/MissionContainer.js
This pull request will be used to resolve the infrequent mission complete modal errors that occur.
=> Mission complete modal errors

app/models/audit/AuditTaskInteractionTable.scala, app/views/admin/task.scala.html, public/javascripts/Admin/src/Admin.Task.js, public/javascripts/SVLabel/src/SVLabel/OverlayMessageBox.js, public/javascripts/SVLabel/src/SVLabel/Tracker.js, public/javascripts/SVLabel/src/SVLabel/canvas/Canvas.js, public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js, public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js, public/stylesheets/previousAudit.css
This pull request adds the following changes:
1. Fixes #389. Brand new logged interactions are `POV_Changed`, `PanoId_Changed`, `ExplainThis` and usage of keyboard shortcuts.
2. Refactored the `Tracker`'s source code. Previously all the parameters (the `notes` field in the database) were hard-coded in the source code, it is now dynamically stored. That makes logging new events much easier.
3. Added a timeline under the playback tool and a box to show logged events. (The playback tools' address is `/admin/task/[task_id]`).
As a side-effect of storing all POV changes, the playback tool is now much smoother.
=> Quality control changes

app/models/audit/AuditTaskInteractionTable.scala, app/views/admin/task.scala.html, public/javascripts/Admin/src/Admin.Task.js, public/javascripts/SVLabel/src/SVLabel/OverlayMessageBox.js, public/javascripts/SVLabel/src/SVLabel/Tracker.js, public/javascripts/SVLabel/src/SVLabel/canvas/Canvas.js, public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js, public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js, public/stylesheets/previousAudit.css
This logs the low level events like mouse movements and keyboard presses. I also increased the stack threshold to 200 from 30 to reduce the number of calls to the server.
We have to test whether this causes any lags before merging this to the production server. So we can merge this to develop for now.
=> Quality control changes low level events

app/views/main.scala.html, public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js, public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js
=> 518 api version update

app/views/about.scala.html
=> Update team members info

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js, public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js
Fixed label sticking while panning using keyboard arrows
=> 429 new label placement method

app/views/audit.scala.html, public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
=> 537 depth data issue

app/controllers/ApplicationController.scala, app/controllers/AuditController.scala, app/views/audit.scala.html, app/views/index.scala.html, conf/routes, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js, public/javascripts/SVLabel/src/SVLabel/util/Utilities.js
=> Mturk HIT implementation - Exit portion

app/views/index.scala.html, build.sbt, public/javascripts/SVLabel/src/SVLabel/Main.js, test_hit_creation.py
- Preview HIT screen updated
- HIT Creation File updated
=> Preview HIT screen - text updated

app/controllers/AuditController.scala, app/controllers/MissionController.scala, app/controllers/TaskController.scala, app/models/mission/MissionTable.scala, app/models/route/RouteStreetTable.scala, conf/evolutions/default/1.sql, conf/routes, hit_approve_assignment.py, hit_creation.py, public/javascripts/SVLabel/src/SVLabel/mission/MissionModel.js
=> Updated HIT creation script

app/views/index.scala.html, connect.py, create_routes.py, hit_approve_assignment.py, hit_creation.py
and updated HIT script to load specific routes
=> Updated db config parameters in scripts..

app/views/main.scala.html, public/css/main.css
=> Landing Page - Results btn jumps bug

app/controllers/AdminController.scala, public/javascripts/Admin/src/Admin.User.js, public/javascripts/Progress/build/Progress.js
Comments out the code that gets audit interactions data. Most OutOfMemory error logs show that it goes out of memory for this method.
=> Temp fix for OutOfMemory Error

public/javascripts/Progress/src/Progress.js
=> Fixing previous commit

build.sbt
- Commented out code for audit interaction data in Progress.js
=> Fixing v3.1.3

public/javascripts/SVLabel/css/svl.css, public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js, public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js, public/javascripts/SVLabel/src/SVLabel/zoom/ZoomControl.js
Trains users to zoom-in and look at the second intersection corner that is relatively far away from camera's position.
Screenshots are in the issue thread #541.
Resolves #541.
=> 541 Onboarding New Zoom In Feature

public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js, public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js, public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js
- Auto closes the context menu when the user finishes with the severity step correctly
- Modified last step text of zoom-in feature to "Look to the left by grabbing and dragging the SV image"
- Updated text bolds appropriately in other parts of the tutorial
=> Update tutorial zoom feature

public/javascripts/SVLabel/src/SVLabel/PopUpMessage.js
Resolves #654
Added tracking code for sign up - yes/ no and sign in for the "contributing a lot" pop up
=> Added tracking code for "contributing a lot" pop up clicks

app/views/navbar.scala.html
Resolves #609 
Text on buttons for signing in has been updated to be more consistent.
=> 609 updated sign in text

app/controllers/CredentialsAuthController.scala, app/controllers/SignUpController.scala, app/models/daos/slick/DBTableDefinitions.scala, app/views/signIn.scala.html, app/views/signUp.scala.html
Fixes #488: registration with an existing email but new username/password is no longer allowed on the front-end; Fixes #664; Fixes #666
=> 488: Registration with duplicate email; 664: Alerts not appearing

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js, public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
- Restricted keyboard panning
- Hid navigation arrows when onboarding is loaded.
Related to #437
=> 437 Restricted keyboard panning

public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js, public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js
- updated instruction texts
- created two states after walk position
Resolves #711
=> 711 tutorial relaunch fixes

app/views/index.scala.html, public/css/main.css
The "What is Project Sidewalk?" video module on the landing page is now the 3rd module instead of the 4th.
Also changed choropleth module's background to white.
Resolves #724
=> Changed location of video module on landing page

public/javascripts/SVLabel/src/SVLabel/PopUpMessage.js
Added a 10px spacing between the buttons on the “Contributing a Lot” popup dialog box. 
This resolves #710
=> Add spacing between buttons

app/views/main.scala.html
Twitter link in footer is updated from umd_sidewalk to new username projsidewalk
Resolves #514
=> Issue 514 Switching Twitter Account Name

app/views/index.scala.html
Twitter links in "What people are saying" section are updated to new username @projsidewalk 
Resolves #514
=> Issue 514 "What people are saying" Twitter Links

public/javascripts/SVLabel/src/SVLabel/modal/ModalMission.js
Only for the user's first ever mission [decided by missionContainer.isTheFirstMission()], the mission dialogue is more exciting:
"First Mission:" is included in the title
"Your **first mission** is.." starts the instruction text
=> Issue #731 New first mission dialogue

public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/onboarding/InitialMissionInstruction.js
- Updated popup text
- Added logging of popup displays
Screenshot:
Resolves #544
=> Updated popup message for GSV label disappearing 

conf/routes
=> Updated API end point name for developer to api

public/javascripts/SVLabel/src/SVLabel/modal/ModalMission.js
"of" is changed to "in" for all mission titles and instruction text
Resolves #801
=> Issue #801 Mission Text Updated

public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js
Resolves #807.
Tracker was not passed to initial mission instructions properly. Should be fixed now.
=> Resolves minor error that occurs when user chooses to skip the tutorial

public/javascripts/SVLabel/lib/animate.css, public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js
Resolves #815 
- Colocated zooming control messages next to the buttons
- Increased animation speed
=> 815 onboarding colocate zoom messages

public/stylesheets/animate.css
For the messages that have a fadeIn animation, the animation speed is increased. 
Resolves #815 (part of it).
=> Updated animation speed increase for onboarding messages

public/javascripts/SVLabel/src/SVLabel/navigation/Compass.js, public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js, public/javascripts/SVLabel/src/SVLabel/navigation/NavigationModel.js, public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js
Fixes #774 , user now faces correctly after manually jumping.
=> User faces in correct direction after manual jumps

public/javascripts/Choropleth.js
Labelled Monumental Core, Navy Yard, Southwest Employment Area, and
Southwest/Waterfront with alerts noting their difficulty
Resolves #820
=> Added choropleth alerts for difficult neighborhoods

public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js, public/javascripts/SVLabel/src/SVLabel/status/LabelCounter.js
#Potentially resolves #847 
Potentially resolves #848 
I have added an extra check in the method that renders red line on the map during onboarding. Not sure, if it would solve the issue as, like others, I am not able to reproduce it.
Pushing this solution to dev server. @misaugstad @maddalihanumateja  Try doing the exact steps when you got the tutorial messages within a mission. Also, note the region id and the street id when you do your testing if you see that ui bug.
=> 847 tutorial messages shown in mission

app/views/index.scala.html, app/views/navbar.scala.html, public/assets/homepage.js
Fixes 756 - adds logging for clicking "Start Mapping" in navbar and index page. Logs are of the form `Click_module=StartMapping_location=Navbar` and `Click_module=StartMapping_location=Index`.
=> 756 log clicks for start mapping

app/controllers/GroundTruthResolutionController.scala, app/models/audit/AuditTaskTable.scala, app/views/gtresolution.scala.html, conf/routes, public/javascripts/gtresolution.js
Created html, route, js file and scala controller for ground truth resolution under the route /gtresolution
=> Create Ground Truth Resolution route

app/views/developer.scala.html
=> Minor text edits to API page

app/views/navbar.scala.html, app/views/results.scala.html, public/css/main.css, public/javascripts/AccessibilityChoropleth.js
Resolves #896, Resolves #897, and my personal forgetfulness regarding instructions. :)
The loading spinner is now transparent, the legend text has been updated and shrunk, and I remembered to add a link to the results page on the navbar.
=> Updated Results page legend text, spinner, navbar

app/views/main.scala.html
Resolves #911. I talked with Manaswi and she said in the interrim, we can just use the same static description on facebook that we use for twitter.
=> Added Facebook Metadata

app/views/navbar.scala.html, deploy.py, test_deploy.py
Updated deploy script to run with 3 GB heap size
Removed results page link temporarily till the 502 error is resolved
=> 967 proxy server error

app/views/about.scala.html
Resolves #890. Added new summer 2017 Project Sidewalk members. Moved old members to
alumni. Updated our mission text.
=> Addresses Issue #890 - Update About Page Personnel

hit_creation_for_conditions.py
Just repurposed hit_creation.py to create HITs for specific conditions rather than create HITs mapped to individual routes.
=> Added a python program to create HITs for specific condition_ids and with a specific number of assignments

public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/data/Form.js, public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js
Testing would be similar to the procedure followed in #1000 . However on the mturk-v2 branch instead of auditing dynamic routes we wll be testing this on pre-generated routes. After the evolutions are applied correctly use [the sql file I've saved in dropbox](https://www.dropbox.com/s/2xj1lff9tgs80zs/sidewalk_mturk_all_volunteers_20170816_140210.sql?dl=0) to populate the necessary tables (route, route_street, amt_condition, and amt_volunteer) with insert statements. Visit 
http://localhost:9000/?assignmentId=A1M1&workerId=M1&hitId=H1M1&turkSubmitTo=localhost:5000/post 
to audit a route. (assignmentId, hitId, and workerId can be replaced by any other string)
=> Added the changes made to resolve issue #969 (null task id after jump)

app/views/results.scala.html, build.sbt, public/css/main.css
Text size of the Results legend was too small. I increased the font size. I also increased the width of the Legend to better fit the font increase.
=> #897: Results Choropleth: Updated Legend Text Sizing and Legend Sizing

app/views/index.scala.html
Please make any updates to the index page (title, description, ...) on this branch before merging with `sidewalk-mturk-v2`
=> Updated instruction text for Turker vs Volunteer HITs

app/views/index.scala.html
Previous text: Label accessibility problems in the streets of DC
New text: Help us find and label sidewalk problems in Washington DC
This now reflects the most recent changes that we made in the Google Doc.
=> updated preview screen title

app/controllers/UserProfileController.scala, app/views/audit.scala.html, conf/routes
Resolves #1114 . A user who has a turker role and hasn't completed any missions will not be able to skip the tutorial.
To test:
1. Login as a turker using the mturk referrer for example localhost:9000/?referrer=mturk&hitId=h1&workerId=worker_bob&assignmentId=a1 
2. Check that the onboarding description popup doesnt include the "skip onboarding" link.
3. Complete the first mission and try revisiting the onboarding. The link should reappear.
4.  Login as an anon or non-turker registered user and check that the onboarding popup shows the skip link for all cases (missions completed ==0 and > 0).
=> Onboarding is mandatory for new turkers

app/models/audit/AuditTaskTable.scala
As pointed out by @manaswis and @sarahsmo the neighborhood completion count was erroneously set to 0 for the first task in a region. This is because I had been using the `street_edge_assignment_count` table in that particular instance. This has been remedied!
@manaswis I am not entirely sure on the specifics of how you were reproducing this bug, but follow whatever method you were using then to ensure that it is fixed! :upside_down_face: 
Resolves #1172
=> Prevents unnecessary region completion popup when starting a finished region

app/controllers/SurveyController.scala, app/formats/json/SurveySubmissionFormats.scala, app/models/user/UserCurrentRegionTable.scala, app/views/audit.scala.html, app/views/main.scala.html
This fixes a bug that caused a page not found error when a turker submitted their survey after their 2nd mission.
Testing:
1. Try on develop first to make sure that you can reproduce the error. Go to [http://localhost:9000?referrer=mturk&workerId=testworker1&assignmentId=testasmt1&hitId=testhit1](http://localhost:9000?referrer=mturk&workerId=testworker1&assignmentId=testasmt1&hitId=testhit1) (if the survey doesn't pop up at all after the 2nd mission, it may be because you already did some testing with the id "testworker1", so try picking something that you haven't used before). The survey should show up, then when you fill out the survey and submit it, you should see the following:
2. Checkout the new branch, and do the same thing, but with a different worker id in the URL. For example, …
=> 1223 fix survey

public/javascripts/SVLabel/src/SVLabel/label/Label.js
Fix #1269 
Tag is back to normal and doesn't disappear anymore. Sorry for not testing this earlier! 😅 
| Regular | On hover |
| -------- | --------- |
| ![image](https://user-images.githubusercontent.com/25534091/41801586-548fe564-7630-11e8-88e1-c6797688105e.png) | ![image](https://user-images.githubusercontent.com/25534091/41801591-5a1f1810-7630-11e8-80e1-16e8294ce425.png) |
=> Resolves #1269: Fixed check that caused tag to disappear

public/javascripts/AccessibilityChoropleth.js
=> updating no sidewalk icon on results page

app/views/admin/index.scala.html, app/views/index.scala.html, public/javascripts/Admin/src/Admin.js, public/javascripts/Choropleth.js
=> makes regions that are 100% audited darker blue choropleth

app/views/audit.scala.html, public/javascripts/SVLabel/spec/SVLabel/modal/ModalMissionComplete-spec.js, public/javascripts/SVLabel/spec/SVLabel/modal/ModalMissionCompleteProgressBar-spec.js, public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/mission/Mission.js, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
Resolves #1312:
The NoSidewalk icon now appears on the mission complete modal.
=> Resolves #1312: Add no sidewalk to mission complete modal

app/Global.scala, build.sbt
Resolves #1338 (Part 2)
Enables gzip compression for all/most files.
To test:
Ensure that all assets load as they normally would. A proper gzip implementation is safe, but there could be bugs in the Play implementation.
=> 1338 nextcity improve load time

Gruntfile.js, app/views/admin/index.scala.html, app/views/help.scala.html, app/views/index.scala.html, app/views/navbar.scala.html, public/assets/homepage.js, public/javascripts/Admin/src/Admin.js
Resolves #1420.
Resolves #1429.
* Added a "Start Validating" button to the main navbar that takes the user to the `/validate` endpoint
* Renamed "Start Mapping" --> "Start Exploring" (from #1429)
* Added logging for "Start Validating" button, updated logging for "Start Mapping"
Before:
After:
=> Resolves #1420, 1429: adds start validating button to navbar

db/Dockerfile
=> Resolves 1479: Fixed the docker container locale issue

conf/evolutions/default/32.sql, public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js, public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js
Resolves #1435 
The "trash can" tag has been changed to "trash/recycling can".
=> 1435 change name of trash can tag

app/views/audit.scala.html
Resolves #1554 
Makes the title of the survey more friendly. Changes it from "Feedback Survey" to "Please take this one-time survey about Project Sidewalk".
=> made the survey title more friendly

app/views/audit.scala.html, conf/evolutions/default/35.sql, public/javascripts/SVLabel/css/svl-context-menu.css, public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js, public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js, public/javascripts/SVLabel/src/SVLabel/label/Label.js, public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js
Resolves #1578 
Adds a "parked car" label tag for obstacle labels.
Old look:
New look:
I won't ask anyone to test b/c it is a pretty simple change.
=> 1578 add parked car tag for obstacles

Gruntfile.js, app/controllers/ValidationController.scala, app/controllers/ValidationTaskController.scala, app/models/amt/AMTAssignmentTable.scala, app/views/navbar.scala.html, app/views/validation.scala.html, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js, public/javascripts/SVValidate/src/Main.js, public/javascripts/SVValidate/src/mission/MissionContainer.js, public/javascripts/SVValidate/src/modal/ModalMission.js, public/javascripts/SVValidate/src/modal/ModalMissionComplete.js, public/javascripts/SVValidate/src/user/User.js
Resolves #1597 
Adds confirmation code, bonus amounts earned, HIT expiration overlay, etc. to the validation page for turkers.
The code is mostly copied from how we did it on the audit page.
@aileenzeng could you read over the code and let me know where things are done poorly? In terms of general coding practices and style? The original code was not written by me and I mostly just copied it straight over. I made some improvements to it, but I'd love your perspective on how to make it even nicer.
=> 1597 update validation for turkers

public/javascripts/SVLabel/src/SVLabel/zoom/ZoomControl.js, public/javascripts/SVValidate/src/zoom/ZoomControl.js
Fixes #1530 
I made a small edit to a comment in the SVLabel ZoomControl.js file. It was suppose to say 'disables' instead of 'enables'.
I added a new function that updates the opacity and if a zoom button should be disabled called ```updateZoomAvailability```. I made ```updateZoomAvailability``` mimic a function called ```updateOpacity``` that is used on the core labeling interface and located in the SVLabel ZoomControl.js file. ```updateZoomAvailability``` is called when the function ZoomControl is called(when the window loads) as well as when a user clicks on a zoom button.
Before:
After:
=> 1530 validation interface zoom level ui update

public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js
I added some console.log statements that should help me debug #1449. 
If anyone gets the bug as described in #1449, it would be great if they could copy/screenshot their console and send it my way.
=> Add logging to aid in the debugging of #1449

Dockerfile, package-lock.json
=> Resolves 1664: modified dockerfile and updated base image to handle the deprecated java 8 package

app/controllers/AdminController.scala, app/models/daos/slick/DBTableDefinitions.scala, app/models/label/LabelTable.scala, conf/routes
Resolves #1657
This PR resolves #1657 by adding an admin API endpoint `/adminapi/labels/cv` that returns, for all labels, the following information in JSON format:
- panorama id
- sv_image_x
- sv_image_y
- label_type_id
- photographer heading
- heading
- user type (registered/anonymous/researcher/etc.)
- username
- mission type (audit, onboarding, etc.)
Example output from the API:
```json
{"labels":[{"gsv_panorama_id":"stxXyCKAbd73DmkM2vsIHA","sv_image_x":9658,"sv_image_y":-460,"label_type_id":1,"photographer_heading":50.3866081237793,"heading":262.0,"user_type":"Registered","username":"myadmin","mission_type":"auditOnboarding"},{"gsv_panorama_id":"stxXyCKAbd73DmkM2vsIHA","sv_image_x":8175,"sv_image_y":-377,"label_type_id":1,"photographer_heading":50.3866081237793,"heading":207.25,"user_t …
```
=> Add an admin API endpoint to return metadata for CV cropping to resolve #1657

app/views/admin/user.scala.html, app/views/audit.scala.html, app/views/developer.scala.html, app/views/index.scala.html, app/views/userProfile.scala.html, public/javascripts/Admin/src/Admin.User.js, public/javascripts/Admin/src/Admin.js, public/javascripts/Choropleth.js, public/javascripts/Progress/src/Progress.js, public/stylesheets/userProfile.css
Fixes #1611
Upgrades the version of Leaflet we are using everywhere, fixing the problem that comes up on the user dashboard when doing that.
It turns out the problem on the user dashboard was a problematic bit of CSS. Removing this CSS fixed the issue and didn't seem to cause any other problems :)
=> 1611 fix old leaflet version

README.md
Resolves #1661 
Updates the README to have instructions for switching cities and having databases for multiple cities.
=> adds instructions for switching cities to README

app/controllers/ValidationController.scala, app/models/audit/AuditTaskCommentTable.scala, app/models/validation/ValidationTaskCommentTable.scala, app/views/admin/index.scala.html
Resolves #1672 
Adds comments from the validation page to the admin comments table.
=> 1672 admin validation comments

conf/evolutions/default/49.sql, public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js, public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js
Fixes #1691 
I added a parked bike tag to the obstacle label and the keyboard short cut for it "d".
Before:
After:
=> 1691 Audit Page - Adds a Parked Bike Tag

app/models/audit/AuditTaskCommentTable.scala
=> fixes query for admin comments table

app/models/label/LabelTable.scala
fixes #1807 
Fixes the bug where we were not giving out any obstacle missions. This should also fix some of the infinite loops issues that may have been causing #1809 and/or #1799. But I think there are other fixes necessary for those issues to be fully resolved.
=> fixes bug where no one was getting obstacle missions

public/javascripts/SVValidate/src/Main.js, public/javascripts/SVValidate/src/panorama/Panorama.js, public/javascripts/SVValidate/src/zoom/PinchZoomDetector.js
Resolves #1883 
Add a pinch zoom feature to mobile validation by using Google Street View Panorama's scrollwheel zooming.
Screen recording of this tested on my phone: https://youtu.be/YJ9V1Xhq7vk
=> 1883 mobile validation add zoom feature

app/controllers/RegionController.scala, app/models/region/RegionTable.scala, app/views/audit.scala.html, public/javascripts/AccessibilityChoropleth.js, public/javascripts/Admin/src/Admin.js, public/javascripts/Choropleth.js, public/javascripts/Progress/src/Progress.js, public/javascripts/SVLabel/spec/SVLabel/task/TaskContainer-spec.js, public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/data/Form.js, public/javascripts/SVLabel/src/SVLabel/mission/CVGroundTruthMission.js, public/javascripts/SVLabel/src/SVLabel/mission/Mission.js, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionCompleteMap.js, public/javascripts/SVLabel/src/SVLabel/task/Task.js, public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js, public/javascripts/SVLabel/src/SVLabel/task/TaskFactory.js
fixes #1450 
fixes #1806 
fixes #1839 
fixes #1885 
fixes #1886 
fixes #1899 
fixes #1908 
Fixes numerous end of mission or end of neighborhood bugs. @jonfroehlich had noticed some bugs when completing a neighborhood (#1885 #1886 #1899), which is what I set out to fix. While fixing those end of neighborhood bugs, I also came across the solutions to some end of mission bugs, particularly related to the animation of the green completed route on the mission complete map (#1450 #1839 #1908). I also noticed that the tutorial street was being included in every neighborhood (#1806).
I realize this isn't really good form because I have 7 bug fixes in one PR... But also I didn't expect anyone to be available to test them anyway :grin: I don't plan on making a monster PR like this ever again, but …
=> Fixes numerous bugs when completing a mission/neighborhood

app/controllers/ValidationController.scala
Fixes #1807 
Fixes the bug where obstacle validation missions were never being given to users. It was an off by one error :upside_down_face:
=> fixes bug where obstacle validation missions not given

app/controllers/TaskController.scala, app/models/mission/MissionTable.scala, app/views/audit.scala.html
Fixes #1964 
Fixes the bug where new users would be sent to the tutorial street at the start of their first mission and were forced to jump to their actual street.
=> fixes bug where new users sent to DC and forced to jump

app/views/footer.scala.html, app/views/main.scala.html, app/views/rapidValidation.scala.html, app/views/validation.scala.html
Resolves/fixes #1987
Created a template file for the mini-footer-audit div in order to keep it in one place for easy importing.
=> #1967: Template for mini-footer-audit div

check_streets_for_imagery.py
Resolves #1990 
When an error occurs due to network problems while running the script that checks for GSV imagery, the progress is now saved and automatically resumed when you run the script again.
=> checking streets for imagery now saves progress

app/controllers/ConfigController.scala, app/views/developer.scala.html, app/views/navbar.scala.html, conf/cityparams.conf, conf/routes, public/javascripts/developer.js
Fixes #1344 
The demo maps on the API page are now different for each city. I added entries in the `cityparams.conf` file for the lat/lngs for each of the 3 maps in each city. I then found a decent looking area in each city for each of the maps.
I used the data on the prod servers to test for good looking areas, so it might not look as nice on the test servers.
=> 1344 api per city demos

public/javascripts/SVValidate/mobile/mobileValidate.css, public/javascripts/SVValidate/mobile/mobileValidate.js
Set an on click animation using CSS for each of the three validation buttons on mobile.
Animation can be seen here:
Resolved #1905
=> 1905 Confirm Validation Button Click Mobile

app/views/audit.scala.html, app/views/validation.scala.html, conf/messages.en, conf/messages.es, public/javascripts/SVLabel/src/SVLabel/modal/ModalMission.js, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js, public/javascripts/SVValidate/src/modal/ModalMission.js, public/javascripts/SVValidate/src/modal/ModalMissionComplete.js, public/locales/en/audit.json, public/locales/en/common.json, public/locales/es/audit.json, public/locales/es/common.json, public/locales/es/validate.json
Resolves #2096 
Adds a couple Spanish translations for mturk, and fixes a bug that was messing up Spanish translations on the validation page's mission complete screen.
=> Fixes a few Spanish translations for mturk

app/views/validation.scala.html, conf/messages.en, conf/messages.es, public/css/main.css, public/javascripts/SVValidate/css/svv-menu-buttons.css, public/javascripts/SVValidate/css/svv-modal.css, public/javascripts/SVValidate/css/svv.css, public/javascripts/SVValidate/src/keyboard/Keyboard.js, public/javascripts/SVValidate/src/label/Label.js, public/javascripts/SVValidate/src/label/LabelDescriptionBox.js, public/javascripts/SVValidate/src/menu/MenuButton.js, public/javascripts/SVValidate/src/modal/ModalComment.js, public/javascripts/SVValidate/src/panorama/PanoramaContainer.js
Added an open text form under the validation buttons that allows users to give comments about a label during the validation process. This feature is not yet implemented on mobile. Resolves #2100
=> 2100 Add Validation Comment Text Field

conf/messages.en
Addresses https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2145
=> 2145 remove trash text from parenthetical

app/views/index.scala.html, conf/cityparams.conf
Used NBSP in order to make sure wrapping worked as intended and changed the MX-NLE tag to MX as requested by @jonfroehlich
=> #2140: Added SPGG to front page

public/javascripts/SVValidate/src/status/StatusExample.js
Resolves #2115 
Moved the vertical placement of the popup into the same function that handles horizontal placement and fixed the vertical placement in order to make sure the popup is in the correct location.
=> Fixed <#2115>: Fixed image popup location in validation

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
Resolves #2327 
This PR removed some of the redundancy on Keyboard.js and does not affect any functionalities.
=> #2327 Cleaning up Keyboard.js

app/views/userProfile.scala.html
Resolves #2337 
Fixed inconsistent rounding! Probably didn't need a whole new branch/PR for this? Not sure, here it is either way!
=> 2337-Uniform-Rounding

app/views/admin/index.scala.html
Resolves #2365 
**How I solved the problem**
At around line 800 in `app/views/admin/index.scala.html` I removed the line `<link href='@routes.Assets.at("stylesheets/bootstrap.min.css")' rel="stylesheet"/>`. I think this was causing a bootstrap conflict as it was trying to load two different styles.
=> 2365 admin navbar messed up

app/views/leaderboard.scala.html, app/views/leaderboardPage.scala.html, conf/messages.en, conf/messages.es, public/stylesheets/main.css
Resolves #2310 
Adds encouragement messages and links to the bottom of the leaderboard page, bolds and hyperlinks a user's username on the leaderboard if that user is signed in.
**Signed out:**
**Signed in:**
=> 2310-Leaderboard-Polishing

public/javascripts/SVLabel/src/SVLabel/PopUpMessage.js, public/javascripts/SVLabel/src/SVLabel/onboarding/InitialMissionInstruction.js
Fixes #2409 
Fixes the link to the "Please check both sides of the street" GIF.
Before:
After:
=> Fixes check both sides of street gif

public/javascripts/SVLabel/src/SVLabel/Main.js, public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js
Resolves #2143 
**What I did**
I created a function `public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js` which pushes all completed tasks into `previousTasks`, which is then later rendered by another function.
=> 2143 show streets previously audited

conf/evolutions/default/98.sql, public/javascripts/Choropleths/Choropleth.js
Fixes #2435 
Fixes a bug in the lat/lng approximation evolution file by doing some error checking in a `CASE WHEN` statement, since we're using an old version of postgis that doesn't have the error checking built in (we need to keep the angle between -2pi and 2pi). I also added in a tiny fix for a rounding error on the choropleths that I noticed.
=> Bug in latlng approximation evolution

app/controllers/GalleryController.scala
Resolves #2444 
Simple fix, just adding a List shuffle in the getLabelsByType method in GalaeryController.scala
=> Added shuffling for assorted labels in Sidewalk Gallery

app/controllers/GalleryController.scala, app/controllers/helper/GoogleMapsHelper.scala
Resolves #2439 
Adds a helper scala object to deal with Google Maps API operations.
=> Helper Scala Object Created for Google Maps API Related Operations

app/models/label/LabelTable.scala, app/views/gallery.scala.html, app/views/mobileValidate.scala.html, app/views/validation.scala.html, public/javascripts/Admin/src/Admin.GSVLabelView.js, public/javascripts/Gallery/css/cards.css, public/javascripts/Gallery/css/gallery.css, public/javascripts/Gallery/css/modal.css, public/javascripts/Gallery/css/tags.css, public/javascripts/Gallery/src/cards/Card.js, public/javascripts/Gallery/src/cards/CardContainer.js, public/javascripts/Gallery/src/displays/SeverityDisplay.js, public/javascripts/Gallery/src/displays/TagDisplay.js, public/javascripts/Gallery/src/modal/Modal.js, public/javascripts/Gallery/src/validation/ValidationMenu.js, public/javascripts/SVValidate/src/label/Label.js, public/locales/en/common.json, public/locales/es/common.json
Resolves #2587 
This PR aims to update the Sidewalk Gallery UI such that it better matches @isavin12's mocks. Here are some before and after screenshots:
Default landing page:
Before:
After: 
Expanded modal:
Before:
After: 
Validations:
Before:
After:
Other features like the autoscrolling (#2589) are provided in other issue threads
=> 2587 new gallery interface

app/models/label/LabelTable.scala
Resolves #2720 
Partially #2721 
We now hide "low quality" users' data from Gallery and Validate. I also added in a missing filter to make sure that we aren't showing tutorial labels on Validate.
=> Remove low quality users' data from Gallery/Validate

app/views/navbar.scala.html, public/stylesheets/main.css
Resolves #2567
- Made turker image and timer straight and right-aligned.
- Turker now looks the same for both screens in the hamburger menu and regular view.
- put style changes in css file
-
**Before**
**After**
=> 2567 turker timer looks messed up 

conf/messages.nl, public/locales/nl/audit.json, public/locales/nl/common.json, public/locales/nl/dashboard.json
Fixes a few typos and incorrect capitalization in our Dutch translations. Fixes provided by Timo!
=> Fixes Ditcj translations, courtesy of Timo Nieuwenhuis

public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js, public/javascripts/common/Utilities.js
Resolves #2839 
Removes the delay we saw on the test servers when opening the context menu on the Explore page. We changed loading of the tooltips to an asynchronous call to fix the delay.
=> Fixes delay in opening context menu on Explore page

app/views/mobileValidate.scala.html
Resolves #2894
Adjusted references to sidewalk logo to reference config file params in the mobile scala file.
Before:
After:
1.  If on Desktop, open website and open the browser DevTools to enable mobile device emulation. If on mobile, just open Project Sidewalk.
2. If the Project Sidewalk logo appears, then it is working correctly!
=> #2894: Fixed reference error to sidewalk logo in mobile version

conf/cityparams.conf
Resolves #2897 
Adds the brick tag in Mexico, where it was previously hidden.
=> Adds brick tag in Mexico

conf/cityparams.conf, conf/evolutions/default/152.sql, public/javascripts/common/UtilitiesSidewalk.js, public/locales/en/audit.json, public/locales/en/common.json, public/locales/es/audit.json, public/locales/es/common.json, public/locales/nl/audit.json, public/locales/nl/common.json
Resolves #2935 
Adds a 'level with sidewalk' tag for Crosswalks to Amsterdam.
=> Adds Crosswalk level with sidewalk tag to Amsterdam

app/models/label/LabelTable.scala
Resolves #2721 
Updates our prioritization of validations such that we will again validate labels from "low quality" users, just at a lowered priority. The prioritization adds a lot of weight to users with fewer than 50 labels validated and to labels with no previous validations. Prioritization for users that are marked as high quality is secondary but still important :) Though a large random component is added so that any label could be chosen.
=> Updates validation prioritization algorithm

app/models/label/LabelTable.scala
Resolves #2661 
This should give a decent speedup for loading Gallery.
Before this PR, we would go one label type at a time, and check each label of that label type for valid GSV imagery in parallel. Now instead of going one label type at a time, we combine all the label types together. This requires some more complicated accounting, keeping track of a mapping from each label type to a bunch of extra metadata. In the end, it only adds  a few more lines of code though.
Ultimately, we found around a 40% speedup in the portion of the page load that involves checking for GSV imagery. I tested on a database dump with 186k labels, testing 10 page loads in each case. In the situation where the whole database was already up-to-date on which labels had imagery, the time went from 1.75 seconds to …
=> Improve Gallery load time

conf/cityparams.conf
Resolves #3105
Adds the configs that we need to accommodate a new server for Taipei, TW! Here are a couple quick screenshots of the interface from my local dev environment.
=> Adds configs for a new Taipei server

conf/cityparams.conf
Resolves #3127 
Adds configs for a new Auckland, NZ server! Some screenshots of the interface below!
=> Adds configs for new Auckland, NZ server

public/javascripts/Admin/src/Admin.Panorama.js
Resolves #3169 
Change the jquery selector to target the id that I set for the a tag for "Explore the street". This should select the correct tag, but I wasn't able to reproduce the issue.
=> Change jquery selector to target specific id for Admin.Panorama

conf/cityparams.conf
Resolves #3264 
This adds the configs that enables us to set up a new server dedicated to mturk studies. The configs almost entirely mirror Seattle's configs, because we are planning to start with a Seattle seed database.
=> Adds configs for new crowd study server

conf/cityparams.conf
Adds configs for a new server in Teaneck, NJ. Hoping to have it up and running sometime next week!
=> Adds configs for Teaneck, NJ server

app/views/accessScoreDemo.scala.html, app/views/admin/task.scala.html, app/views/developer.scala.html, app/views/index.scala.html, app/views/labelMap.scala.html, app/views/results.scala.html, app/views/routeBuilder.scala.html, public/javascripts/Admin/src/Admin.Task.js, public/javascripts/Admin/src/Admin.User.js, public/javascripts/Admin/src/Admin.js, public/javascripts/Progress/src/Progress.js, public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionCompleteMap.js, public/javascripts/accessScoreDemo.js, public/javascripts/developer.js, public/javascripts/routeBuilder.js, public/locales/de/common.json, public/locales/en/common.json, public/locales/es/common.json, public/locales/zh-TW/common.json
Resolves #3371
We are now using the translations provided by Mapbox on all of our maps! Unfortunately, Dutch is not an option; other than that, we have translations!
Before
After
Before
After
=> Maps are now translated in Chinese, Spanish, and German

conf/cityparams.conf, conf/messages, conf/messages.zh-TW
Adds configs for a new server for Walla Walla, WA. I've sent a seed database to CSE Support. We are starting with just the "Central Walla Walla" neighborhood open!
=> Adds configs for new Walla Walla server

app/views/index.scala.html, conf/application.conf, public/stylesheets/homepage.css
Resolves #3425 
Updated application.conf to include a link to the website (is empty since the accessiblecommunities.org is not ready). Created a banner visible in the top right of the landing page, links to the website if URL is in application.conf. Otherwise, the banner is not visible.
Before (no banner):
After (banner):
=> 3425 Added banner overlay to landing page

app/controllers/ProjectSidewalkAPIController.scala, app/controllers/helper/ShapefilesCreatorHelper.java, app/models/attribute/GlobalAttributeTable.scala, app/models/street/OsmWayStreetEdgeTable.scala, app/models/street/StreetEdgeTable.scala, conf/evolutions/default/211.sql
Resolves #3438 
Implemented Batch processing to send features on /attributesWithLabels API and it slightly does better on local.
Tested it with multiplying data and reducing the mem as well!
=> #3438 attributeswithlabels api in seattle for shapefiles causes server to crash

app/controllers/CredentialsAuthController.scala, app/views/navbar.scala.html, conf/routes, public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js
Resolves #3412
updated CredentialsAuthController.scala by adding new logs to indicate general signin attempts and failed/successful signin attempts. each log contains a userid, ip address, message, and timestamp
=> Updated CredentialsAuthController.scala

app/views/routeBuilder.scala.html, public/javascripts/routeBuilder.js, public/stylesheets/routeBuilder.css
Resolves #3432
In this PR, I added search support to RouteBuilder by using the MapBox SearchBox API, which allows you to input some search text and it to zoom into that area on the map (this API is super well integrated into the actual map itself, so I was able to get it to do this with basically no code of my own)! I essentially just create a search object with the bounding lat/long coordinates of the current map as the bounds to search in, and call a method to bind the map and the search object, and it does the rest by itself.  As for filtering searches down further than the area visible by the map, I was not sure how to go about that since we want to be able to search for things like schools, etc, but when I looked at how the non-greyed out areas on RouteBuilder are specified, it seems …
=> Adding Search Support to RouteBuilder

app/controllers/helper/ShapefilesCreatorHelper.java, app/formats/json/APIFormats.scala, app/models/label/LabelTable.scala
Resolves #3534
Fixes the coordinates in the Shapefile version of the Raw Labels API. Also adds the OSM Street ID to all versions of this API.
=> Fixes Raw Labels shapefile API, adds OSM ID

conf/cityparams.conf, conf/messages, conf/messages.es, conf/messages.zh-TW
Resolves #3750
Resolves #3761 
Adds the necessary configs to support new deployments in West Chester, PA and Columbia, SC.
=> Adds configs for West Chester, PA and Columbia, SC

conf/cityparams.conf, conf/messages, conf/messages.zh-TW, db/scripts/create-new-schema.sh, db/scripts/hide-streets-without-imagery.sh
Adds configs for a new deployment in Maywood, NJ.
I made a couple of minor fixes to my scripts for setting up new cities while I was working through this as well.
=> Adds configs for Maywood, NJ deployment

public/locales/de/audit.json, public/locales/en/audit.json, public/locales/es/audit.json
Resolves #3811 
Replace this with a brief description of the problem solved or feature implemented and how you implemented it.
See comments on [previous PR for this issue](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/3823).
Changes: Reduced text to 2 lines, and modified translations that reflected this new text (some translations were the same).
Before:
After:
1. Open localhost:9000
2. Navigate to 'explore' -> Start mission
3. Click 'OK' on the popup
4. Pan around in main street view window to get mini map text to appear
5. Observe mini map text correctly shows new text (2 lines)
- [NA] I've added/updated comments for large or confusing blocks of code.
- [NA] I've updated any logging. Clicks, keyboard presses, and other user interactions should be logged. If you're not sure how …
=> Reduced text for minimap (in relevant languages)

app/views/index.scala.html, app/views/navbar.scala.html, conf/cityparams.conf, conf/messages, conf/messages.de, conf/messages.es, conf/messages.nl, conf/messages.zh-TW
Resolves #3880, #3881, #3883
Adds configs for new deployments in Madison, WI; Niagara Falls, NY; Chandigarh, India; and Tainan City, Taiwan.
This also fixes the drop down menu city list in the navbar for cities in Taiwan. We had hard-coded the list of Taiwanese cities instead of using the `countryId` field, and our list was out of date.
=> Adds Madison, WI; Niagara Falls, NY; Chandigarh, India; and Tainan City, Taiwan
