ProjectSidewalk/SidewalkWebpage

public/javascripts/SVLabel/src/SVLabel/status/LabelCounter.js

Rearranged the Label Counters so that Curb Ramp has its own row. The whole Label Counter section should probably be wider(obstacles is cut off). 
Created a larger circle to break down larger quantities by 50s. Updated the d3 plotting and animation. There were some issues with inconsistencies and glitches when counts were changed. This was fixed by updating the attributes of the existing circles, as well as the new ones.
Tested on Chrome with the results pictured above. Works in increments of +/-1 as the user would do, as well as changing from or to any value.

Label Counter Improvement

---

app/views/faq.scala.html

https://github.com/ProjectSidewalk/SidewalkWebpage/issues/153
Updated keyboard shortcuts in faq implemented earlier

FAQ keyboard shortcut update

---

public/javascripts/SVLabel/src/SVLabel/status/MissionStatus.js

Addressing https://github.com/ProjectSidewalk/SidewalkWebpage/issues/164
Implementing design from one of my first tasks.
Bar is the same shade of blue for all values below 100% at which point it becomes green.

Mission Completion Bar changed to Blue/Green

---

app/models/user/WebpageActivityTable.scala
app/views/admin/index.scala.html

Method added to Scala model to count occurrences of 'SignIn' with a specified UUID in user_role.
https://github.com/ProjectSidewalk/SidewalkWebpage/issues/191

Admin View SignIn Count

---

public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/Storage.js
public/javascripts/SVLabel/src/SVLabel/game/AudioEffect.js

This pull request resolves #307 by using Web Storage. A "muted" key is added to the TemporaryStorage class and it is used in the AudioEffect class instead of using a local variable which would disappear after reloading the page. This also works for anonymous users.
resolves #307

Implement #307: Store mute option

---

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js

Fix #262: Escape closes the example modal as well

---

app/views/main.scala.html

Twitter card's image is not correctly shown. Changed the relative path of image to absolute value to see if that works.

Change twitter card image path to absolute value

---

public/javascripts/SVLabel/css/svl-context-menu.css

Fixes the problem of the top-down map’s text appearing on the label pop-up message box, when the pop-up is very close to the GSV screen border such that it overlays on top of the top-down map.

Fix overlay label box issue

---

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js

The message initially was shown when the user was about to finish the route. This will show the message when the user is at the end of the route.

Show jump "finish labeling" msg when at the end of the current route

---

app/controllers/AdminController.scala
app/models/label/LabelTable.scala
app/views/admin/index.scala.html
app/views/main.scala.html
public/javascripts/Admin/src/Admin.js
public/stylesheets/admin.css

Resolves #386.
The JSON returned by  /adminapi/labels/all has been modified so that it contains information on severity. Slider bars have also been added next to all label types (excepted 'Audited Street') in order to allow additional filtering based on the severity of a specific label type.

Fixes #386: Admin Interface - Add in Filtering Based on Severity

---

app/views/admin/index.scala.html
public/javascripts/Admin/src/Admin.js

Resolves #516.
Added in a checkbox that allows a user to easily select/deselect all the label types in the map legend.

Implements #516 - Adding a 'select all' checkbox to the admin map

---

test_accept_asmts.py

It was pretty simple to implement, but I am not sure how to test it right now.
Are we able to create HITs, complete them, and then review them in the sandbox?

added script to accept mturk asmts that are ready for review

---

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js

Resolves #550 : The file-not-found error used to occur when pressing Shift+Z and moving simultaneously. Replaced one instance of the filename 'Cursor_ZoomOut.png,' which does not exist, with 'ZoomOut.png.'

Resolves 550 - Cursor_ZoomOut.png not loading occasionally

---

app/views/faq.scala.html

This change adds more space to the Key column of the FAQ Keyboard Shortcut table to prevent key overlapping. It does not have any side-effects to other parts of the application.
Resolves  #617

#617 FAQ Improved text spacing in the keyboard shortcuts table

---

public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js

Fixes #498. Added a line of code to reset the svl.labelCounter object in the _endTheOnboarding() function

Fixes #498. Resets the label count after onboarding ends

---

build.sbt
public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js

Fixes #679. Uses (temporarily) the tutorial pano id as the id after walking.

679 tutorial gsv error

---

public/javascripts/Progress/build/Progress.js
public/javascripts/Progress/src/Progress.js

This change allows the user to actively see the Neighborhood names as they click on the respective regions. This does not have any side-effects on other parts of the application.
Resolves #627

#627 Updated text that allows the user to select a neighborhood in the user dashboard

---

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js

Fixing bug caused by a commit in PR #701. Navigation arrows don’t show up again when the label is applied.

Removed linksControl setting statements

---

public/javascripts/Admin/src/Admin.js

Fixes #716 , onboarding time chart now checks that a user has completed onboarding before adding time to chart; bounce rate also takes new definition into account.

Fix onboarding time graph

---

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js

Resolves #705, #706. 
The delete icon and context menu should hide when the user chooses to walk using keyboard. Panning with the context menu open closes the context menu now instead of displacing it. Panning while hovering over a label should now hide the label tag and delete icon.

Resolved ui bugs with context menu and walking

---

app/views/index.scala.html

Text has been changed from:
"Your contributions help train machine learning algorithms to identify accessibility issues automatically"
to:
"Your labels are used to improve city planning, build accessibility-aware mapping tools, and train machine learning algorithms to automatically find accessibility issues."
In order to be more in line with the graphic that it is associated with.
Before and after in image form:
Resolves #720

"What we do with your lables" landing page text update

---

app/views/index.scala.html
public/stylesheets/choropleth.css

The legend size has been significantly increased...
Before:
After:
I don't think that we should make it much larger than this to avoid taking up too much space on small screens.
Partially addresses: #723

Increases legend size of landing page choropleth

---

public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVLabel/src/SVLabel/util/Utilities.js

Resolves #698.
Added recognition of iOS and Android operating systems, as well as the Chrome browser on iOS. These were being incorrectly recorded, but should now appear correctly. Though, since we disabled the /audit page for mobile devices, we won't likely record these devices in the audit_task_environment table.

Improve browser detection

---

app/controllers/UserController.scala
conf/routes
public/javascripts/Choropleth.js
public/javascripts/Progress/build/Progress.js
public/javascripts/Progress/src/Progress.js

Resolves #464 , now when the links in the bubbles from the choropleth or user dashboard map are clicked, it's logged in `webpage_activity` so the `activity` reads `SelfAssign_Region<RegionId>_<DistanceLeft>MilesLeft`, where the distance left is either 0, <1, 1 or >1.
Related to PR #742

'Click here' on choropleth and user dashboard maps now logged

---

app/views/navbar.scala.html

The new FAQ link will now open in a separate tab from the audit page
Resolves #759

#759 Open FAQ in New Tab

---

.gitignore

Resolves #760 , removed non-existent path, added path that does exist and needed to be gitignored (`public/javascripts/Progress/build/*`)

Fixes non-existent path in gitignore to a path that does

---

public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionContainer.js
public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js
public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js

Resolves #730 by displaying mission instructions after user completes tutorial. The pop-ups only show at the start of the first mission.
This PR also partially resolves #700 by displaying the mission instructions after the user clicks "skip the tutorial" without previously completing a mission.

Initial Instructions After Tutorial

---

app/views/faq.scala.html

Found another twitter link I had not previously updated, at the bottom of the FAQ page in the "Contact Us" section. That link is now updated to @projsidewalk. 
Resolves #514

#514 FAQ page twitter update link

---

app/views/faq.scala.html
public/assets/homepage.js

The embedded videos on the landing page (1) and FAQ page (5) now show no suggested videos.
Instead, when the video is completed, the only thing shown will be the replay button (see below example of end of landing page video).
resolves #726

Issue #726 Embedded Youtube Videos

---

app/controllers/UserController.scala
app/views/index.scala.html
app/views/main.scala.html
app/views/navbar.scala.html
conf/routes
public/assets/homepage.js
public/javascripts/Choropleth.js
public/javascripts/Progress/build/Progress.js
public/javascripts/Progress/src/Progress.js

Resolves #756 - at least, number 3 on the list. Now logs when users click on choropleth neighborhoods under the format `ChoroplethClickRegion<regionId>`.
Also, I changed logs for `Click here` link by adding if it was from the choropleth or the dashboard at the end of the activity string like this:
`SelfAssign_Region<regionId>_<distanceLeft>MilesLeft_Choropleth`
`SelfAssign_Region<regionId>_<distanceLeft>MildesLeft_Dashboard`
Please let me know if I should remove this.
Did not log mousing over the neighborhoods as it seemed there wasn't a clear consensus on that.
More precisely, resolves #721 but most of the discussion was in #756

Log choropleth neighborhood clicks

---

app/views/about.scala.html

All of the publication links and titles on the About page are corrected.
Before:
After:
Resolves #569

Issue #569 Update About Page Links

---

app/views/index.scala.html
public/javascripts/Choropleth.js
public/stylesheets/choropleth.css

Old look:
New look:
This zoom slider is more prominent, making zooming more obvious. This is important since mouse wheel zooming is disabled on the choropleth on the landing page.
Resolves #725 #723

Adds zoom slider to choropleth on landing page

---

app/views/audit.scala.html
public/javascripts/SVLabel/lib/gsv/GSVPano.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js

Each getParamByLocation() was changed to getParam() with a source property set to OUTSIDE, while maintaining the location and radius properties.
"...search only returns panoramas where it's possible to determine whether they're indoors or outdoors. For example, PhotoSpheres are not returned because it's unknown whether they are indoors or outdoors."
Therefore, photospheres are blocked from being returned.
Resolves #668 
Resolves #780 
Partially Resolves #718

Issue #780 Disable Photospheres

---

public/javascripts/SVLabel/src/SVLabel/util/Utilities.js

Fixes #698, part 2 :)
Added recognition of Edge browser; previously misrecognized as Chrome. Noticed in Google Analytics that we had Edge users, but didn't see any in my local environment's audit_. Added a condition to check for Edge and it's now being recorded correctly.

Fixed Edge recognition

---

app/models/daos/UserDAOImpl.scala

Resolves #791. Very minor SQL change to display the correct number of labels on the Anonymous Users table of the admin dashboard.

Display correct number of labels by Anonymous Users in Admin Users table

---

public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js

Resolves #814 
No labeling is possible when the delete message is shown. Figure below.

Disables labeling when 'delete label' message

---

public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/Storage.js
public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/mission/Mission.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionContainer.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMission.js
public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js

Resolves #826.
Now, as an anonymous user, if you have completed a mission other than onboarding in a browser session, the initial mission instructions will not appear even if you refresh or open the page in another tab.
Also resolved a minor issue of the link controls appearing behind the pop-up messages.

Added tracking for anonymous first mission completion

---

conf/evolutions/default/2.sql

Resolves #773 
Uses a Play Evolution to add a 'Researcher' role to the role table, and adds entries to the user_role table for each past and current researcher (for whom I could find a registered user by going through the past project members on the HCIL site and searching for usernames/email addresses based off of the names I found there).

Adds researcher role and adds entries for past/current researchers

---

public/javascripts/SVLabel/css/svl-modal.css
public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalComment.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalSkip.js

Resolves #840.
Used same disable interaction functionality as regular pop-up messages for the jump and feedback windows.
Removed redundant code that causes changes in Z and Shift+Z behavior.

Disabled interactions while giving feedback or jumping

---

public/javascripts/SVLabel/css/svl-context-menu.css
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js

If the context menu is low enough on the screen to get cut off, it will appear above the label rather than below label.
Normal:
Too Low:
Resolves #812

Issue #812 Context Menu Cut Off

---

app/views/faq.scala.html

Improved some grammar, readability, conciseness in the FAQ page. Also updated a thing or two to reflect changes since the FAQ was originally created (e.g., it now says Start Mapping instead of Start Auditing). 
Also added the Esc keyboard shortcut to the table. But I want some feedback on this, since it has the same function as the Enter key. So we could either leave it out, or one of the following option...
I currently have the 1st option in this PR.

updated some text in FAQ

---

app/views/audit.scala.html
public/assets/detectUnsupportedBrowser.js

Resolves #715. Now that we support all the browsers that we've tested, we no longer need to display the "Browser unsupported" message.
edit: got ahead of myself. we still should display this alert for browsers that aren't firefox, chrome, or safari. will commit this fix shortly

Removed unsupported browser message

---

public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js

On mousedown, the context menu will close, but now it will not immediately reopen on mouseup (which was the most significant annoyance reported by @misaugstad)
Resolves #849

Issue #849 Fix Error with Closing Context Menu

---

public/javascripts/Admin/src/Admin.js

For the user mission counts histogram on the admin dashboard, there is a checkbox for including data from the researchers in the histogram. The histogram was meant to initially exclude researcher data. The box was unchecked, but the graph that was actually including the researcher data to start.

mission count chart now defaults to excluding researchers

---

app/views/main.scala.html
app/views/navbar.scala.html

Resolves #874 ; logs for clicking links that appear on more than one page (i.e. the navbar links including Sign-In and Start Mapping, footer links and info-footer links) now have an additional key/value pair at the end of their log strings of the form `route=/<route>`, where `<route>` is obtained from the actual page the browser is currently on.

Added routes to logs for multi-page link clicks

---

app/models/audit/AuditTaskTable.scala
app/models/daos/UserDAOImpl.scala

Resolves #886 
The issue was that the audit count queries for today and yesterday did not exclude audits that were not marked as complete; this has been fixed in this PR. The total audit count query was already correct.

Audits completed today/yesterday now excludes incomplete audits

---

app/views/navbar.scala.html
public/css/main.css
public/javascripts/AccessibilityChoropleth.js

When clicking on the new Results button on the navbar, it was erroneously being logged as if the Start Mapping button was clicked. This should be fixed now.

Fixed logging of new results button on navbar

---

public/javascripts/AccessibilityChoropleth.js

Resolves #905 
The choropleth on the results page is now referred to as "ResultsChoropleth" instead of "Choropleth" when logging, to differentiate from the choropleth on the landing page.

differentiated b/w choropleths' logging

---

app/controllers/AdminController.scala
app/controllers/AuditController.scala
app/models/user/WebpageActivityTable.scala
app/views/admin/index.scala.html
conf/routes
public/javascripts/Admin/src/Admin.js

Fixes #860 
In a previous commit I made a bar chart to display this data but it seemed unnecessary for such few values and the VisitAudit value dwarfed the other two graphically. Replaced the chart with a table as pictured above. If a chart is desired, the most recent commit can be rolled back. Below is the chart for comparison:

Add Choropleth vs Start Mapping click statistic to admin page

---

app/controllers/SignUpController.scala
app/views/navbar.scala.html

Resolves #845 ; now Play's email validation is used instead of the one previously on the front-end. When 400 or 409 responses are received after incorrectly signing in or signing up, an appropriate error message is displayed.

Moved email validation to back-end and added handling for Bad Requests

---

app/controllers/ClusteringSessionController.scala
app/controllers/GTLabelController.scala
app/models/clustering_session/ClusteringSessionClusterTable.scala
app/models/clustering_session/ClusteringSessionLabelTable.scala
app/models/clustering_session/ClusteringSessionTable.scala
app/models/gt/GTExistingLabelTable.scala
app/models/gt/GTLabelTable.scala
conf/evolutions/default/4.sql
conf/routes

Running this branch will create the following groups of tables + their related models and controller (new evolutions were put into a new .sql file):
Tables for clustering sessions
- clustering_session
- clustering_session_cluster
- clustering_session_label
Tables for ground truth labels
- gt_label
- gt_existing_label
Check if the /clusteringsessions endpoint returns a json object containing all existing (deleted = False) sessions
Check if the /gtlabels endpoint returns a json object containing all ground truth labels

Added models to manage clustering of labels and ground truth labels

---

public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js

Resolves #940 
The tracker logs the entered description text in the event `ContextMenu_TextBoxChange` log.
Also, added logs for hitting enter and clicking outside the context menu to close the context menu - events `ContextMenu_ClosePressEnter` and `ContextMenu_CloseClickOut`

940 Log Description Text

---

app/views/index.scala.html

Fixes the two landing page tweets which incorrectly linked to our old twitter handle (@umd_sidewalk). They now appropriately point to @projsidewalk

952 landingpage fix twitter hyperlinks

---

app/controllers/TaskController.scala
app/models/label/LabelTable.scala
app/models/label/ProblemTemporarinessTable.scala
app/views/admin/index.scala.html
build.sbt
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/Tracker.js
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVLabel/src/SVLabel/label/Label.js
public/javascripts/SVLabel/src/SVLabel/label/LabelContainer.js
public/javascripts/SVLabel/src/SVLabel/label/LabelFactory.js

Resolves #937.
Our front end system on the audit page is now capable of updating labels after the first submission. Additionally, labels that have ratings / descriptions added after the first submission will continue to be updated as they are entered.
These are submitted as new label objects in the `submit` function within `Form.js` with the same temporary_label_id and task as the first label submitted. Next, we need to create a backend handler for these labels, likely within `TaskController.scala` to update rows in the table with matching temporary_label_id and task fields. @misaugstad and @manaswis told me today that they could work on this over the weekend.
As @jonfroehlich mentioned, this will need a lot of testing. While I ran through multiple interaction sequences (e.g. creating two …

Update labels in the database with changes from the frontend: severity, description, temporary status or deletions

---

app/controllers/MissionController.scala
app/formats/json/TaskFormats.scala
conf/evolutions/default/4.sql
public/javascripts/SVLabel/src/SVLabel/modal/ModalMission.js
public/javascripts/SVLabel/src/SVLabel/status/StatusFieldMission.js

Resolves #841 : Adds a 500-ft and 1000-ft mission to each region. Old 1000-ft mission is no longer sent to users, and if user has already finished old 1000-ft mission they do not receive the new ones. If the user has already completed the old 1000-ft mission, the new missions are not marked as completed by the user, and if the user completes the new 500-ft and 1000-ft missions the old 1000-ft mission is not marked as completed.

Replace first 1000-ft mission with two 500-ft missions

---

app/controllers/AdminController.scala
app/controllers/TaskController.scala
app/formats/json/LabelFormat.scala
app/formats/json/TaskSubmissionFormats.scala
app/models/label/LabelTable.scala
conf/evolutions/default/5.sql
public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/SVLabel/src/SVLabel/data/Form.js

Resolves #967 
Resolves #935
This adds a time_created field to the label table. All new labels that are added to the database get a timestamp, but the ones currently in the database have that field as null for now. We will backfill the old data later, as described in #974

Add timestamp field to label table

---

app/controllers/ApplicationController.scala
app/controllers/CredentialsAuthController.scala
conf/routes

Resolves #901 
If you visit
`projectsidewalk.io/referral?referrer=<someString>&endPoint=<someEndPoint>`
you will be redirected to `<someEndPoint>`, and in the webpage activity table, we will log
`Referrer=<someString>_SendTo=/<someEndPoint>`
A concrete example...
`projectsidewalk.io/referral?referrer=campaign1&endPoint=/results`
will send the user to `projectsidewalk.io/results` and log
`Referrer=campaign1_SendTo=/results`
And the `<endPoint>` param is optional, and will just default to the landing page.

Added ability to use custom url to access any PS page

---

app/controllers/AuditController.scala
app/controllers/MissionController.scala
app/controllers/RouteController.scala
app/formats/json/TaskSubmissionFormats.scala
app/models/mission/MissionTable.scala
app/views/audit.scala.html
conf/routes
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVLabel/src/SVLabel/mission/Mission.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionContainer.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionFactory.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionModel.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionProgress.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalModel.js

We can now present multiple routes to a turker as successive missions within a single HIT. Related to pull request #972 . This pull request should only be tackled after #972. This is because it builds on the code for sidewalk-mturk-v2-restrict-turker-to-single-volunteers-routes which is the more stable predecessor (partly due to how HIT are mapped to individual missions). Most of the modifications are either to javascript files or the controllers. No changes were made to the database. 
You'll see the following additions:
- At the end of a route the modal mission completion popup will have a "Continue" button that will load the next route. When the turker has completed all assigned routes a "Submit HIT" button should replace the "Continue" button. It will perform a POST request to the …

Added code to present all assigned routes successively in a single HIT session to MTurkers

---

app/controllers/AuditController.scala
app/models/amt/AMTAssignmentTable.scala
app/models/turker/TurkerTable.scala
conf/routes

Procedure for testing is the same as #981 . There is now a separate endpoint auditCondition that takes the conditionId in the query string.
Visit the url http://localhost:9000/?assignmentId=some_string&workerId=some_string&hitId=some_string&conditionId=come_condition_id&turkSubmitTo=localhost:5000/post . This will automatically assign you to the specified condition id.
This will be useful for ground truth collection. HITs can be generated on MTurk sandbox with a mapping between HITs and conditions.

Added an endpoint to audit the routes associated with a specific condition

---

app/controllers/AdminController.scala
public/javascripts/Admin/src/Admin.js

Resolves #944, possibly; since the 404 only occurs on the development server and there were no error logs, it won't be possible to tell if this is resolved until this change is pushed to development.
Based on an educated guess, this change encodes the URI component `route=/` twice as opposed to once as previously, to possibly avoid the server automatically decoding it. Also decodes twice since decoding a string without %'s is just the string.

Double-encoded 'route=/'

---

app/controllers/AuditController.scala
app/controllers/TaskController.scala
app/models/audit/AuditTaskTable.scala
app/models/street/StreetEdgeRegionTable.scala
app/models/user/UserCurrentRegionTable.scala
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
public/javascripts/SVLabel/src/SVLabel/neighborhood/NeighborhoodModel.js
public/javascripts/SVLabel/src/SVLabel/task/Task.js
public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js

Resolves #839 
If the neighborhood is incomplete, it now first routes the user through the neighborhood streets that are unaudited by anyone. Once the neighborhood is complete, the routes that are unaudited by the 
user personally are given.
For testing: Choose a neighborhood that is relatively small in size and that is towards completion. I have left debug comments, so you can see in the console how the routes are assigned and how neighborhood progress happens.
**TODO: One other small thing that is remaining**: Once the user personally completes a neighborhood, they should be assigned an incomplete neighborhood. During testing, I got a completed neighborhood.

839 assign unaudited streets

---

public/javascripts/SVLabel/src/SVLabel/mission/MissionProgress.js

The svl.amtAssignmentId variable is used to set the assignmentId directly for new tasks and indirectly for audit task table's amt_assignment_id. In the previous code all the tasks for the new route were being fetched before the svl.amtAssignmentId variable was updated so they would have the value of the previous amtAssignmentId. I changed the location of the code which fetches the tasks on a route to after the svl.amtAssignmentId variable was updated which resolves the issue.
Note: When @misaugstad encountered #1017 he had only worked on 2 routes which ended up having the same amt_assignment_id s. I used a set of routes for testing. This resulted in the first 2 routes having the same amt_assignment_id and the third route having the amt_assignment_id that was expected for the second route. …

#1017 Resolves the delayed updation of amt_assignment_id in the audit task table

---

app/controllers/AdminController.scala
app/models/audit/AuditTaskInteractionTable.scala
app/views/admin/index.scala.html
conf/application.conf
conf/routes
public/javascripts/Admin/src/Admin.js

*This issue was tabled earlier, as the ground truth resolution tool was a higher priority.
Now, histograms are added to the Admin page that show total time users have spent interacting with the audit tool (all users, registered users, anonymous users). Researchers are excluded.
Total time is calculated by looking at meaningful audit task interactions, and any that occur more than 5 minutes apart, that elapsed time is not included. The user was likely not actively engaging with the tool, and left their computer stagnant.
This query can be modified to calculate onboarding times or time per 1000 feet, as requested.
Resolves #983 
Resolves #984

Auditing Time Histograms

---

app/controllers/AuditController.scala
app/controllers/CredentialsAuthController.scala
app/controllers/RegionController.scala
app/controllers/SignUpController.scala
app/models/audit/AuditTaskTable.scala
app/models/region/RegionTable.scala
app/models/user/UserCurrentRegionTable.scala
app/views/accessScoreDemo.scala.html
app/views/audit.scala.html
app/views/developer.scala.html
app/views/faq.scala.html
app/views/index.scala.html
app/views/navbar.scala.html
app/views/student.scala.html
conf/routes
public/javascripts/SVLabel/spec/SVLabel/mission/MissionProgress-spec.js
public/javascripts/SVLabel/spec/SVLabel/neighborhood/NeighborhoodModel-spec.js
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionContainer.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionProgress.js
public/javascripts/SVLabel/src/SVLabel/neighborhood/NeighborhoodModel.js

Resolves #997 
- Updated front-end to assign a least audited new region to a registered user when the user selects a region that has already been completely audited by them
- Modified `assignRandomly()` function to now assign regions that are least audited for a new registered user
- Modify the method that assigns an easy region to an anonymous user to get least audited regions
- Updated `/audit` controller to take query string in the following way:
- `/audit?nextRegion=easy` --> it will assign easy regions to a registered user -- Used for the screen that is shown when a difficult neighborhood is chosen. Accordingly, updated the link on the front end to use this. Therefore, user of `/audit/easyRegion` has been deprecated. (Added in PR #832)
- `/audit?nextRegion=regular` --> for signed in …

997 assign least audited region to new users

---

build.sbt
public/javascripts/AccessibilityChoropleth.js

Moved the legend to the top right corner so you no longer have to scroll to the bottom of the screen to see it.
Before: 
After:

1028-Results Choropleth Updated Legend Position

---

app/views/audit.scala.html
public/css/main.css
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js

Resolves #926 
**NOTE:** This code is dependent on PR #1010. This issue branch was made from the branch related to issue #997. So PR #1010 should be reviewed and merged first. Only a couple of files has changed that are relevant to this PR (once PR #1010 is merged).
1. Now, after a user helps complete a neighborhood, it shows that a message box informing them and giving them two choices - (i) to continue in the same neighborhood or (ii) go to a new neighborhood (one amongst the least audited ones). Here are the screenshots:
**Case 1:** This was triggered when the user completed a street and that led to neighborhood completion. However, the mission was still incomplete.
**Case 2:** This was triggered at the end of a mission when the neighborhood was marked as complete.
2. This PR also …

926 overlay post neighborhood completion

---

app/models/amt/AMTConditionTable.scala

Resolves #1046. Changed the sql query that checks which conditionId s have been worked on the least. Excluded HITs completed by mikey, steven, and ryan's workerIds along with a test id. Also included a filter for conditions (hardcoded in the sql query right now).
Testing this is probably easier by connecting to the database and running the following sql queries:
- **Get a list of non-researcher HIT assignments**:  This should return an empty view 
`Select * from sidewalk.amt_assignment where turker_id not in ('APQS1PRMDXAFH','A1SZNIADA6B4OF','A2G18P2LDT3ZUE','TESTWORKERID')`. 
- **Get a list of conditionIds along with the count of non-researchers who have worked on them**: This should return a zero count for every conditionId 
`SELECT amt_condition.amt_condition_id, count(condition_id) as …

Resolves #1046 excludes researcher HITs from condition assignment calculation

---

app/models/amt/AMTConditionTable.scala
connect.py
hit_creation.py

Made the following changes:
- Modified hit_creation.py. This is the main HIT generation function. It will create a single HIT with the specified number of HIT assignments i.e. number of people who will need to work on the conditions. The turkers will be assigned to each condition in a round robin fashion. The function doesnt explicitly create a HIT for each condition since, as mentioned previously, the assignment of turkers to conditions is handled by the sidewalk-mturk server on the "\" endpoint.
- I've added my MTurk worker_id to the list of ids to exclude. (I was testing on MTurk sandbox and left the test mission incomplete).
To test:
- You will just need to modify the number_of_assignments to some small number (It is 1 by default) and run the hit_creation.py file.
- Check the worker …

Modified hit_creation.py to suit our current iteration of experiments

---

app/views/audit.scala.html
public/javascripts/SVLabel/src/SVLabel/mission/MissionProgress.js

Resolves #1054 . The mission completion popup stats were being updated after the next route and mission were loaded. This caused the stats to get reset to zero and show up as such. 
To test this just audit any random condition and place some number of labels. The label count on the mission completion popup should be the same as the number and type of labels you actually placed.
Also verify that the HIT submission button text is now "You're all done! Submit HIT!"

Resolve 1054: Mission completion popup showing 0 labels placed

---

app/controllers/AuditController.scala
app/models/amt/AMTVolunteerRouteTable.scala
app/views/noAvailableMissionIndex.scala.html
conf/routes
hit_creation_for_conditions.py

Also modified the text on the view when no missions are available either because the condition specified is not the same as the one requested, or because all the routes in that condition have been completed.
Things to test:
- If you already have some turker M1 in your turker table assigned to condition 72 visiting the turkAuditCondition endpoint with 
- conditionId=72 ((http://localhost:9000/turkAuditCondition?assignmentId=A1M1&workerId=M1&hitId=H1M1&conditionId=72&turkSubmitTo=localhost:5000/post)) should display 
- the next incomplete route in that set if you haven't already finished all of them.
- a "Please return this HIT" message if you've already completed all assigned missions 
- conditionId != 72 ((http://localhost:9000/turkAuditCondition?assignmentId=A1M1&workerId=M1&hitId=H1M1&co …

Created a new endpoint for the turkers to audit a specific condition

---

app/views/audit.scala.html
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionProgress.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMission.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js
public/javascripts/SVLabel/src/SVLabel/status/StatusFieldNeighborhood.js

Resolves #1067 . Replaced neighborhood stats with the current mission number at 3 locations. 
At the start of a mission:
During the mission: on the dashboard:
On mission completion modal:
I realize that I still need to make some style changes (especially on the mission completion modal). I need feedback before I do anything else.

Resolves 1067: HIT progress (number of missions completed and left) is now visible to Turkers

---

app/controllers/ApplicationController.scala
app/controllers/MissionController.scala
app/controllers/TaskController.scala
app/formats/json/TaskSubmissionFormats.scala
app/models/amt/AMTAssignmentTable.scala
app/views/audit.scala.html
conf/evolutions/default/6.sql
conf/routes
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js

Resolves #1043. For turkers on the production site their HIT is considered complete when they complete their first 500ft mission. I've include code for that first mission completion event that updates the assignment_end time, and a boolean completed variable. 
To test this
- Login as a turker by visiting the landing page using the referrer "mturk" and provide hitId, assignmentId, and workerId parameters in the query string. For example: localhost:9000/?referrer=mturk&hitId=h9h9h9h&workerId=w9w9w9w9w9&assignmentId=a9a9a9a9
- Check if your username is the same as your workerId
- Check the amt_assignment table and verify that a record has been inserted for your turker session. The completed field should be set to False and the assignment_end field should be blank.
- Complete a mission on the …

Resolves #1043: Update a Turker's record in the assignment table on HIT completion

---

app/controllers/AuditController.scala
app/models/amt/AMTAssignmentTable.scala
conf/evolutions/default/7.sql

Resolves #1096 
I've added an `accepted` column to the amt_assignment table that defaults to null. Right now we are running a Python script that accepts/rejects assignments from mturk. Updating the rows in this database to go from `null` to `true` or `false` would be done within this script.
To test:
1. Use a dump that had previously been running `sidewalk-mturk-v2` branch; use one that already has some entries in the `amt_assignmen`t table.
2. Compile and run; check that there are not "database in an inconsistent state" errors.
3. Verify that the evolution has been applied by looking at the the `amt_assignment` table, checking that it now has a new column `accepted` which is `null` for every entry.
4. Get yourself assigned something (go to …

Added accepted column to amt_assignment table

---

.gitignore
app/controllers/ClusteringSessionController.scala
app/controllers/GroundTruthResolutionController.scala
app/formats/json/ClusteringFormats.scala
app/models/amt/AMTAssignmentTable.scala
app/models/clustering_session/ClusteringSessionTable.scala
app/models/turker/TurkerTable.scala
app/views/gtresolution.scala.html
conf/routes
label_clustering.py
public/javascripts/gtresolution.js

I have modified the GT resolution tool to also have the option of going through a single person's labels, prompting the user to fill in any severity ratings that are null. It then adds these labels (both the ones that already had severity and the newly updated ones) to the gt_label and gt_existing_label tables.
There are two main things to test: that I didn't break the previous functionality of the tool, and that my new functionality works. I will send @manaswis a dump from mturk server that is recent enough to include any data I may be assuming is present in these instructions.
One preliminary thing to do:
Make sure you have all the correct python libraries installed to run the clustering code. The easiest way to check is to open up `label_clustering.py`, copy all the import statements …

Modified GT resolution tool to update null severities for a single labeler

---

public/css/main.css

Resolves #1106 
There was a lot of extra white space on the landing page legend choropleth. By editing the width in main.css, I was able to decrease the white space.

Resolves #1106: Landing Page Legend Choropleth Extra Space

---

app/views/audit.scala.html

Resolves https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1104#issuecomment-332334864
Removes the comma in the advanced neighborhood overlay.

Removed errant comma

---

public/css/main.css

Resolves Issue #1110 
Edited the width percentages in the main.css file to make the Advanced Neighborhood overlay box more centered on the page.

Resolves #1110: Fixes window in the advanced neighborhood overlay

---

public/javascripts/SVLabel/src/SVLabel/Main.js

Resolves #1091 . Complete the first 2 missions to display the survey. Try pressing labeling keyboard shortcuts and check that the label buttons don't get selected.
Please remember to check that the browser has reloaded svlabel.js or try this in incognito mode

Disabled labeling buttons on survey display

---

public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js

The action of clicking on the "generate confirmation code" would initialize the Orange MTurk code button next to the canvas. When turkers accidentally dismissed the completion popup by clicking outside the MTurk code button would remain hidden and hence #1113. I've removed the additional "click to generate code" requirement to just auto display the code and unhide the MTurk code button on the first mission's completion. 
To test:
1. Login as a turker using the mturk referrer for example localhost:9000/?referrer=mturk&hitId=h1&workerId=worker_bob&assignmentId=a1 
2. Complete the first mission.
3. Check that the mission completion popup shows the completion code instead of a "click to generate ..." button.
4. Check 2 cases 
- Clicking outside the popup still creates the MTurk Code button to …

Resolves #1113 : The confirmation code is now auto displayed on the mission completion popup

---

app/views/audit.scala.html
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js

Resolves #1118. The mturk code button was hidden using css "display:none". The button occupies zero space using this method which was messing with the position of the onboarding message for the jump button. **Ideally the position of these messages should be linked with the associated element's id but they are instead hardcoded as absolute positions**. I've switched to modifying the "visibility" attribute instead so that the mturk code button occupies space even when it is hidden.
To test:
1. Use the mturk referrer to login as a turker.
2. When you go through onboarding before completing any missions check that you only see 3 left column buttons (jump,sound, and feedback). It doesnt matter when you retake the tutorial after completing a mission since the mturk code button will be visible …

Resolves #1118 Onboarding jump message is now aligned with the jump button

---

app/views/index.scala.html

Resolves #1127 : 
Before, the miles within the landing page text did no match the one displayed below it. 
I edited it so that the two numbers circled in red are equal to one another. 
Issue was the text was static, just had to change it to be the variable that pulls the number of miles in.

Resolves #1127: Landing Page miles static. Should be dynamically calculated

---

app/models/gsv/GSVOnboardingPanos.scala
app/models/label/LabelTable.scala
conf/evolutions/default/7.sql
public/javascripts/AccessibilityChoropleth.js

There are many situations where we will want to weed out tutorial labels, particularly for analysis and on the admin dashboard. For now, I have just removed them from the results choropleth b/c it is public facing and we want to start driving traffic there again.
I made sure to exclude the pano ids from the current version, as well as the old version, of the tutorial.
We chose to add this as a separate table solely because of the ease of implementation. Perhaps it would be best to just include a boolean `tutorial` column in the label table instead. This could still be done in the future.
Here are before and after pictures of the results choropleth:
Resolves #980

Adds gsv_onboarding_pano table, filters onboarding labels from results choropleth

---

public/javascripts/AccessibilityChoropleth.js
public/javascripts/Admin/src/Admin.js
public/javascripts/Choropleth.js
public/javascripts/Progress/src/Progress.js

I have removed the zooming and centering that occurs when clicking on a neighborhood in all choropleths. Here are the choropleths that I have verified that the zoom in has been removed from:
1. landing page
2. user dashboard
3. results page
4. admin dashboard map tab
5. admin dashboard analytics tab
Let me know if I have forgotten any!
Before clicking on a region (looks the same):
How it used to look after clicking:
How it looks with the changes I made:
Resolves #1141

Removed zoom and center on click from all choropleths

---

public/javascripts/SVLabel/src/SVLabel/label/LabelContainer.js

Resolves #497 
As mentioned in the comment I made in issue #497 , if you deleted a label that you placed, then when you completed the mission, that deleted label was still being included within the label counts. This caused the total label counts for any neighborhood to be incorrect. 
I resolved this by fixing LabelContainer.js
In this file, anytime a user would add a label, that label was pushed to neighborhoodLabels. But whenever a user deleted a label, it was never removed from neighborhoodLabels. I just added a line to "pop" the label from neighborhoodLabels and now it functions properly.

Resolves #497: Label count was including labels that were deleted

---

app/views/admin/user.scala.html

Before:
After:
What it looks like when there _is_ an entry in the table:
And for the person reviewing the PR, I guess you can't use the .getOrElse method in this situation, because it is in a .scala.html file. Not entirely sure what that's about, but I guess we have to use .map first? Anyway, I guess this is how you do it when using the Play framework, so there you go.
Resolves #1193

1193 Fixes None.get error after truncating user_current_region table

---

app/controllers/AuditController.scala
app/controllers/AuditPriorityController.scala
app/controllers/TaskController.scala
app/controllers/UserProfileController.scala
app/models/audit/AuditTaskTable.scala
app/models/region/RegionTable.scala
app/models/street/StreetEdgePriorityTable.scala
app/views/main.scala.html
conf/routes
public/javascripts/Admin/src/Admin.js
public/javascripts/SVLabel/src/SVLabel/task/Task.js
public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js

* Updates the front-end routing to be entirely based on priority
* Rewrites the task selection code in AuditTaskTable.scala to assign tasks based on priority instead of completion count. This is the most annoying part to test, because there are something like 6 different cases to test for.
* Removes a few large-ish chunks of code that we are no longer using, and I don't see a reason to keep - let me know if you disagree with any of those choices :)
* Generally cleaned up any code I saw that needed some cleaning... So I removed a bunch of unused import statements (which is why the PR has 11 modified files), fixed misspellings, renamed variable, made some minor changes to syntax to make things more readable/consistent, etc. I'm going to go through the PR and add comments next to anything …

1207 full priority based routing

---

app/controllers/AuditController.scala
app/controllers/CredentialsAuthController.scala
app/controllers/RegionController.scala
app/models/audit/AuditTaskTable.scala
app/models/label/LabelTypeTable.scala
app/models/mission/MissionTable.scala
app/models/region/RegionTable.scala
app/models/user/UserCurrentRegionTable.scala
app/views/admin/index.scala.html
app/views/audit.scala.html
app/views/index.scala.html
app/views/results.scala.html
app/views/userProfile.scala.html
public/css/main.css
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/neighborhood/NeighborhoodModel.js

This PR updates the code that selects and assigns regions to make use of our new priority-based system.
The code is used when a new user comes to the site and needs to be assigned a neighborhood to audit, when a user finishes auditing a neighborhood completely, and any time an anonymous user visits the audit page.
Previously, a user would be assigned to one of the neighborhoods that had the lowest completion percentage. Now a user is assigned to a neighborhood with one of the 5 highest average priorities across its streets.
Testing:
I added print statements in the relevant places, so when you run each case, note the output of the print statements.
1. Visit the audit page as an anonymous user. You should see the following print statements
EASY SELECTION
GENERIC SELECTION
Highest priority …

1214 assign region from priority

---

app/controllers/AuditController.scala
app/controllers/RegionController.scala
app/models/user/UserCurrentRegionTable.scala
app/views/admin/user.scala.html

It seems that we were trying to update entries in the `user_current_region` table without checking whether or not there was any entry in the table to update. I created a new `saveOrUpdate` function that does the appropriate check, and adds a new entry for the user if they don't have one.
This also fixes the bug #1220 where the region for user was being displayed incorrectly on the admin dashboard.
You can test this by trying to come to the site as a new turker (i.e., through a referrer link like [http://localhost:9000?referrer=mturk&workerId=testworker1&assignmentId=testasmt1&hitId=testhit1](http://localhost:9000?referrer=mturk&workerId=testworker1&assignmentId=testasmt1&hitId=testhit1). It should assign you a new region when it automatically signs you up. So you can then check the …

fixed bug where users were not being assigned regions

---

app/views/admin/user.scala.html
app/views/userProfile.scala.html
public/javascripts/Admin/src/Admin.User.js

For #155
| Before | After |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/25534091/42187515-35ea43b6-7e05-11e8-8c44-37436636589f.png) | ![image](https://user-images.githubusercontent.com/25534091/42187524-3dd002fa-7e05-11e8-8392-d3cc47382aa6.png) |
| ![image](https://user-images.githubusercontent.com/25534091/42187530-45b87aba-7e05-11e8-8377-d23100a56aa7.png) | ![image](https://user-images.githubusercontent.com/25534091/42187542-4b3b661e-7e05-11e8-89cf-1bd2338b8863.png) |
Changes:
* Added another section under General Info to display total label counts
* Aligned header text for Labels/Feedback sections (snuck in this change because it's a quick fix)

Resolves #155: Add label counter table to admin user interface

---

public/javascripts/SVLabel/src/SVLabel/Main.js

Fixes #1274 
There was some CSS renaming that happened earlier (when removing bus stop code), and there was one part of `Main.js` that wasn't updated.
Labels in the tutorial flash again!

Resolves #1274: Make label buttons flash

---

app/models/attribute/GlobalAttributeTable.scala
app/models/attribute/UserAttributeLabelTable.scala
app/models/attribute/UserAttributeTable.scala
app/models/attribute/UserClusteringSessionTable.scala
app/models/audit/AuditTaskInteractionTable.scala
app/models/audit/AuditTaskTable.scala
app/models/street/StreetEdgePriorityTable.scala

Fixes conflicting imports of Tag objects from different libraries by making each import more explicit. I tested that this now compiles correctly from scratch on the dev server.
Fixes #1282

resolves #1282 fix tag naming conflicts

---

app/models/label/LabelTable.scala
app/views/admin/index.scala.html
public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/Admin/src/Admin.js

Tags are added to admin interface, comma seperated. Looks like this:
and this:
Description removed from table, but still exists in dialog.
Created seperate sql query for getting the tags because copy pasting into each of the three queries seemed redundant.

fixes #1285, adding tags column to description overview

---

public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js

Fixes #1260 
Fixes the problem where the instructions obscured the curb ramp by making the user pan left a bit more. Looks like this:

fixed  onboarding so that intersection is not obscured by instructions

---

app/views/admin/index.scala.html
app/views/admin/user.scala.html

fixes #1234 
in case where description is empty or null, display the label key value instead.
new admin table:
new user table:
old admin table:
old user table:

shows 'Other' label in user and admin tables, fixes #1234

---

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js

Resolves #1255.
The Google Maps 'pano_changed' listener is triggered twice when we switch panoramas: once when we are transitioning between panoramas, and once when we set the new panorama. I added a check to see if it was the same as the previous panorama ID that was logged.
Go to the audit screen and try to walk around a bit. You can try stress-testing the system by rapid clicking the Street View arrows.

Resolves #1255: fixes duplicate pano id logging

---

public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/Admin/src/Admin.Panorama.js

Fixes #976 
The blank panorama is caused by a bug in the Google StreetView API that doesn't load the panorama w/ the PanoID correctly the first time. There was a workaround we used earlier of resizing the window (because I think it forces the panorama to refresh). I added a callback function (which is similar to what we do in Onboarding) that will force the panorama to refresh itself. It should load without having to resize the window now.
I also modified the zoom levels in the admin panorama to more closely reflect what the user sees. (The zoomLevel seems to depend on what size the Google StreetView window is, which is sort of odd -- when I made the window bigger in #1308, I forgot to adjust the zoomLevel too).
* Open the admin page. Go to page ~100(ish) on the …

Resolves #976: Fixes initial blank panorama

---

app/views/developer.scala.html
app/views/faq.scala.html
app/views/main.scala.html
app/views/terms.scala.html
app/views/turkerIdExists.scala.html

resolves #1318 
Changes email address on webpage from sidewalk@umiacs.umd.edu to sidewalk@cs.uw.edu
Ignore PR #1331 since it was branched from master instead of develop

1318 update webpage email2

---

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js

Resolves #1237.
* Allows keyboard shortcuts corresponding to the current label to close the context menu.
* Interactions for closing the context menu are logged by `ContextMenu_CloseKeyboardShortcut` and `KeyboardShortcut_CloseContextMenu`.
Testing instructions: 
* Try using keyboard shortcuts to close the context menu during a regular mission + the Onboarding tutorial, and make sure everything still works okay.
* Try closing out of the context menu with the wrong keyboard shortcut (try pressing `m` when the curb ramp context menu is open) - nothing should happen here!
* When you close the context menu using the keyboard shortcut, make sure that `ContextMenu_CloseKeyboardShortcut` and `KeyboardShortcut_CloseContextMenu` events show up in the `audit_task_interaction` table

Resolves #1237: allows keyboard shortcuts to close context menu

---

anonymize.py
app/controllers/ApplicationController.scala
app/models/audit/AuditTaskInteractionTable.scala
app/models/daos/UserDAOImpl.scala
app/models/daos/slick/DBTableDefinitions.scala
app/models/label/LabelTable.scala
app/models/sidewalk/SidewalkEdgeTable.scala
conf/evolutions/default/19.sql
hit_approve_bonus.py

Resolves #1146 
Changes the name of the `user` table to `sidewalk_user` so that we don't have to put the name of the table in quotes or use "sidewalk.user" each time we reference the table. We no longer have a table with the same name as a postgres keyword :roll_eyes: 
NOTE: Do not review this PR until PR #1319 (updating mission infrastructure), #1327, and #1328 have been merged. I branched this code off of the code in that PR instead of the code on develop (b/c each of these PRs creates a new evolutions file, and it would be annoying to have a merge commit where I change the name of the evolutions file every time I merge a PR.
Testing:
* Test that the evolution file works correctly in that the table name changes to `sidewalk_user` when compiling and running the code on this branch, and …

1146 change name of user table to sidewalk_user

---

app/models/user/VersionTable.scala
conf/evolutions/default/20.sql

Resolves #653 
This PR adds a `version` table that has the following columns:
* `version_id` a string,
* `version_start_time` a timestamp, and
* `description` an optional string
Using this table, we will be able to keep track of the times when versions are released, which should help us to version-based queries in the future. For example, we may improve our logging in some future version, and we may need to calculate something for the admin page differently for the two different modes of logging (which has happened to us in the past). We can then get the timestamp of the change in version from this table, and use that timestamp in our queries where appropriate.
The way I see entries being added to this table is as follows: When we merge code into master, we just increment the version …

653 adds version table

---

public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js

Resolves #1334 
- Prevented the enter key from interfering with label tag selection by blurring the tag element after it has been clicked.

Resolves #1334: Prevent enter key from interfering with label tag selection

---

public/javascripts/SVLabel/spec/SVLabel/status/StatusFieldMissionProgressBar-spec.js
public/javascripts/SVLabel/src/SVLabel/status/StatusFieldMissionProgressBar.js

Resolves #510 
Added an if check so if the percentage of the mission complete is less than 100% and greater than or equal to 99.5%, the percentage complete gets rounded down to 99%. Also, added a unit test to check that this code change works properly.
To test:
- Run the StatusFieldMissionProgressBar-spec tests to ensure the newly added test properly rounds down the percentage

Added 99% round down check to avoid unwanted display of mission 100% complete

---

app/controllers/ApplicationController.scala
app/controllers/AttributeController.scala
app/controllers/AuditController.scala
app/controllers/CredentialsAuthController.scala
app/controllers/MissionController.scala
app/controllers/ProjectSidewalkAPIController.scala
app/controllers/SignUpController.scala
app/controllers/SurveyController.scala
app/controllers/TaskController.scala
app/controllers/UserController.scala
app/models/audit/AuditTaskTable.scala
test/models/audit/AuditTaskInteractionSpec.scala
test/models/labels/LabelTableSpec.scala

Resolves #1300 
I replaced any usage of the `Timestamp` class to use `Instant.now.toEpochMilli` instead of whatever alternative it had used before, as per the instructions in #1300. Most of the previous code was using the joda library, so I removed those imports as well. 
To test:
- Make sure that timestamps are working the same as before. Everything should compile and function identically
- Any Timestamps initialized as `lazy val`s I kept as lazy values, make sure this keeps the intended functionality

Resolves #1300: Standardize Dates

---

app/views/audit.scala.html
public/javascripts/SVLabel/css/svl-context-menu.css

Partially resolves #1281.
This adds an "Add Tags:" label to the tags, to make them more noticeable as the user is completing the mission. I had to change the padding on each of the tags to make it fit for all features. 
To test, launch a mission and validate that the "Add Tags" label is showing up correctly.
Here is how it looks for each accessibility feature:

1281 next city make tagging more noticeable

---

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js

Resolves #678, #999. 
* Panorama no longer zooms in when the +/- keys are pressed
* ContextMenu no longer closes when the +/- keys are pressed
I added the following line to `MapService.js` which disables +/- keyboard shortcuts.
```
svl.panorama.set('scrollwheel', false);
```

Resolves #678, #999: removes +/- (plus and minus) zoom keyboard shortcuts

---

public/javascripts/SVLabel/src/SVLabel/navigation/Compass.js

Resolves #552 
- Changed text at end of route to help user know to highlight the last intersection
Doesn't seem like it would have any side effects. Only a text change.
To test:
- Finish mapping a neighborhood (until you reach the final intersection and see a "You have reached the end.." tooltip)
- Verify that the tooltip text has changed to "You have reached the end of this route. Finish labeling this intersection then **click here to move to a new location**."

#552: Ambiguous 'You Have Reached End Of This Route'

---

app/models/street/StreetEdgeTable.scala
conf/application.conf

Resolves #1338 
`totalStreetDistance` and `auditedStreetDistance` are now each cached for 10 minutes. **Note that this means some of the stats on the home page will update every 10 minutes.** The 10 minutes does not get reset (I tested this) when the cached value is accessed.
To test:
1. Try reaching the home page (doesn't matter if you clear cache or not, this is server sided).
2. The loading time difference should be very noticeable.

#1338: Improve website loading times

---

conf/evolutions/default/26.sql

Fixes #433 
This PR adds an evolution file that modifies all the timestamp columns that were added over the past few years (mostly by me) from timestamps without time zones to timestamps _with_ time zones.
To test:
1. Check out the `develop` branch and audit a bit.
1. Take a look at the entries in the `label`, `user_survey_text_submission`, `user_survey_option_submission`, `version`, `user_clustering_session`, `global_clustering_session`, and `mission` tables (don't worry if there are none for any given table). Take a look at their timestamp columns. 
1. Check out the `433-fix-timestamps-in-local-timezone` branch and run it.
1. Check that the timestamp columns in those tables jumped forward 8 hours from PST to UTC
1. Check out the `develop` branch again and run it.
1. Verify that the …

433 fix timestamps in local timezone

---

public/javascripts/SVLabel/css/svl-context-menu.css
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js

Resolves #1276 
I've added keyboard shortcuts for selecting label tags. All you have to do is open a label, and press one of the underlined letters to toggle its corresponding tag. 
Here are some screenshots of the label screens:
To test:
- Ensure that all of the hotkeys toggle the tags as intended
- Ensure that the hotkeys do not interfere with other hotkeys we have (in case I missed something!)
- Ensure that everything else with labels works as before
I have performed these test on Chrome and Firefox on my machine and everything works fine!

Resolves #1276: Adds keyboard shortcuts for selecting label tags

---

public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js

Resolves #1431.
Switched the shortcut for "cracks" to K, and the shortcut for "grass" to R. That way one can see the underline for the grass tag.

Resolves #1431: Switch shortcuts for surface problem tags

---

public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js

Resolves #853 
This improves wording in the tutorial. In particular, it lets users know _why_ they should be rating a certain severity when they get it wrong the first time. The full set of text changes was discussed on the #853 thread.
To test, I need someone to go through the tutorial and carefully read each dialog that comes up. So you will need to rate each severity incorrectly on your first attempt so you end up seeing all of the text. Watch out for typos and such.

853 imporove tutorial wording

---

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js

Resolves #1444 
This adds a null check to ensure that there isn't an error message in the console. I also found and fixed a bug where pressing a shortcut would toggle a tag on the most recent label, even if the context menu was closed.
To test, simply ensure that all of the tagging works as before (minus the bugs ofc).

Resolves #1444: Fix null error from shortcut code and unfound bug

---

app/views/main.scala.html
app/views/validation.scala.html

Resolves #1410
Updates the footer url for the Makeability Lab from "https://makeabilitylab.umiacs.umd.edu/" to "https://makeabilitylab.cs.washington.edu"

#1410 Update audit footer url 

---

public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js

Resolves #1458 
Adds a separate log entry in `audit_tak_interaction` for when a user selects a tag with a keyboard shortcut as opposed to clicking on it. 
To test: ensure that the `audit_task_interaction` table now has `KeyboardShortcut_TagRemoved` and `KeyboardShortcut_TagAdded` logs when appropriate.

Resolves #1458: Add separate logging for keyboard tag changes

---

public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js

resolves #1426 
NoSidewalk was given a context menu by @maubinle in #1482. This PR just adds the relevant sections to the tutorial given the new context menu.
Here is what the tutorial looks like after you place the NoSidewalk label
And here is the tutorial after you rate the severity incorrectly (it should be a 3)
Note that I just took the GIFs from the missing sidewalk label, since all the GIFs are going to be redone very soon by @lstrobel anyway (#1281).
TO TEST:
Go through the tutorial and make sure you see these popups :) Also check that the progress bar increases appropriately as you rate severity (and doesn't go backwards at any point). Note that the progress bar should only increase once when rating severity (so if you get it wrong, then fix it, it should not increase a 2nd time).

1426 no sidewalk context menu in tutorial

---

public/javascripts/SVLabel/src/SVLabel/Tracker.js
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js

Resolves #1490 
ContextMenu_Close is now the only "context menu close event" and only triggers when the context menu is open.
To test:
- Ensure that arrow keys work properly when moving

Resolves #1490: Arrow keys now move properly

---

app/views/navbar.scala.html

Resolves #1409
As described in #1409,
* Fixed the style of the buttons on the audit page navbar
* Added the "Start Validating" button to the audit page navbar
* Removed the "Start Validating" button from the validation page navbar
To test: make sure the buttons show up as intended, and all work

Resolves #1409: Change navbar button styles

---

public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js

Resolves #965
I moved `contextMenu.hide()` calls to after the logging of `ContextMenu_Close...` events.
To test:
- Ensure that temporary label IDs are null when not in context menu

Resolves #965: Temporary label IDs properly null after ContextMenu

---

public/javascripts/SVValidate/src/panorama/Panorama.js

Resolves #1501 
It looks like we're creating a new panorama every time we load a new validation label onto the screen. I think this used to be necessary for avoiding some GSV infinite loop bugs when we changed panorama IDs. I don't think this is necessary anymore since we've changed the way we're loading labels (+ creating a new panorama every time is super slow!).
* Go to the validation interface
* Stress test the system by hitting keyboard shortcuts / clicking the button quickly. Make sure we don't go into an infinite loop! (this happens if you see the panomarker jumping around + a black screen)

Resolves #1501: Improves how labels are loaded on the validation interface

---

app/models/user/VersionTable.scala
app/views/main.scala.html

Resolves #1350 
Adds version information to the footer of the website. Here is what it looks like:
To test, go around to some different pages of the site and make sure the footer has the correctly formatted version information. Specifically make sure to check the audit page, b/c it is handled differently from other pages.

added version info to footer

---

.gitignore
README.md
app/models/user/VersionTable.scala
app/views/main.scala.html

Resolves #1355 
Resolves #1356 
Changes
1. Switched our Google Maps API version from saying 3.3.1 to "quarterly", which is the "stable" version of the API (which is updated quarterly). Version 3.1.1 was already technically deleted and we were being forced into the quarterly version, but since we didn't specify "quarterly" we were getting a warning in the console whenever we used GSV.
1. Switched out the old API key that was linked to @manaswis's account. We are now using a ML lab one.
1. Removed the API key from the actual codebase. It now lives in a file that won't be in our source tree. People will thus have to ask me for the API key so they can add it to their own dev environments. This is important so that randos can't scrape Github to find GMaps API keys and use them.
1. Updated the …

1355 updated gmaps api account

---

app/controllers/AdminController.scala
app/models/user/WebpageActivityTable.scala
app/views/admin/index.scala.html
public/javascripts/Admin/src/Admin.js

Resolves #1418 
2 things were causing the Start Mapping statistic not to display properly:
- Double `encodeURIComponent`. Changing it to 1 fixed it.
- We renamed the 'Start Exploring' activity to 'Start Mapping' and the dashboard was only loading the 'Start Mapping' ones (so old logs got ignored).
We were already logging Turker redirects, just had to add a row to the table.
To test:
- Check that the # of users that click Start Mapping is displayed in analytics
- Check that the # of turker redirects is displayed in analytics

Resolves #1418: "Start Mapping" & turker analytics

---

app/views/labelingGuideCurbRamps.scala.html
app/views/labelingGuideSurfaceProblems.scala.html

Fixes #1421 
Fixes #1451 
Slightly reworded a few sections of the labeling guide to make it clear that curb cuts should be labeled as curb ramps and brick should be marked as a surface problem.
Curb cut before
Curb cut after
Brick before
Brick after
I'm not going to ask anyone to review this PR, b/c it just changes some wording (note that I did verify that I didn't break the direct links to sub-sections).

1451 labeling guide curb cuts as curb ramps

---

public/assets/homepage.js

Resolves #1476
JavaScript objects only allow string keys and I was using an HTMLVideoElement as the key, so the object I used to keep track of which videos were paused only had 1 entry which would be shared for all videos. I changed it to use the video's ID instead.
To test:
- Ensure that videos lazy-play properly on the landing page

Resolves #1476: Fixed lazyplay not resuming videos

---

app/models/amt/AMTAssignmentTable.scala
app/views/audit.scala.html
app/views/navbar.scala.html

Fixes #1537 
This fixes a bug where the front-end timer for turkers was off b/c of time zone differences from UTC. Instead of sending a timestamp of when the HIT ends to the front-end, we now compute how many milliseconds are left before the HIT has expired on the back-end and send that number.
Testing instructions:
1. Check out the develop branch and go to localhost:9000/?referrer=mturk&hitId=h1&workerId=worker1&assignmentId=a1&minutes=5 -- you should be redirected to the audit page and the timer should show something like 8 hours and 5 minutes.
1. Check out the 1537 branch and go to localhost:9000/?referrer=mturk&hitId=h2&workerId=worker2&assignmentId=a2&minutes=5 -- you should be redirected to the audit page and the timer should show 5 minutes remaining.
I'm not going to ask anyone to …

fixed front-end timer for turker HITs

---

app/controllers/AdminController.scala
public/javascripts/Admin/src/Admin.js

Resolves #1418
See https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1508 for the original PR.
This one has a workaround for routing inconsistencies between local & test/production, specifically to do with trailing slashes.
To test:
- Check that the # of users that click Start Mapping is displayed in analytics
- Check that the # of turker redirects is displayed in analytics

Resolves #1418 again!!: Turker/mapping analytics, workaround routing inconsistencies

---

app/views/admin/user.scala.html

Fixes #1423 
Fixes the illegalformatconversion error on the admin user page `/admin/user/<username>` that prevented the page from loading. This was caused by the 0-distance missions (e.g., the tutorial or validation missions). The error was with a line of the form `mission.distanceMeters.getOrElse(0)`, which should have been `mission.distanceMeters.getOrElse(0F)` (we were passing in an Int instead of a Float).
Testing instructions: Load the `/admin/user/misaugstad` endpoint and make sure that it actually loads and the table with the list of missions looks okay.
I won't ask anyone to test b/c this was a really simple fix.

1423 admin user page illegalformatconversion error

---

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js

Resolves #1535 
Switches the keyboard shortcut for the "street has a sidewalk" tag from 't' to 'r' and the shortcut for the "street has no sidewalks" tag from 'r' to 't'.
This was just done so the physical location on the screen matches the physical location of the keys on the keyboard.
Not asking anyone to test b/c it is a simple change.

1535 switch shortcuts for nosidewalk tags

---

app/controllers/AuditController.scala
app/models/region/RegionTable.scala

Resolves #1569 
The /audit/street endpoints used to use a postgis `ST_Intersects` query to determine which neighborhood the street is in. But that is what the `street_edge_region` table is for :) This was causing some issues, so I removed the old query and switched to using the `street_edge_region` table like we are supposed to be doing.
To test: Make sure that the /audit/street endpoint works as expected. One street that didn't work with the old query was street edge 168 in the Newberg dataset. So you could test that street edge on develop and on this branch to make sure the issue is fixed.
I won't ask anyone to test because this is a simple fix.

1569 use street edge region table for audit street endpoint

---

app/views/audit.scala.html

Partially resolves #1570 
This improves the logging when there is no GSV imagery. We now report which street edge the user is trying to audit when we find no imagery. This is now being logged in the console and in the `audit_task_interaction` table.
Not asking for a tester b/c this PR just adds two logging statements.

improved logging when there is no GSV imagery

---

public/javascripts/SVValidate/src/panorama/Panorama.js

Resolves #1561, #1543 
The reason that we've been getting this bug is because when we get the panorama POV (from `Label.js`, sometimes the data is outdated (we get the POV from the previous panorama that's loaded). 
```
var userPov = svv.panorama.getPov();
```
This sometimes caused our calculation that calculates the pixel coordinates of the Panomarker to fail one of its sanity checks and return `null` coordinates. 
I think the reason why we were getting outdated data was because I previously added a callback to set new panoramas. If you hit the validation button fast enough, that would somehow mess with the callback and cause us to get outdated information. When I originally built the validation interface, there was a GSV bug that caused me to go into an infinite loop when I directly …

Resolves #1561, 1543: cannot read property null from ‘left’

---

app/views/audit.scala.html
public/javascripts/SVLabel/css/svl-modal.css
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionCompleteMap.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionCompleteProgressBar.js
public/javascripts/SVLabel/src/SVLabel/neighborhood/Neighborhood.js
public/javascripts/SVLabel/src/SVLabel/task/Task.js
public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js

Resolves #846 
Changes
* The mission complete modal now shows neighborhood progress across all users. We differentiate b/w audits by other users, past audits by the current user, and the current user's most recent mission (see before/after images below).
* Neighborhood complete popup now shows up when all streets in the neighborhood have a priority less than 1 instead of when all the streets have been audited by anyone. The difference is that we aren't counting audits of "low quality" users when deciding when to say we've completed the neighborhood.
Before:
After:
Given time constraints on others, I won't ask anyone to review the PR. But it is a significant enough change that we will make sure to test out completing missions thoroughly on the test servers before merging into master.

846 mission complete progress across all users

---

app/models/user/VersionTable.scala
app/views/main.scala.html
conf/cityparams.conf

Resolves #1576 
Splits the Google Analytics b/w cities. Creates separate Google Analytics accounts for Newberg and Seattle. I've given @jonfroehlich full access to these accounts, did you get the confirmation emails @jonfroehlich?
Simple fix, so I won't ask anyone to test.

1576 split google analytics by city

---

Dockerfile
requirements.txt

resolves #1515 
Upgrades the Python requests library to 2.20.0 due to a security vulnerability in previous versions.
Not asking anyone to test because it is a simple change. However I will wait to merge until I ask @mechanicjay to remove the old libraries from the Docker images.

upgraded Python requests library to 2.20.0

---

app/views/audit.scala.html
check_streets_for_imagery.py

Resolves #1570 
Adds a script that will look through a CSV containing the endpoints for the street edges, check the GSV API for imagery at the endpoints, and output a CSV of streets that do not have imagery at both endpoints. It shows percentage progress in the terminal as it runs :blush: 
This script should be run when creating a database for a city. You should mark all the streets in the output CSV as "deleted" in the `street_edge` table.
I also removed the page refresh when no street view imagery is found (which shouldn't happen anymore). But when it was happening, an infinite refresh wasn't a great way to deal with it. Instead I am just logging which `street_edge_id` is causing the problem in the console so we can look at that.
Testing:
1. Create CSV from street_edge table with …

1570 deal with missing gsv imagery

---

Dockerfile

Fixes #1599 
This resolves the issue when running ```make dev``` setting up a dev environment. I believe the problem stemmed from changes to Jessie on the mirror network. Jessie’s apt no longer supports the check-valid-until flag. So ```apt-get upgrade -y``` needs to change to ```apt-get -o Acquire::Check-Valid-Until=false upgrade -y```.

1599 dev environment failed fetch jessie update

---

app/controllers/ConfigController.scala
conf/cityparams.conf
public/javascripts/AccessibilityChoropleth.js
public/javascripts/Admin/src/Admin.User.js
public/javascripts/Admin/src/Admin.js
public/javascripts/Choropleth.js
public/javascripts/Progress/src/Progress.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionCompleteMap.js
public/javascripts/accessScoreDemo.js
public/javascripts/developer.js
public/javascripts/mapEdit.js

Fixes #1602 
Sets the default zoom for maps of Seattle to be 0.5 zoom levels further zoomed out so that we can see all of Seattle on the maps by default. Here is a before/after:
Very simple fix so not asking anyone to test.

1602 zoom out seattle

---

app/models/mission/MissionTable.scala
public/javascripts/SVLabel/src/SVLabel/modal/ModalMission.js
public/javascripts/SVLabel/src/SVLabel/status/StatusFieldMission.js

Resolves #1595 
Shortens mission lengths from 500 ft, 500 ft, 1000 ft, 1000 ft, the rest 1/4 mile to 500 ft, 500 ft, 750 ft, the rest 1000 ft.
Very simple change so not asking anyone to review/test.

1595 shorten mission lengths

---

app/models/attribute/GlobalAttributeTable.scala
app/views/developer.scala.html

Resolves #1605 
Adds parameters to the /v2/access/attributesWithLabels endpoint that are needed to recreate the scene in Google Street View. The /api page documentation is updated accordingly.
Very simple change so I'm not asking anyone to review.

1605 add gsv params to api

---

app/models/audit/AuditTaskTable.scala

Fixes #1613 
Instead of running a query that sorts the streets by priority and taking the first street that is returned, we now take one street randomly from the list of streets with the highest priority in the region.
Super easy change so I'm not asking anyone to test.

1613 randomize first street in neighborhood

---

app/views/index.scala.html

Fixes #1614 
Deals with the weird wording of "that's nearly 0% of the city!" by removing the word "nearly" and adding a decimal to the percentage. We also added a decimal to the number of miles audited.
Before
After
Trivial change so not asking anyone to test.

added decimal to percentage of city complete on landing page

---

app/views/navbar.scala.html
public/css/main.css

fixes #1506 
I was quickly able to vertically align the logo by removing unnecessary classes and editing the margin of the surrounding div. 
While this fix works, I would say there is a better way to do it using flex. This would take more time but I feel like would work better in the long run. 
Let me know if you would like me to re-design the navbar's css using flex.
Before: 
After:

Fixes menubar components not being vertically aligned

---

app/controllers/ValidationController.scala
app/controllers/ValidationTaskController.scala
app/models/label/LabelValidationTable.scala
app/views/validation.scala.html
public/javascripts/SVValidate/css/svv-left-column.css
public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/data/Form.js
public/javascripts/SVValidate/src/mission/Mission.js
public/javascripts/SVValidate/src/mission/MissionContainer.js
public/javascripts/SVValidate/src/modal/ModalMission.js
public/javascripts/SVValidate/src/modal/ModalMissionComplete.js
public/javascripts/SVValidate/src/status/StatusExample.js

(Partially?) Resolves #1584.
**Changes**
* Changed the "You validated 10 labels" text on mission complete screen to be the number of labels the user validated in their current session (rather than the number of labels in the mission)
* Added a resume mission screen to hopefully clear up some confusion about receiving validation missions that were partially complete
* Do some validation missions. Refresh the page part-way through some of these missions.
* When you complete a mission, check that the complete mission screen shows the accurate label counts (both in the description below the title and in the table)
* When you are getting a new mission (either on page load, or after you click "Validate more labels", check that the appropriate new mission/resume mission …

(Partially?) Resolves #1584: Fix problem with prematurely ending missions

---

app/controllers/ApplicationController.scala
app/views/index.scala.html
conf/cityparams.conf
public/css/main.css

Partially resolves #1304 
Adds links to the audit pages for other cities to the landing page.
Before
After
Pretty easy change, so I won't ask anyone to test. Unless you specifically want to take a look @manaswis to make sure this meets your expectations.

1304 newcity landing page

---

public/javascripts/SVValidate/src/data/Form.js
public/javascripts/SVValidate/src/keyboard/Keyboard.js
public/javascripts/SVValidate/src/modal/ModalMission.js
public/javascripts/SVValidate/src/modal/ModalMissionComplete.js
public/javascripts/SVValidate/src/modal/ModalNoNewMission.js

Resolves #1627.
When the mission complete / resume mission screens are being shown, we don't allow the users to use keyboard shortcuts. Previously, if you clicked the "A" key (or any other validation keyboard shortcut), you'd still be able to validate labels even while these screens were still visible. 
I also snuck in a brief fix for some changes from #1610. In some cases, I found that I was still able to close the "mission complete" screen before the next label was loaded because of some asynchronous weirdness. 
* Complete a validation mission. On each screen, use keyboard shortcuts. The label count (that is still visible above the mission screen) shouldn't change.
* Check the `validation_task_interaction` table to make sure that the keyboard shortcuts aren't …

Resolves #1627: Disable keyboard shortcuts when mission screens are shown

---

public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js
public/javascripts/SVValidate/src/data/Form.js

Resolves #1643.
We were using an asynchronous post request to submit our data to the backend when redirecting users to the audit page. This was causing some problems because we would load the audit page for the next mission before we had a chance to mark the mission as complete in our database. This caused some problems because we don't allow users to start a new distance mission while an onboarding mission is in progress.
I added a new function for submitting data that sets `async = true` in our post request when we complete/skip the onboarding mission. This way, we make sure that all our data is being logged appropriately. 
1. Visit `http://0.0.0.0:9000/audit?retakeTutorial=true`
2. Select Skip Mission. You should be redirected to a new distance mission.
3. …

Resolves #1643: Can't get past the tutorial

---

public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVValidate/src/data/Form.js

Related to #1643, #1645. (Doesn't resolve anything, hah).
I added some code that tried to use beacons to submit code to the backend before unload that doesn't seem to be working. I decided to add back the code from what we were doing previously (synchronous ajax call) -- even though this doesn't work on the newest version of chrome. But perhaps it works on other browsers or older versions of Chrome, so having something that partially works is probably better than nothing 😬.
(Note: on the newest version of Chrome, this means that we lose the data from between the "last time" the form was submitted -- which happens when there are over 200 interactions logged (including LowLevel events like mousemove, keyboard presses) or when a user completes a mission.

Add in old code for submitting data

---

public/javascripts/SVLabel/src/SVLabel/Panomarker.js

Resolves #1644.
Fixes issue where the Panomarker moves around in the validation in Safari and Firefox.
* Open up the validation interface in Safari/Firefox/Chrome. Pan around the interface and check that the label is properly sticking.
* I don't have Firefox installed so I have only tested on Safari/Chrome.

Resolves #1644: Fixes Panomarker stickiness in Safari and Firefox

---

public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVValidate/src/data/Form.js

Bandage for #1648 
This PR switches to using _asynchronous_ ajax requests in _only Chrome_ when the page is closed/refreshed. Data is not guaranteed to be sent, but it is now at least sent _sometimes_ when the page refreshes instead of never. Firefox/Safari should continue to always send the data successfully.
This is a bandage until `application/json` support is restored for `navigator.sendBeacon` or until we find an alternative.
Testing:
1. Check out the develop  and go to the validate page in Chrome. Try agreeing with a single label and immediately refreshing the page. Notice how the mission completion percentage never increases.
1. Do the same thing on the audit page by taking a step and refreshing. Notice how the percentage also does not increase.
1. Try both of the above in Firefox …

Chrome now makes async requests on page close

---

app/views/audit.scala.html
app/views/auditCreateCVMissionForm.scala.html
public/css/main.css
public/javascripts/SVLabel/src/SVLabel/mission/CVGroundTruthMission.js

A very minor PR to show the current PanoID in the CV Ground Truth Audit tool. Also tweaked panoId input form to mention required format.
Before:
After:
Testing:
* Verified the panoId shown matches result of `svl.panorama.getPano()` in console.

Add current panoid display to CV ground truth tool to resolve #1660

---

app/models/mission/MissionTable.scala
app/views/audit.scala.html
app/views/validation.scala.html
public/javascripts/SVValidate/src/modal/ModalMissionComplete.js

Fixes #1670 
The confirmation code no longer shows up for turkers when they complete a validation mission. They now have to complete an audit mission for the confirmation code to show up. However, the code does still show on the validation page if they happen to go there and they've already completed an audit mission :)
Pretty simple PR that is time-sensitive, so I'm not asking anyone to review.

disabled confirmation code appearing on validation interface

---

app/models/mission/MissionTable.scala
app/views/audit.scala.html
app/views/validation.scala.html

Fixes #1675 
On the HIT expiration overlay, we now only include the confirmation code if the turker actually finished the tutorial and first mission.
Very quick/easy fix and time-sensitive, so not asking anyone to review.

confirmation code now only shows if you finish HIT

---

app/views/admin/index.scala.html

Resolves #1683 
The admin page contribution tab will now show the most recent 5000 labels instead of most recent 1000 labels, which should make it easier for me to batch when I review turker work.
Super simple PR, and we won't know if it works until I put it on Seattle production server. But the worst it can do is make the admin page unresponsive, and will be easy to revert :)

now showing last 5000 labels on admin page

---

app/formats/json/ValidationTaskSubmissionFormats.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala
conf/evolutions/default/44.sql
public/javascripts/SVValidate/src/label/Label.js

Fixes #1543 
The `canvas_x` and `canvas_y` columns in the `label_validation` table are meant to capture the location on the canvas that the label is when validation occurs. This doesn't really make sense when the user has panned away so that the label is no longer in view. This was causing a bug when the `povToPixel3d` returned `null`, b/c that was what the `povToPixel3d` function was meant to calculate.
I've made it so that `canvas_x` and `canvas_y` are nullable, and I set them to null only when the label is not at all visible on the screen.
@aileenzeng I was hoping you could just sanity check the code? You can test if you have time, but it will be easy enough for anyone to test once it is on the test servers.

makes canvas_x/y nullable to fix panning validation bug

---

app/views/validation.scala.html
public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/modal/ModalMissionComplete.js

Resolves #1693 
Comments out all turker-related code on the /validate page. I tested to make sure it works for both turkers and non-turkers. I left all the code intact though, with comments that include "#1693" at each location so that it will be easy to uncomment when we want to start using validation for turkers.
Pretty simple change so not asking anyone to test.

comments out turker stuff on validate page

---

public/javascripts/Admin/src/Admin.User.js
public/javascripts/Progress/src/Progress.js

This is a bandage for #1611 
On the #1611 thread @htadeusiak fully describes our current situation, where we need to upgrade our Leaflet version on the user dashboard and audit pages, but that causes other problems. The early version of Leaflet we are using on those pages does not work with the fractional zoom we are using in Seattle. So the temp fix I am doing is to just take the floor of the zoom level we are given on the user dashboard.
The Seattle deployment is in full swing, so I want users to be able to see their dashboard while we work on figuring out a legitimate fix for this issue.

1611 temp fix for user dashboard not working

---

public/javascripts/SVValidate/src/modal/ModalMissionComplete.js

Fixes #1528 
Fixes an issue where the old mission would load on the validation interface if you clicked the continue button too early. Just needed to change the line `closeButton.on('click', null);` to `closeButton.off('click');`, which is how it is done on the audit page.

fixes previous mission loading after 2nd validation mission

---

.gitattributes

Fixes #1527 
FIxes an issue in setting up our Docker dev environment where our shell scripts had CRLF line endings which caused them to fail with a cryptic error. This is fixed by adding a .gitattributes file to set the default line endings for shell scripts. I used [this tutorial](https://help.github.com/en/articles/dealing-with-line-endings#per-repository-settings) to create our .gitattributes file.

adds .gitattributes file to fix line endings

---

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js

Resolves #1596 
Adds 'g' back in as a keyboard shortcut for the 'grass' surface problem tag. Both 'g' and 'r' are now options.

g and r are now both shortcuts for grass tag

---

app/models/audit/AuditTaskTable.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala

Fixes #1590 
Removes the hardcoded dates for the graphs on the admin page. They now start whenever we begin having data. Note that the data looks a bit sparse in the graphs below b/c it is the data used in my dev environment, not the last few months of production data.
Before:
After:
Really easy change, so not asking anyone to test before putting it on test servers.

1590 no hardcoded dates admin page

---

public/javascripts/SVValidate/src/status/StatusPopupDescriptions.js

#1586 
Changes the description from 
"Surface problems on curb ramps should not be labeled as surface problems"
to
"Surface problems on curb ramps should be marked with a curb ramp label with a higher severity".
Before:
After:

Validation - Slight change to surface problem example description 

---

app/controllers/ValidationController.scala
app/controllers/ValidationTaskController.scala
app/models/label/LabelTable.scala

Fixes #1712 
Speeds up loading new missions for validation page by a few seconds.
There are two main updates I made to this.
1. Instead of querying our database 10 times (once per new label), we query the database just once. In order to do this, I had to switch from our nice compiled Slick queries to a static SQL query because (our version) of Slick doesn't have the feature where we select N labels randomly. This seems to be saving about 3.5 seconds.
1. As suggested by @aileenzeng we are now calling the GSV API for the 10 labels in parallel. This seems to be saving about 1.25 seconds. Turns out that this is ridiculously easy in Scala. So I'll keep an eye out in the future for where I can use this :)
All in all we are saving about 4.75 seconds whenever loading a new mission (and I assume …

1712 speed up validation page

---

public/javascripts/SVValidate/src/mission/Mission.js
public/javascripts/SVValidate/src/mission/MissionContainer.js
public/javascripts/SVValidate/src/panorama/PanoramaContainer.js

Fixes #1735 
When a user clicked skip in the validation interface, the next image would require two button clicks to get past. This PR address that issue. The problem was there are two "progress" variables that keep track of where we are in the "labels" array. These trackers were set incorrectly when the user clicked skip.
Before:
After:

1735 - Validation fixes two button presses after skip button clicked bug

---

README.md
app/views/labelingGuideObstacles.scala.html
app/views/labelingGuideSurfaceProblems.scala.html

Resolves #1703 
Resolves #1690 
Resolves #1637 
Improves documentation in the README for setting up and troubleshooting problems with the dev environment. Also clarifies/elaborates on a few things in the labeling guide, namely how frequently to place Surface Problem labels and whether to place Obstacle labels on crosswalks.
These are all just changes to text, so no need for a review.

1703 improve docker documentation

---

app/models/label/LabelTable.scala

Resolves #1739 
Users will now only validate labels that no one has validated before. If all labels have been validated, then we prioritize validating labels that have been validated only once, etc.
This was a pretty simple change to the validation code. But when we make validation prioritization any more complicated, we should do something like we do for prioritizing street edges (something like the `street_edge_priority` table).

now prioritizing labels with no validations

---

public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js

Fixes #1545 
I only made changes to the min/max head angles. It should now prevent most context menu's from covering tutorial instructions. I'm not sure exactly what you had in mind with adjusting the head angles, so I made the tutorial slightly more 'constricting' as far as user movements. 
I do know in two places where the instructions do get covered:
- In stage 2 you can cover the instructions with the missing curb context menu. There is not a way to prevent this from happening unless we added another stage.
- In stage 3 you can cover the instructions with the curb context menu if your pov is pointed up higher. Once again we would need to add another stage or have the user point the pov more to the ground to fully prevent this. 
However, for both these cases I do not view the context …

Tutorial - context menu can block tutorial instructions

---

public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/keyboard/Keyboard.js
public/javascripts/SVValidate/src/modal/ModalMission.js

Fixes #1750 
Added code to check if either the comment box or sign-in modal is shown and disable keyboard shortcuts accordingly.
For testing: check if the keyboard shortcuts still go off when typing to the sign-in box or comment box.

1750 - Fix keyboard shortcuts firing off

---

public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/modal/ModalNoNewMission.js

Fixes #1656 
Added small changes to fix out of labels validation screen broken issue.
Before:
After:

1656 - Out of labels validation screen broken

---

public/javascripts/SVLabel/css/svl-context-menu.css

The `pointer-events: none` line was added to the style of the `tag-underline`; this prevents overlay of the `tag-underline` over the button. Now, clicking on the underlined character works in a tag works.

Resolves #1547: pressing on underlined character in tags now works

---

app/forms/SignUpForm.scala
app/views/navbar.scala.html

Fixes #1546 
Add a 'Confirm password' input box. Only allow signing up if the passwords match. Also, restrict passwords to be at least 6 characters.
After pictures:

1546 - Require users to type in their password twice when signing up

---

public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionProgress.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/mission/MissionContainer.js
public/javascripts/SVValidate/src/modal/ModalMissionComplete.js

Partially resolves #1372 
We are not sure exactly how we want to integrate validation missions into the audit workflow. This is a temporary change that we will adapt going forward. What this PR does is make is so that after 2 audit missions, you are send to the validation page, and after you finish 3 validation missions, you are sent back to the audit page. If you at any point reload the audit or validation pages, that count will start over right now.
I just want to start by testing this out to see how it feels. Planning to make a more robust PR later on once we figure out what we really want.

1372 temp integrating validation missions

---

app/views/developer.scala.html
public/css/main.css

Resolves #800 
Clicking in-page anchor links on the Developer page now scrolls the screen to the right place, keeping the navigation bar on top from blocking the content.

#800: Bug with nav bar calibration

---

README.md

Resolves #1751 
This is just an update to the README.md to make the onboarding process more smooth.
1. Adds info on IDE and database access
1. Adds links to the [style guide](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Style-Guide) and [process for contributing new code](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Process-for-contributing-new-code) wiki pages
1. moves the link to [docker troubleshooting](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Docker-Troubleshooting) wiki page to the top

1751 more dev env info to readme

---

public/javascripts/SVLabel/src/SVLabel/status/LabelCounter.js

Resolves #1051
Helps a bit with keeping label images from going off-screen when they reach too high a number.
Before: (goes off-screen at 189 labels; circles of size 50, 10, and 1)
After: (goes off-screen at 249 labels; circles of size 100, 50, 10, and 1)

#1051: Adds a circle size that represents 100 labels

---

app/models/label/LabelTable.scala

As discussed in [this comment](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1727#issuecomment-510164568) on #1727, we want to prioritize doing validations of labels provided by users who have less than 10 labels validated for that label type. We want users to have a minimum of 10 labels per label type validated in order to include them in this analysis, and we were having trouble getting enough users who meet this threshold.
Choosing which labels to validate is done in one big query right now. So I added a subquery that calculates whether or not a user has 10 or more labels of the given label type validated. Then instead of ordering totally randomly, I take from users with less than 10 labels validated first, and randomly from within that group. If there are no labels left to …

1727 prioritize validations users with few validations

---

public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionCompleteProgressBar.js

Resolves #244
Fixes mission complete progress bar 1 pixel for 'previous mission' even though none has been completed. The screen should not be drawing either blue or black bar when there is no previous mission or other users' completed.
To test, run on local host and on the web page, select a neighborhood that shows 0% complete. Once a mission is complete in that neighborhood, look at the pop-up mission complete progress pixel bar, there should be only the blue bar drawn, and no other color.
Before:
After:

#244: <mission-complete-bar-pixel> 

---

public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js

Resolves #1773
Fixes mission complete progress bar displaying a negative -0.01 distance when it should be displayed as 0.0
Fixes the bug by adding a Math.max, to ensure the value is always greater than or equal to 0.0.
To test, run on local host and on the web page, select a neighborhood that shows 0% complete. Once a mission is complete in that neighborhood, look at the pop-up mission complete progress pixel bar, the "othera audited in this neighborhood" option should display 0.0 miles. However, the bug only shows up sometimes; other times it displays 0.0 miles correctly.
Before:
After:

#1773: <fix negative distance in mission complete bar>

---

docker-compose.yml

Resolves #1517 
The issue occurs when we run make dev for the first time when setting up a new dev environment. Basically, the node_modules folder that contains all dependencies was not created properly after 'npm install' was run in Dockerfile.
I made a small change in docker-compose.yml to create a data volume for node_modules, as these data volumes are properly mounted.
For testing: Remove node_modules folder from inside docker container. Stop and delete all projectsidewalk's containers, volumes. Rerun make dev to make sure node_modules is created with all dependencies installed.

1517 grunt not found when setting up dev environment

---

app/controllers/TaskController.scala
app/controllers/ValidationController.scala
app/controllers/ValidationTaskController.scala
app/models/audit/AuditTaskInteractionTable.scala
app/models/label/LabelTable.scala
app/models/validation/ValidationTaskInteractionTable.scala

Resolves #1799 
Drastically improves validation mission load times. It brings the load times on my local dev environment from 4-5 seconds to 1.5-2.5 seconds (a 2.5 second improvement!). I did this by making a few improvements:
1. There was a separate query being done for each label type to check if a user had enough labels left to validate of that label type. I turned this into a single query that includes a group by. This improved load time by about 0.5 seconds.
1. When figuring out how many labels a user had remaining to validate, we were running a separate query to get all the labels that user had already validated, and turning that into a Scala object. We were then filtering those labels out. It is much more performant for large lists of labels to instead do a left join and filter …

1799 improve validation mission load time

---

public/javascripts/SVValidate/src/modal/ModalMission.js

Resolves #1813 
The mission start text for a label type now shows the text for the label type of the current mission. Minor changes were made in ModalMission.js to fix this. The Html string has a ‘COUNT’ and ‘LABELTYPE’ variables that are to be replaced at the beginning of each mission. In the old code, the very first mission used this original string to display the text on the mission modal instead of a copy. This was the cause of this bug.
Testing: Check to see if the bug can be reproduced.
After: https://youtu.be/k5LJK7bZJhU

1813 wrong label type in mission text

---

app/controllers/AdminController.scala
app/models/daos/UserDAOImpl.scala
app/models/label/LabelValidationTable.scala
app/models/street/StreetEdgeTable.scala

Fixes #1822 
Fixes the validation count on the admin page user table. This also modifies it so that the count of labels validated is a count of *distinct* labels.

1822 admin fix label validation count

---

app/controllers/ValidationController.scala
app/controllers/ValidationTaskController.scala

Fixes #1862 
This should fix the issue where we were getting validation missions for no sidewalk labels. The issue was that we were relying on a list to be sorted that was not necessarily sorted.

no sidewalk labels deprioritized on validation again

---

public/javascripts/SVValidate/src/panorama/Panorama.js

Resolves #1813 
On develop branch's validation page, the title doesn't get updated for new missions. This was fixed by adding code to update this title when new labels are set.
Bug Screenshot:

1813 validation wrong title text

---

app/controllers/ValidationTaskController.scala
conf/cityparams.conf

Fixes #1837 
The link to the DC server on the landing page is now sidewalk-dc.cs.washington.edu instead sidewalk.cs.washington.edu. So it correctly links to DC and not to Seattle now!

1837 landing pagefix dc link

---

app/views/validation.scala.html
public/javascripts/SVLabel/src/SVLabel/Panomarker.js
public/javascripts/SVValidate/css/svv-panorama-single.css
public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/panorama/GSVOverlay.js
public/javascripts/SVValidate/src/panorama/Panorama.js

Resolves #1734 
Fixes #1662 
This bug happens when a user tries to validate labels using keyboard shortcuts while panning. I was able to reproduce the bugs multiple times:
Screen Recording: https://youtu.be/KI3UzXwEops
This was fixed by making sure that a user can only pan after the panorama is fully loaded. Doing so requires adding a layer on top of the GSV window that handles panning.
Users are now also not able to walk using arrow keys.
Testing: Test to see if this bug still happens (using keyboard shortcuts while panning), make sure nothing breaks during panning.

1734 validation blank screen on validation

---

app/models/label/LabelTable.scala

Resolves #1854 
We recently had a bug that occurred when every label of a certain type had been validated. I wanted to make sure that I also fixed this for when a single user validated all the labels of a certain label type.
Through my investigation I found that the logic looks sound (I actually fixed it during that other PR where I fixed the issue mentioned above).
One thing I did do in this PR is to add a buffer to how many labels need to be available for us to assign a validation mission for that label type. I foresaw a problem if there were only 10 obstacle labels left to validate, but then one of them didn't have imagery, this likely would have thrown us into an infinite loops on the back-end again (though honestly it would have been very very unlikely). We now require that a there …

adds buffer room when deciding if a user can validate a label type

---

app/views/navbar.scala.html

Resolves #1298
Before, when the user signs in in the audit page, the tutorial will not be skipped.
Now, when the user signs in, the page will reload and the user will directly be taken to the actual audit interface. 
It works the same for the validation page as well.

1298 Refresh the page when the sign in post request is done.

---

app/controllers/AuditController.scala
app/models/mission/MissionTable.scala
app/views/audit.scala.html
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
public/javascripts/SVValidate/src/modal/ModalMissionComplete.js

This is a small test of something suggested in #1372 
We are toying with the audit/validation mission flow so that it feels less jarring for returning users. Being taken out of an auditing after only 1 or 2 audit missions seems to quick for returning users, but new users should have a chance to try validating right away.
To this end, this PR sets things up so that a new user will do one audit mission, then be sent to validations for 3 missions. If a user has already completed an audit mission, they will get 3 audit missions in a row before being sent to validation for 3 missions.
This setup probably isn't going to be our end goal, but we want to try out some slight modifications before completely overhauling and giving users more choice.

1372 validation change number of audit missions

---

app/views/results.scala.html
public/javascripts/AccessibilityChoropleth.js
public/stylesheets/choropleth.css

Resolves #898. Adds a reset zoom button to the results choropleth. The button restores the original zoom value of the map when it is clicked. The changes add the physical button to the map in results.scala.html, add the button styling in choropleth.css, and add the button's functionality in AccessibilityChoropleth.js. 
Before:
After 
For testing if button works well, check if 
- button works on all results choropleths (for Washington DC, Seattle, and Newberg)
- button appears on different browsers and screen sizes

898 results choropleth add reset zoom

---

public/javascripts/SVValidate/src/panorama/PanoramaContainer.js

Fixes #1869 
On the validation interface, when a new mission is loaded, the progress field (label index) does not get updated properly. This PR has code that makes sure this field get incremented correctly.
Bug: 
No bug:

1869 validation first two labels are the same

---

public/javascripts/SVValidate/css/svv-modal.css
public/javascripts/SVValidate/src/panorama/PanoramaContainer.js

Fixes #1871 
A function was incorrectly called when the skip label button is clicked.
The comment box sits underneath the newly introduced GSV overlay.
This PR has code that fixes the issues above.
After: https://youtu.be/g_pTexUZVPM

1871 validation skip and feedback button not working

---

public/javascripts/SVValidate/src/modal/ModalMissionComplete.js

Fixes #1800 
After finishing your third validation mission, the continue button now reads "Start an exploration mission" instead of "Validate more labels" before you are sent to the audit page. This remains "Validate more labels" on mobile, because we don't have a mobile audit interface right now.

continue button now changes text for which mission is next

---

app/controllers/ValidationController.scala
app/controllers/ValidationTaskController.scala
app/models/label/LabelTable.scala
conf/routes
public/javascripts/SVValidate/src/panorama/Panorama.js
public/javascripts/SVValidate/src/panorama/PanoramaContainer.js

Fixes #1874 
Resolves #1823 
This fixes the bug where you would click the skip button and the exact same label would just show up again (#1874). It also makes it less likely that you will see a bunch of labels from the same labeling mission in a validation mission (#1823).

1874 validation fix repeating labels

---

app/controllers/helper/AttributeControllerHelper.scala
app/models/user/UserStatTable.scala

fixes #1892 
Drastically improves the runtime of nightly clustering. We were "running clustering" on all users, even if they had never placed a label. And this involves a call to a Python script that would take about 1/4 of a second. Given that there are 10s of thousands of accounts (from anyone who simply visits our landing page), this caused the clustering to be taking 1-2 hours. It should now take more like 20-30 minutes.
I also noticed that tutorial labels were being included in the label count for users when deciding if they are a "high quality" user. I've fixed that bug as well.

1892 performance improve clustering speed

---

app/controllers/ApplicationController.scala
app/controllers/AuditController.scala
app/controllers/SignUpController.scala
app/controllers/ValidationController.scala
app/models/amt/AMTAssignmentTable.scala
app/models/mission/MissionTable.scala
app/views/audit.scala.html
app/views/mobileValidate.scala.html
app/views/rapidValidation.scala.html
app/views/validation.scala.html
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
public/javascripts/SVValidate/src/Main.js

Resolves #1915 
Turkers will now be required to go from 3 audit missions to 3 validation missions, and vice versa. And they should not be able to get around it by clicking the "start validating" or "start exploring" like other users can right now. Nothing should be changed for normal users.
This also adds a payment amount of $0.12 per validation mission that is shown on the validation page.
This also prevents turkers from visiting the /rapidValidate or /mobile endpoints.

Forces turkers into specific mission flow

---

app/models/daos/UserDAOImpl.scala
app/models/mission/MissionTable.scala
app/views/admin/index.scala.html

Resolves #1906 
Adds validation user stats to the overview tab on the admin page.
Before
After

1906 add validation user overview stats

---

app/controllers/TaskController.scala
app/controllers/ValidationTaskController.scala
public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVValidate/src/data/Form.js

Resolves #1915 
This modifies how we force turkers between the audit and validation pages. We now rely more on the back-end to decide that it is time to switch between the two. This should prevent any errors we may have been making on the front-end, and prevent users from being able to just modify JavaScript variables to continue doing the types of missions they want.

Changes how turkers are forced b/w audits and validations

---

app/controllers/AdminController.scala
app/controllers/ApplicationController.scala
app/models/label/LabelTable.scala
app/views/labelMap.scala.html
conf/routes
public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/Admin/src/Admin.LabelSearch.js
public/javascripts/Admin/src/Admin.Panorama.js
public/javascripts/Admin/src/Admin.js
public/javascripts/LabelMap.js

Partially resolves #1166 
Resolves #1782 
Adds the MVP for a new /labelmap endpoint that will allow users to take a look at all the labels in their city. It is the same as the map on our admin page. Users can click on an individual label on the map and it will pop up a window showing it on a pano.
I also added an error message when the given pano has been deleted so we can't get it from Google. This also now happens on the admin page (which resolves #1782).
Things we are currently missing include
1. The ability to minimize the legend
1. A checkbox so that you can view only labels that have been positively validated
1. The ability to validate directly from this interface.

LabelMap MVP

---

app/models/label/LabelTable.scala
public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/Admin/src/Admin.Panorama.js

Resolves #1928 
Resolves #1929 
Adds image date to the table below the pano on the /labelmap endpoint and on the admin page.
Also prevents walking by clicking on /labelmap (we left that functionality on the admin page). You can still navigate this way on the admin page. You can also still navigate if you use the arrow keys, but the fix for that was more complex than is worth expending on this.
Before
After

1928 labelmap add date to pano

---

public/javascripts/Admin/src/Admin.Panorama.js

fixes #1935 
**Before**: we would query Google, wait 500ms, then show the pano if we had it, and showed a no imagery error message if we didn't have it (whether this was b/c we hadn't received a response yet OR if we received a response saying there was no imagery).
**After**: we query Google, then every 100ms we check if we've got a response. If it is a good response we show the pano. If it says there is no imagery, we show the no imagery error message. If we wait a full 2 seconds without getting a response from Google, we show a message saying we had trouble connecting with Google and they should try again later.
This will improve performance on good connections, where the pano (or no imagery error message) will now show after only 200-300ms instead of the 500ms we were waiting every …

fixes bug where labelmap said there was no imagery

---

app/controllers/AdminController.scala
app/controllers/ValidationTaskController.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala
conf/evolutions/default/68.sql
conf/routes
public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/Admin/src/Admin.LabelSearch.js
public/javascripts/Admin/src/Admin.Panorama.js
public/javascripts/Admin/src/Admin.js
public/javascripts/LabelMap.js

Resolves #1930 
Adds validation support to the /labelmap endpoint. This also adds it to the map tab on the admin page.
When you click on the button, it sends a request to the back-end to update the `label_validation` table. Once it has been updated, the button changes shade. If you pick a different option afterward, it gets updated in the database and the shading switches to the new button.
These validations are separated from normal validations by having a different mission type.

1930 labelmap validation support

---

conf/routes

Resvoles #1940 
/labelingGuide and /labelMap are no longer case-sensitive.

1940 case insensitive URLs

---

app/controllers/AdminController.scala
app/models/label/LabelTable.scala
public/javascripts/Admin/src/Admin.GSVLabelView.js

Resolves #1932 
Adds validation data when clicking on a label on /labelmap or the admin page.

adds validation data to /labelmap popup

---

public/css/main.css

Resolves #1949 
Links to other cities on the landing page are now white (then yellow on hover) instead of yellow and then white on hover. This should make them more readable.
Before
After

landing page city links are now white

---

app/views/index.scala.html

This is a temporary code change where we manually remove the link to the nonexistent Columbus server from the landing page for Seattle and Newberg. When I added Columbus support to the configs (#1942) it automatically added a link to Columbus to Seattle and Newberg landing pages. I wanted to temporarily remove that so I can push the current develop code to the prod servers without a dead link on the landing page.

temporarily removed columbus city link from landing page

---

conf/evolutions/default/70.sql
public/javascripts/Admin/src/Admin.GSVLabelView.js

Fixes #1960 
The label type row for "Other" labels is no longer blank on the label popup on /labelmap. Also adds the label type to the title of the label popup.

1960 labelmap other label type blank

---

app/views/audit.scala.html
app/views/validation.scala.html
public/javascripts/SVLabel/css/svl-modal.css
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
public/javascripts/SVValidate/css/svv-modal.css
public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/modal/ModalMissionComplete.js

Resolves #1372 
Non turkers are now given the option to continue auditing after their third audit mission or continue validating after their third validation mission.
TODO I need to make sure I didn't break anything in mobile validation since I messed with the CSS.

1372 Give options for mission flow

---

app/views/mobileValidate.scala.html
app/views/rapidValidation.scala.html
public/javascripts/SVLabel/spec/SVLabel/modal/ModalMissionComplete-spec.js
public/javascripts/SVLabel/spec/SVLabel/modal/ModalMissionCompleteProgressBar-spec.js
public/javascripts/SVValidate/css/svv-modal.css
public/javascripts/SVValidate/mobile/mobileValidate.css
public/javascripts/SVValidate/src/modal/ModalMissionComplete.js

My updates to the CSS in #1968 messed up the look of the mission complete buttons on both the mobile and rapid validation interfaces. This PR just corrects those visual issues.

fixes mission complete CSS for mobile and rapid validate

---

public/javascripts/Admin/src/Admin.Panorama.js

Resolves #1962 
Updates the no imagery error message on /labelmap to be a bit more informative.

improves error message when no imagery on /labelmap

---

app/controllers/SignUpController.scala
app/views/signUp.scala.html

Fixes #1963 
Fixes the issue of not being able to sign up at the /signUp endpoint.
The problem was that when we added a 6 character minimum req for passwords and added a password confirmation field in PR #1755 we only added this to signing up via the navbar, and not to the /signUp endpoint. Adding the functionality there fixes the bug where we couldn't sign up.

1963 update password requirements

---

public/javascripts/SVValidate/src/data/Form.js

Fixes #1977 
Fixes the mission complete screen hanging when there are no validations left.
The problem was that I needed to hide the normal mission complete screen (`svv.modalMissionComplete.hide();`) before showing the no validations left screen (`svv.modalNoNewMission.show();`). Seems to be working as expected now.

fixes interface hanging when no validations left

---

app/views/audit.scala.html
app/views/userProfile.scala.html
public/javascripts/SVLabel/spec/SVLabel/modal/ModalMission-spec.js
public/javascripts/SVLabel/spec/SVLabel/modal/ModalMissionComplete-spec.js
public/javascripts/SVLabel/spec/SVLabel/status/StatusFieldMission-spec.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMission.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
public/javascripts/SVLabel/src/SVLabel/navigation/Compass.js
public/javascripts/SVLabel/src/SVLabel/status/StatusFieldMission.js
public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js

Resolves/Fixes #1793
Changed the instances of the word "audit" to "explore" where applicable to create a more user-friendly experience

#1793: Change "Audit" Language

---

conf/evolutions/default/72.sql
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/util/UtilitiesSidewalk.js

Resolves #1979 
Adds 'construction' and 'sign' tags to the obstacle label type, and 'construction' and 'brick' tags to the surface problem label type. Here is what the context menus look like now:
I made 'g' the shortcut for 'sign' (which you can't see underlined because of the font). I made 'i' the shortcut for 'brick'. And I made 't' the shortcut for 'construction' for both label types (to do that, I switched the shortcut for 'tree' from 't' to 'e').

Adds some new tags for obstacle and surface problem

---

public/javascripts/SVValidate/src/status/StatusPopupDescriptions.js

Fixed grammar mistakes in two of the No Sidewalk validation examples, removing the unnecessary "is" from both statements.
Resolves #1857

#1857 Fixed No Sidewalk Validation Description 

---

public/css/main.css

Resolves #1152
Changes the neighborhood completion overlay to fill the screen instead of being confined to the center portion of the screen. To test this overlay easily without having to actually move through the neighborhood you can go to the Javascript file `TaskContainer.js` and change the if statement inside the function `updateNeighborhoodCompleteAcrossAllUsersStatus` to show the overlay even when the neighborhood is incomplete.

#1152 Neighborhood Completion Overlay Now Fills Screen

---

public/javascripts/SVValidate/css/svv-status.css
public/javascripts/SVValidate/src/status/StatusField.js

Resolves #1849
Changed the titles for the example images on the right side of the validation interface from 'Curb Ramp' and 'NOT a Curb Ramp' to 'CORRECT Curb Ramp' and 'INCORRECT Curb Ramp', respectively.  The font size for the example text was also changed from 12 pt to 10 pt so that the validation example images didn't appear too far down as seen in the picture below:
Here are some new pictures with the correct validation image titles:

#1849 change titles on example images on validation

---

conf/cityparams.conf

Resolves #2014 
I've already made the changes to the database necessary to move Seattle to a two-phase deployment. This PR just increases the default zoom on all maps of Seattle given the smaller area we are focusing on.
Here's what it looked like before any changes
Here's what it looks like after moving to a subset of Seattle, before changing the zoom (choropleth shading looks different bc they are pics from different servers)
And here's what it looks like with the increased zoom

Increases default zoom for Seattle maps

---

app/controllers/ApplicationController.scala
app/views/index.scala.html
conf/cityparams.conf

Resolves #2012 
Adds a link to upcoming mapathon events to the landing page. This only shows up on servers for cities where we there are upcoming events (if there is a link in the conf/cityparams.conf file). If there are no upcoming events, then the text is absent. Here is with/without:

Adds link to mapathons on landing page

---

app/models/audit/AuditTaskTable.scala
app/models/daos/UserDAOImpl.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala

Converted all data on the admin interface to be displayed in respect to PST time instead of UTC time. Did this by converting timestamps in the "end_timestamp" column from PostgreSQL database into PST time.
Resolves issue #1653

#1653 Convert Admin Interface to PST Time

---

conf/cityparams.conf

Resolves #2024 
Changes the default zoom and map centering for Columbus, OH to accommodate expanding to more neighborhoods.

Changes default zoom and map center for Columbus

---

public/javascripts/AccessibilityChoropleth.js
public/javascripts/Admin/src/Admin.Task.js
public/javascripts/Admin/src/Admin.User.js
public/javascripts/Admin/src/Admin.js
public/javascripts/Choropleth.js
public/javascripts/LabelMap.js
public/javascripts/Progress/src/Progress.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionCompleteMap.js
public/javascripts/accessScoreDemo.js
public/javascripts/developer.js
public/javascripts/index.js
public/javascripts/mapEdit.js
public/javascripts/previousAudit.js

Resolves #2013 
Old styles created through Mapbox Studio Classic have been deprecated. This PR replaces those old styles we were using with more current ones that looks similar. We only had two different styles we were using across our maps; the minor differences shown below:
Landing page before
Landing page after
User dashboard before
User dashboard after

Replaces deprecate Mapbox styles

---

package-lock.json
package.json

Resolves #2042 
Upgrades npm libraries using `npm audit fix`. Includes a moderate severity security update to the "acorn" library.

2042 update npm libraries including acorn

---

app/views/index.scala.html

Fixes #2059 
Removes the line that filters out the Mexico City link on the landing page since the public version is up and running.

Adds Mexico City link to landing page

---

conf/messages.en
conf/messages.es

Resolves #2063 
Before, when using the sign up now link from the /signIn page, the web page would redirect to an invalid URL "/@routes.UserController.signUp()". The same goes for the sign in now link from the /signUp page. The new changes now route both correctly. The changes were made in both the messages.en and messages.es.

#2063 fixed sign up link bug from /signIn

---

app/views/navbar.scala.html
conf/messages.en
conf/messages.es
public/css/main.css

Resolves #2069 
Adds a link to /labelmap to the navbar, including logging of clicks. This shows up for Newberg, Columbus, and Mexico City. We don't show it for Seattle because the dataset is too large, and we don't show it for DC because it's using the old code base.

Adds Label Map link to navbar

---

docker-compose.yml

Resolves #2066 
Adds a POSTGRES_USER and POSTGRES_PASSWORD environment variables to the DB container in order for the container to start up properly.

#2066 added postgres environment variables to docker-compose from develop branch

---

app/controllers/ApplicationController.scala

Fixes #2078 
We are now appropriately logging "Visit_LabelMap" instead of "Visit_Results" when a user goes to the label map page.

Fixes logging of label map page visits

---

README.md

Resolves #2065 
Updates the dev environment instructions in the README to require a database dump (since it doesn't work out of the box without one). Also makes some other tiny edits to the instructions to make them more streamlined.

Fixes instructions to require loading the database dump

---

.gitattributes

Fixes #1527
Users should now have the correct style of line endings when cloning the repo. When I had fixed this last time, I had accidentally made exactly the _wrong_ line endings the default!

Fixes Windows CRLF line endings

---

docker-compose.yml

Fixes #2066 
Changes the POSTGRES_USER env variable to be "postgres" instead of "sidewalk" for the dev environment. Should fix the dev env issue of the postgres user not existing.

Fixes postgres user for dev env

---

check_streets_for_imagery.py

Resolves #2102 
The script that checks street view imagery was written to be run once for the entire city. This doesn't really make sense since most of our deployments are now multi-phase deployments, so we often want to run this script for just a subset of streets.
The changes I made here add a region_id column to the output. It also makes adjustment to how the progress is kept track of so that it actually works for a subset of the data.

2102 new city region id in imagery script

---

app/controllers/SignUpController.scala
app/views/accessScoreDemo.scala.html
app/views/admin/index.scala.html
app/views/auditCreateCVMissionForm.scala.html
app/views/clustering.scala.html
app/views/developer.scala.html
app/views/index.scala.html
app/views/labelMap.scala.html
app/views/labelingGuide.scala.html
app/views/labelingGuideCurbRamps.scala.html
app/views/labelingGuideNoSidewalk.scala.html
app/views/labelingGuideObstacles.scala.html
app/views/labelingGuideOcclusion.scala.html
app/views/labelingGuideSurfaceProblems.scala.html
app/views/mapEdit.scala.html
app/views/navbar.scala.html
app/views/noAvailableMissionIndex.scala.html
app/views/previousAudit.scala.html
app/views/results.scala.html
app/views/signUp.scala.html
app/views/terms.scala.html
app/views/turkerIdExists.scala.html
app/views/userProfile.scala.html
conf/routes

Partially fixes #2098 
The issue was that when a user signed up, the session cookie was not being updated to reflect that change. The authentication info would be saved on the server, the navbar would update with the new username, but the cookie was still using the old anon user account info. Then whenever data was sent to the server, it failed to authenticate that old anon user account info, and thus we were losing data.
This only started happening recently, because we used to save the old anon user authentication info in the database anyway under the same user_id. So the now signed up user would continue working, and the session cookie would say it was the anon user authentication info, but it would still be saved in the database under the correct user_id. Since @ThatOneGoat added the …

2098 Fixes bug where we lose user authentication

---

public/javascripts/SVLabel/src/SVLabel/mission/Mission.js
public/javascripts/SVLabel/src/SVLabel/mission/MissionFactory.js

Partially fixes #2120 
We were running into an issue where the mission progress bar was being stuck at 0%. This was because the progress for your mission was somehow being set to a negative number, and the progress bar stayed at 0% while you crawled out of that hole.
This is a hotfix that just checks if the progress is negative when updating every step and sets it to 0 if so. If it is negative, it also logs an error to the console, which I will be keeping an eye on in the future. This should fix all symptoms of the problem. I just have not found the root cause of it, as it is hard to reproduce.

hotfix for #2120, mission progress bar should not be stuck at 0 now

---

public/javascripts/Admin/src/Admin.js

Resolves #2062 
Updated city coverage progress graph in admin analytics to shows more detail using vega selection brush.  Seen in attached picture.

2062 show more detail in city coverage graph

---

app/views/developer.scala.html

Resolves #2084 
This PR fixes some typos on the API page. Specifically, it adds a space before the third sentence of optional parameters paragraph and corrects filetype=csv|geojson to filetype=[string].

#2084 API Page Optional Parameters Formatting

---

public/javascripts/Admin/src/Admin.js
public/javascripts/LabelMap.js
public/javascripts/Progress/src/Progress.js

Resolves #2085 
Adds dark polygon outline and gray overlay to neighborhoods on the label map and userdashboard map.  Feel free to test various colors, opacities, and border weights in the `Progress.js` and `LabelMap.js` files.
User Dashboard Before:
Label Map Before:
User Dashboard After:
Label Map After:

#2085 Add dark polygon outline and gray overlay to neighborhoods

---

conf/cityparams.conf

Resolves #2147 
Changes the default pan/zoom on the maps for the SPGG server to focus on just the San Pedro neighborhood. This code change should be accompanied by first running the following queries on the relevant server before pushing code to it:
```
UPDATE region SET deleted = TRUE WHERE region_id <> 7;
UPDATE street_edge
SET deleted = TRUE
FROM street_edge_region
WHERE street_edge.street_edge_id = street_edge_region.street_edge_id
AND region_id <> 7;
DELETE FROM street_edge_priority
USING street_edge
WHERE street_edge_priority.street_edge_id = street_edge.street_edge_id
AND deleted = TRUE;
TRUNCATE TABLE region_completion;
```
This will make the necessary changes in the database. The code then adjusts the maps appropriately.

changes map locations to focus on one spgg neighborhood

---

package-lock.json
package.json

Bumps websocket-extensions from 0.1.3 to 0.1.4 to fix a security vulnerability. Also updates a few npm packages used in the dev environment.

2129 upgrade npm packages (incl. websocket-extensions)

---

public/css/main.css

Resolves #727 
This PR solves a formatting issue on the Front Page. Specifically, it prevents the cumulative statistics from bleeding over in Safari.

#727 Cumulative Statistics on the Front Page Bleeds Over in Safari

---

public/javascripts/SVLabel/css/svl-map.css

Resolves #1221 
Uses the svl-map.css file to hide the expand button in the mini-map on the audit page. Example seen below:

#1221 Made expand button hidden

---

.gitignore
README.md

Resolves #2191 
Updates the README to tell people looking to deploy in their city to email us instead of just trying to set up the dev environment. I also added a few suggested plugins for IntelliJ IDEA to the README, and added the database dump files to the .gitignore.

2191 readme now triages new city requests

---

app/controllers/ApplicationController.scala
app/views/main.scala.html
conf/application.conf
conf/cityparams.conf
docker-compose.yml

Resolves #2113 
Since @mechanicjay recently added an ENV_TYPE environment variable to our servers with values "test" and "prod", I am now able to make a few changes in the code to differentiate those servers further. The changes made here are:
1. The test servers now have their own Google Analytics IDs. Each city had their own before, but now each city will have two, one for test and one for prod.
1. The links to other cities on the landing page now point to servers of the same type. So test servers now link to other test servers
1. I've added `ENV_TYPE=test` to the docker-compose.yml for the dev environment, so now our local dev environments should be using the test server analytics IDs and link to test servers on the landing pages.

Separates test and prod servers analytics IDs

---

app/forms/ForgotPasswordForm.scala
app/forms/ResetPasswordForm.scala
app/forms/SignInForm.scala
app/views/forgotPassword.scala.html
app/views/navbar.scala.html
app/views/resetPassword.scala.html
app/views/signIn.scala.html

Fixes #2040 
Fixes the warnings about multiple HTML elements having the ID. The issue was that all of our various sign in/up methods used identical IDs. So the password field had the ID "password" on the sign in page, sign up page, in the navbar sign in, navbar sign up, and on the password reset page. Multiple of these fields could be present at the same time. For example, at /signIn, there was the password field in the main form on the page, plus the password fields in the sign and and sign up forms within the navbar.
This PR fixes this issue by changing the names of a few elements to make them unique and removing the sign in button from the navbar on /signIn and /signUp.

Fixes warning from multiple HTML elements with the same ID

---

public/javascripts/Admin/src/Admin.js

Resolves #2197 
This PR fixes a bug on the analytics page of the admin dashboard where some charts were not showing up. Specifically, it ensures that when a group of charts are rendered together, only charts with data are included, as those without data (for some reason) prevent all charts from rendering.
Before:
After:

#2197 Some admin dashboard visualizations are not loading

---

README.md
conf/cityparams.conf

Resolves #2232 
Adjusts the default lat/lng and zoom for maps on the website so that the Del Valle neighborhood of SPGG is also in view. I've already added the neighborhood through the database, this will just update the maps accordingly.

Expand SPGG into Del Valle neighborhood

---

conf/messages.en
conf/messages.es

Fixes #2226 
Fixes the bug where clicking on "Terms and Conditions" brought you an error message instead of our terms/conditions.

fixes bug where terms and conditions does not show

---

app/views/index.scala.html
conf/cityparams.conf

Resolves #2248 
Removes links on the landing page to DC (permanently) and Pittsburgh (until we have the prod server set up). I also reordered the links on the landing page
from Newberg -> Seattle -> Columbus -> CDMX -> SPGG -> Pittsburgh
to Seattle -> Columbus -> CDMX -> SPGG -> Pittsburgh -> Newberg
Before on Columbus server
After

2248 remove Pittsburgh and DC links from landing page

---

app/views/index.scala.html

Addresses #2247 (removes embedded video from landing page)
**After:**
It's just commented out for now. Can completely remove in the future.

Addresses #2247 (removes embedded video from landing page)

---

app/views/index.scala.html

Partially addresses https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2227.
Changes the default url for city names to just the city server rather than the /audit page of the city server.
Note: I didn't change the header text (so it still just says "Let's create a path for everyone" rather than "<city name>, let's create a path for everyone" as described in Issue #2227)

Partially addresses Issue #2227: clicking on city name on landing page brings you to landing page of other city (rather than /audit)

---

app/views/admin/index.scala.html

Correctly bolds 'Total Validations' row in admin interface by making them th rather than td
Addresses https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2249

Addresses https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2249

---

app/views/index.scala.html

Resolves #2271 
Landing page had an unnecessary href to "/validate". Simply deleted it from code.

#2271 Removed unwanted href on landing page

---

public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js

Resolves #2238 
Changes the margin of surrounding elements in order to prevent the 'Continue' button from overlapping other elements. This can occur during resizing(zooming in/out) or at 100% zoom based on the size of the viewing window.
Before:
After:

2238 Mission-Complete-Visual-Bug-Fix

---

app/views/results.scala.html

Resolves #2216 
Fixed error with reset button where on firefox browsers you would get redirected to a page which said "null". Removed `href="javascript:null"` on reset-button at around line 71 in file app/views/results.scala.html.

#2216 Reset view error with firefox browsers

---

app/views/navbar.scala.html

Resolves #2305 
**This is how the navbar looked like before the fix:**
**This is how the navbar looks like after the fix:**
**How issue was fixed**
Go to app/views/navbar.scala.html and at line ~122 change `id="navbar-dropdown-list"` to `id="navbar-data-dropdown-list"`. This changes the id of the Data dropdown button. I think this bug was happening because the Sign-In and Data buttons had the same id's of `navbar-dropdown-list`. So then when script was changing the Data button instead of the Sign-In button.
**Potential bugs/issues**
If there were scripts that call the Data button, referencing the id `navbar-dropdown-list`, then there will be a problem because the new id for the Data button is `navbar-data-dropdown-list`. It will now reference the Sign-in button with the same id. I did not …

2305 navbar messed up after signing up

---

public/locales/en/dashboard.json

Resolves #2335 
Fixes text error in English version.
I am unable to replicate the bug because I do not have all the missions complete... here is the text file change.
Before:
After:

2335-User-Dash-Text-Correction

---

app/controllers/TaskController.scala
app/formats/json/TaskSubmissionFormats.scala
app/models/label/LabelPointTable.scala
conf/evolutions/default/93.sql
public/javascripts/SVLabel/src/SVLabel/PointCloud.js
public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVLabel/src/SVLabel/label/Label.js
public/javascripts/common/UtilitiesMath.js
public/javascripts/common/UtilitiesPanomarker.js

Resolves (partially) #2362 
Given that we no longer have depth data from Google, this PR uses the rough fallback approximation we have for the mini map for the back end as well. This fixes the issue of null lat/lngs in the database.
The approximation is quite crude. I believe it just assumes you are placing the label 10 meters or so in front of you, where "in front of" only takes into account your heading. So if you place labels on the top left and bottom right of the screen, they will show up in the same location as long as you did not pan between placing the labels.
I'm sure that we can improve on this approximation, but I wanted to get out _anything_ ASAP so that it doesn't look like we are missing data on our maps and such. Adding new approximations or altering old ones will be quite …

Adds rough approximation of latlng without depth data

---

app/models/audit/AuditTaskTable.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala
conf/cityparams.conf
public/javascripts/Choropleths/Choropleth.js

Resolves #2369 
Fixes a bug where the results map wouldn't load. It was a bug that came out of our choropleth refactoring (#2215) that we didn't catch because it only occurs in neighborhoods that have no labels contributed to them.
While I was there, I also made a small performance improvement to a few admin page queries and adjusted the map center/zoom in SPGG to accommodate the addition of the El Obispo neighborhood.

Fixes bug where results map wouldn't load

---

public/javascripts/SVValidate/src/label/LabelDescriptionBox.js
public/locales/en/validate.json
public/locales/es/validate.json

Resolves #2331 
Adds a heading of "user description: " for user comments on tags, displayed during validation.

2331-Differentiate-User-Description-On-Tags

---

public/javascripts/SVValidate/src/panorama/PanoramaContainer.js

Fixes #2382 
This fixes the bug where the first label you validate in a new mission looks like the same label from the end of the previous mission, even if the label type is incorrect. It was a mistake I made when removing the code for the rapid validation interface.

Fixes bug of new mission not setting first label correctly

---

app/views/labelMap.scala.html
public/javascripts/Admin/src/Admin.User.js
public/javascripts/Admin/src/Admin.js
public/javascripts/Progress/src/Progress.js

Fixes #2379 
Fixes the lack of scroll wheel zoom on label map, the user dashboard, and the admin interface. I had just forgotten to include those parameters when changing the choropleth code recently.

Fixes scroll wheel zoom on choropleths

---

public/javascripts/Choropleths/InitializeSubmittedLabels.js

Fixes #2378 
Removes the blank popup that showed up when clicking on a label on the user dashboard. We shouldn't be showing any popup there.

Removes empty popup when clicking on label on user dash

---

public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVLabel/src/SVLabel/label/Label.js

Fixes #2383 
Fixes the error I made in recording which method is being used to compute lat/lngs on the audit page.

Fixes recording of computation method for latlngs

---

public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/Admin/src/Admin.User.js
public/javascripts/SVLabel/src/SVLabel/status/StatusFieldNeighborhood.js

Fixes #2389 
Fixes the issue of spaces in usernames leading to issues by making sure that anytime a username is used in a URL in JavaScript, it is encoded using `encodeURI()`.

Usernames in URIs now being encoded everywhere

---

app/controllers/ValidationTaskController.scala
app/models/label/LabelTable.scala
conf/routes
public/javascripts/SVValidate/src/panorama/PanoramaContainer.js

Fixes #2393 
Fixes the bug where the 2nd label in a validation mission would be a repeat of the 1st. I also just removed an unused endpoint.

Fixes bug with repeating 2nd validation label

---

public/javascripts/Choropleths/Choropleth.js
public/javascripts/Progress/src/Progress.js

Fixes #2371 
Fixes the default zoom for the map on the user dashboard. We had decreased the size of the map, so we needed to zoom out a bit more on that map by default. I added an optional parameters to the Choropleth.js file to modify the default zoom.

Fixes zoom on user dashboard map

---

app/models/audit/AuditTaskTable.scala
app/models/label/LabelTable.scala
app/views/admin/user.scala.html

Fixes #2380 
Makes some of the label counts on the admin pages more consistent by removing deleted and/or tutorial labels from them.

Removes deleted or tutorial labels from some counts/maps

---

app/models/audit/AuditTaskTable.scala
app/models/daos/slick/UserDAOSlick.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala
app/models/street/StreetEdgeTable.scala
docker-compose.yml

Resolves #2272 
Changed some SQL queries that relied on time data to use 'US/Pacific' instead of 'PST', since 'PST' is only accurate for 6 months of a year due to daylight savings. 
These changes are reflected in the admin table and can be tested by performing two labeling missions (must have separate audit ids) and manually changing one of them to a day before with this command: 
```docker exec -it projectsidewalk-db psql -c "UPDATE sidewalk.audit_task SET task_end = '<updated time>' WHERE audit_task.audit_task_id = <audit_task_id>" -U sidewalk -d sidewalk```

2272 update admin time queries

---

app/models/daos/slick/UserDAOSlick.scala

Resolves #2311
**What I did**
Around line 490 in `app/models/daos/slick/UserDAOSlick.scala`, I changed `.min` to `.max`. The statement was taking the minimum sign in date, which would return the least recent date. `.max` returns the most recent date. 
I also removed `AnonAutoSignUp` when counting the logins because it would give us one extra login that was not really a login.
**Problem that arises**
Some users do not have a last login because I removed `AnonAutoSignUp`. This happens mostly for users who only signed in once. I think `SignIn` was not logged into the `WebpageActivityTable` because of issue #2361, so they do not have a `Last Login` value.

2311 last login before user registered

---

app/models/mission/MissionTable.scala
public/javascripts/SVLabel/src/SVLabel/mission/MissionProgress.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMission.js
public/javascripts/SVLabel/src/SVLabel/status/StatusFieldMission.js
public/javascripts/common/UtilitiesMath.js

Resolves #2324 
Changes the sequence of mission lengths from 500 ft, 500ft, 750 ft, 1000 ft, ... to 250 ft, 250 ft, 500 ft, ... I also updated the code that displays the distances to end users to round to the nearest 25. So instead of saying 76 m, 76 m, 152 m, it will say 75 m, 75 m, 150 m. Nothing changes on the back end, just wanted to display nicer numbers to end users. Due to the shortening of mission lengths, I also made it so that the survey shows up near the end of the 2nd mission instead of near the beginning.

Shorten audit/explore mission lengths

---

app/controllers/ValidationTaskController.scala
app/formats/json/CommentSubmissionFormats.scala
conf/routes
public/javascripts/Admin/src/Admin.GSVLabelView.js
public/locales/en/common.json
public/locales/es/common.json
public/stylesheets/main.css

Resolves #2239 
This PR adds a comment box and submit button to the labelmap GSV popup for validation.
This is what it looks like:
This is it working:
Here is the Spanish version:

#2239 Add comment box to labelmap GSV popup

---

conf/evolutions/default/98.sql
public/javascripts/SVLabel/src/SVLabel/label/Label.js

Resolves #2374 
Improves our estimation of lat/lng for labels placed through the explore page. I ran some linear regressions to create predictors for the distance from the panorama and the heading, and now we use those predicted values to calculate lat/lng of a label, given `pano_lat`, `pano_lng`, `heading`, `zoom`, `canvas_x`, `canvas_y`, and `sv_image_y`. More information on the regression analysis can be found [here](https://github.com/ProjectSidewalk/label-latlng-estimation/blob/master/scripts/label-latlng-estimation.md#overview).
Before at any zoom level (note on mini map that they all collapse to one spot):
After at zoom level 1:
After at zoom level 3 (as expected, the predicted change in heading has a smaller range):
After at zoom level 1, with the camera angled downward (note that …

Improve label latlng estimation

---

app/models/daos/slick/UserDAOSlick.scala

Fixes #2433 
Fixes an issue where the count of the number of users was very inflated on the admin dashboard. The check that a user had validated at least one label was missing from the combined audit + validation user count.

Fixes bug in user counts on admin dashboard

---

app/views/index.scala.html

Resolves #2402 
Replaced the link to the article in The Diamondback, as it was broken, to the new one. Made sure the new link was attached both for image and the text, tested it on Chrome using localhost.

#2402: Press link broken on landing page - I replaced the broken URL to the new URL, for both image and the text. 

---

app/views/main.scala.html
public/stylesheets/main.css

Resolves #2384
The footer was too tall before with some empty space after it. I made it shorter and have consistent vertical padding of 50px. This only affects css by id, so it shouldn't have any affect on other code and it's static.
before (header height is large):
after (smaller header height):
- [check] If there is a visual design component, I've posted before/after screenshots on the relevant issue thread and have been given a thumbs up on my design.
- [check] I've added/modified comments for large or confusing blocks of code.
- [check] I've made sure my code and comments follow the [style guide](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Style-Guide).
- [firefox, chrome, safari] I've tested on multiple browsers.
- [check] I've verified that this PR is set to merge into …

#2384 Reduce size of vertical footer on landing page

---

public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/canvas/Canvas.js

Fixes #2460 
Fixes the bug that I introduced with my lat/lng estimation fix. The `zoom` value is now parsed to an integer immediately when we get it so that it can safely be used for indexing. I also just removed a couple lines of unused code that I found :grin:

Fixes bug where you can't place a label

---

conf/cityparams.conf
public/javascripts/Choropleths/Choropleth.js
public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionCompleteMap.js
public/javascripts/accessScoreDemo.js
public/javascripts/developer.js

Resolves #2462 
Changes the default zoom/pan for maps in SPGG since we've revealed some new neighborhoods there. I also increased the granularity of the map zoom in general (from 0.5 to 0.25), and used that to slightly increase the zoom in Columbus and Pittsburgh, and slightly decrease it in Newberg. This is just to make those maps looks slightly better :ok_hand: 
Before (note that these are on my local dev env, so there isn't much data):
After:

Changes SPGG map pan/zoom

---

app/views/index.scala.html

Fixes #2461 
This should fix the slow load times on the landing page in Seattle. The issue is some code that we had commented out in a template scala file (`.scala.html`) using an HTML comment instead of a template scala comment. Which means that the code was being run, and only the visible HTML output was being commented out. This was code for a leaderboard that we thought about adding to the landing page. The leaderboard query takes a long time in Seattle at this point (5 seconds). I just removed that commented out code completely for now. Hopefully this speeds things up!

Fixes slow landing page load times in Seattle

---

app/views/admin/index.scala.html
app/views/index.scala.html
app/views/results.scala.html
public/javascripts/Choropleths/Choropleth.js
public/stylesheets/choropleth.css

Resolves #2428
Super quick fix for the hidden results legend. The legend mistakenly had a css attribute "display: none" that was causing it to be hidden. I removed the inline css and it shows back up when I log in as a normal user or an anonymous user.
before
after
- [no design issue] If there is a visual design component, I've posted before/after screenshots on the relevant issue thread and have been given a thumbs up on my design.
- [should already be translated] I've asked for and added translations for any user facing text that was added or modified.
- [code is short] I've added/modified comments for large or confusing blocks of code.
- [check] I've made sure my code and comments follow the [style guide](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Style-Guide).
- [firefox, …

#2428 Fixes hidden legend on results map

---

conf/cityparams.conf

Resolves #2479 
Updates the map configs to show all of SPGG since we've now revealed all of the neighborhoods.
Before (on my local env with very little data):
After:

Updates SPGG map parameters

---

app/models/label/LabelTable.scala

Resolves #2474 
Improves load time of some web pages by optimizing queries that get label tags.
I tested on my local dev environment, running an up to date Seattle database dump (our largest database atm). Speed improvements will be smaller for smaller databases.
* Loading the admin page went from 45 seconds to 20 seconds
* Loading an admin version of a user's page went from 8 seconds to 2 seconds for a user with a lot of labels. If the user has very few labels, the load time should be around 2 seconds regardless.
* Loading the validation page had no significant change in load time, but I updated the query for labels to validate in the same way. This added consistency and allowed me to delete a few helper functions we were using for the old method.
The reason we see speedups in the first …

Optimize some queries that get tags or validations

---

app/models/label/LabelTable.scala

Fixes #2492 
Fixes a bug where the tag names were messed up (replaced by "center-ui.tag.\<tag-id\>") on the validation page.
My bad! I rewrote a bunch of queries, and all of them except for this one used the tag ID instead of the tag name! Nice catch @jonfroehlich

Fixes messed up tag names on validation

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Resolves #2308 
Streamlines the Issue and PR templates by cutting down on wordiness and cutting less important sections.
My first attempt was overly verbose and specific. I think it was sometimes helpful for very new interns to help them realize all the different things they can/should be thinking about when making a new Issue/PR. But after day 1, it just became overly cumbersome and no one wanted to use it. I'm hoping that the redesign strikes a better balance!

Streamlines issue and PR templates

---

Makefile
app/views/navbar.scala.html
conf/messages.en
conf/messages.es

Resolves #2138 
Rewords the text on the overlay that lets turkers know that their auditing time is up. I also fixed the Makefile because I recently replaced the tabs with spaces, and I guess the tabs are important in the Makefile :sweat_smile: 
Before/after English:
Before/after Spanish:

Rewords mturk HIT timeout overlay

---

app/models/amt/AMTAssignmentTable.scala
app/models/audit/AuditTaskTable.scala
app/models/daos/slick/UserDAOSlick.scala
app/models/label/LabelTable.scala
app/models/label/LabelTypeTable.scala
app/models/label/LabelValidationTable.scala
app/models/mission/MissionProgressCVGroundtruthTable.scala
app/models/mission/MissionTable.scala
app/models/mission/MissionTypeTable.scala
app/models/region/RegionPropertyTable.scala
app/models/region/RegionTable.scala
app/models/street/StreetEdgeRegionTable.scala
app/models/street/StreetEdgeTable.scala
app/models/survey/SurveyQuestionTable.scala
app/models/user/UserRoleTable.scala
app/models/user/VersionTable.scala

Resolves #2101 
Marginally improves the efficiency of SQL queries that just output a `COUNT` by changing `.list.size` to `.size.run`, `list.head` to `.first`, and `.list.headOption` to `.firstOption`. The first one moves the counting computation out of Scala and into SQL. The latter two just remove the middle step of putting the result into a Scala list and then taking the first element; instead, we just grab that first element directly.
I don't expect these changes to have any material impact on website performance because I had already fixed the egregious examples of this problem. But this is technically more efficient and a better style, and it was really easy/fast to fix in one go, so I think it was worth it :wink:

Marginally improves efficiency for SQL COUNT queries

---

app/controllers/AdminController.scala
app/models/user/UserStatTable.scala
app/utils/actor/UserStatActor.scala
conf/routes

Resolves #2107 
Speeds up the nightly computation of user stats. There are two big optimizations:
1. Only updating stats for users who have audited in the past 36 hours instead of recomputing stats for everyone.
2. Using the bulk update feature in Slick for updating the `high_quality` column. Doing two bulk updates (one for high quality users and one for low quality users) is much faster than doing a thousand individual updates.
Since I set it to only look at users who audited in the past 36 hours by default, I added a separate admin endpoint (`/adminapi/updateUserStats`) where we can do a full recomputation of stats for everyone, in case that ever comes up. We can also specify an arbitrary cutoff time at that endpoint.
On my local dev environment using a Seattle database dump from Feb …

Speeds up nightly computation of user stats

---

app/controllers/AttributeController.scala
app/controllers/helper/AttributeControllerHelper.scala
app/models/attribute/GlobalClusteringSessionTable.scala
app/models/attribute/UserClusteringSessionTable.scala
app/models/user/UserStatTable.scala
app/utils/actor/ClusterLabelAttributesActor.scala
app/views/clustering.scala.html
conf/evolutions/default/106.sql
conf/routes
label_clustering.py

Resolves (partially) #2499 
Speeds up the nightly clustering of labels into accessibility attributes. We achieve this by only re-clustering users and neighborhoods where the underlying data changed. The underlying data changes either because a new user joined, an existing user added new data, or an existing user changed from being low quality to high quality (or vice versa).
The time to run clustering on **all** of the Seattle data on my local machine took the same amount of time on this branch vs the develop branch: 21 minutes for single user clustering and 12 minutes for multi-user clustering. Then if I try adding some data with my own account and running the incremental clustering update with this branch, it takes 10 _seconds_ for single user clustering, and 7 minutes for multi-user …

2499 speed up label clustering

---

app/utils/actor/ClusterLabelAttributesActor.scala
app/utils/actor/RecalculateStreetPriorityActor.scala
app/utils/actor/UserStatActor.scala
conf/cityparams.conf

Resolves #2504 
Staggers when the nightly updates occur by city. The difference in time zones let's us start start the updates within a smaller window in local time. Here are the start times we're looking at now:
10:30 pm PDT - Columbus (1:30 am local)
11:30 pm PDT - Pittsburgh (2:30 am local)
12:30 am PDT - SPGG (1:30 am local)
1:30 am PDT - CDMX (2:30 am local)
2:30 am PDT - Seattle (2:30 am local)
3:30 am PDT - Newberg (3:30 am local)
Given the different time zones, we're able to start the updates an hour apart in each of the 6 cities while starting between 1:30 am and 3:30 am (a 2 hour window).
Hopefully this will spread out the load on the shared resources and might be improve performance slightly.

Staggers nightly updates by city

---

README.md

Resolves #2517
Changed user in the credentials for database tools to be "postgres" instead of "sidewalk", as for users where "sidewalk" will work, "postgres" will also work. 
Before
After

2517: Changed Credentials for Database Tools in README.md 

---

public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/Admin/src/Admin.Panorama.js

Resolves #2416 
This PR makes it so that on the labelmap, if there is no imagery, then the "Is this label correct?" header and the comment submission stuff are hidden in addition to the validation buttons. Also, I did some CSS styling just to make the popup look a little nicer (in my opinion). Please let me know what you think!
Before:
After:

#2416 Hide validation content when no imagery on labelmap.

---

app/views/labelingGuide.scala.html
public/stylesheets/help.css

Resolves #2453 
Adds a note to the top of the labeling guide encouraging users to label objects up close because it is more accurate. I also noticed a small CSS issue on the /help page and fixed that.
Before
After

Encourage labeling nearby objects in labeling guide

---

app/views/help.scala.html

Resolves #178 
This adds a question to the help/FAQ page about the interface being too small, and instructs users to use their browser zoom. I also noticed that the help page has old instructions to double click to move forward (including a video), which has been replaced by the Stuck button. So I removed the video and updated the text for that question as well.
We need a better long term solution for the need for zooming in our tools. Either through better user training or through actually making our interface zoom dynamically. But we've needed to make those changes for years, so I figured it's better to get _something_ into the /help page now than to just continue to wait for us to implement something more sustainable.
Before
After

Adds zooming suggestion to help page

---

app/models/audit/AuditTaskInteractionTable.scala
app/views/admin/index.scala.html
app/views/admin/user.scala.html
public/stylesheets/admin.css

Resolves #266 
Adds combined time spent auditing/validating to the dashboard at `/admin/user`. We have to look through interaction logs, so it was too time consuming to add to the full table of users on the admin dashboard, but we could add it to this page. I also fixed up some CSS for the user table on the admin page because we have lost horizontal scrolling at some point!
Before
After

Add time audited/validated to admin user page

---

app/controllers/AdminController.scala
app/controllers/AuditController.scala
app/controllers/MissionController.scala
app/controllers/SurveyController.scala
app/controllers/UserProfileController.scala
app/controllers/ValidationController.scala
app/models/audit/AuditTaskInteractionTable.scala
app/models/audit/AuditTaskTable.scala
app/models/daos/slick/UserDAOSlick.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala
app/models/mission/MissionTable.scala
app/models/street/StreetEdgeTable.scala
app/views/admin/index.scala.html
app/views/admin/user.scala.html
app/views/userProfile.scala.html

Resolves #2265 
Standardizes and shortens function names in the `app/model` files. @jonfroehlich pointed out that some, but not all, of the functions that take in a user ID were named `getBlahByUserId`. I decided to remove the `ByX` in any function names where the `X` there is just one of the parameters to the function. It should be clear when you say `countLabels(userId)` that you are counting the labels for that user, so it doesn't need to be called `countLabelsByUserId(userId)`. This standardizes our naming conventions and shortens some of the really long function names we had.
I also removed some instances of including the schema name (which is "sidewalk") in some queries, since it is implied. This just means I changed a lot of `FROM sidewalk.audit_task` to `FROM audit_task`.
None of …

Standardize and shortens function names

---

check_streets_for_imagery.py
requirements.txt

Partially addresses #2547 
Improves the script that checks for missing GSV imagery by checking at numerous points along a street instead of just the endpoints. The script used to check for imagery at each endpoint, and it either endpoint was missing imagery, it would be marked as not having imagery. This update still checks the endpoints, but it also checks approximately every 15 meters along each street for imagery.
The new logic we're using is to mark a street as not having imagery if:
1. neither endpoint has imagery,
2. only one endpoint has imagery while at least 25% of the points along the street have no imagery, or
3. both endpoints have imagery but at least 50% of the points along the street have no imagery.
This more complicated logic is meant to address two types of streets I've …

Improves script that checks for missing GSV imagery

---

public/javascripts/Gallery/src/Main.js
public/javascripts/Gallery/src/filter/CardFilter.js

Fixes #2554 
There was a race condition that could occur in Gallery which would cause some of the translations to not load, namely, the tag names in the filtering section. It wasn't caught in our dev environments just because of the timing difference when sending something over a network.
I fixed it by putting the `_initUI()` and `_init()` functions for Gallery in `Main.js` inside the callback to `i18next.init()` instead of just being called after it. This must have just slipped my mind during the initial code review, oops!
Before:
And in the worst case:
After:

Fixes race condition where tag translations did not load in Gallery

---

public/javascripts/Gallery/css/cards.css
public/javascripts/Gallery/css/gallery.css
public/javascripts/Gallery/src/modal/Modal.js

Fixes one issue raised in #2587 
This removes the extra whitespace between the filtering section and the actual cards. Since I'm getting rid of that whitespace, I increased the size of the cards slightly.
Before
After

Removes extra whitespace in Gallery, increases card size

---

public/javascripts/Gallery/css/cards.css

Resolves #2600 
Replaces a drop shadow on the small Gallery cards with a 1 px gray outline along the lower portion of the cards
Before
After

Removes drop shadow from small Gallery cards

---

public/javascripts/Gallery/css/gallery.css
public/javascripts/Gallery/src/cards/Card.js
public/javascripts/Gallery/src/cards/CardContainer.js
public/javascripts/Gallery/src/filter/CardFilter.js
public/javascripts/Gallery/src/modal/Modal.js

Fixes #2606 
The expanded view now closes whenever we change the filter or move to a new page in Gallery.
Before (when you click open the modal, then change the filter)
After (same scenario)
1. Load gallery
2. Click on a card to open expanded view
3. Go to the filters and pick a label type that is different from the type of your current card
4. The modal should close and the newly filtered cards should load correctly

Gallery close modal when filtering or paging

---

app/controllers/GalleryController.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala
public/javascripts/Gallery/css/cards.css
public/javascripts/Gallery/src/cards/Card.js
public/javascripts/Gallery/src/validation/ValidationMenu.js

Resolves #2603 
If you are signed in, validations that you had made in the past now show up on Gallery when it loads. This incorporates your validations from /validate, /labelMap, /gallery, or through the admin page!
Before (on initial page load)
After (on initial page load)
1. Visit Gallery
2. Filter for a specific label type, severity, and/or tag. Drill down however far you need to so that there are only a small number of labels, which will make it easier to test.
3. Validate a bunch of those labels in Gallery
4. Reload Gallery and add the same filters. You should see your previous validations showing up!
Testing that contributions through /validate or /labelMap are a lot easier on a smaller database, since there will be fewer non-validated labels to sift through.

Show previous validations in Gallery

---

public/javascripts/SVValidate/src/label/LabelDescriptionBox.js

Resolves #2595 
Description: On /validate, the label descriptions are formatted incorrectly. I added some strings in the JS file: "LabelDescriptionBox.js" and it fixed it.
1. Hover over the label and see the fix
2.

2595 - Fixed text issue on validate

---

app/controllers/AdminController.scala
app/models/label/LabelTable.scala
app/views/admin/index.scala.html
app/views/admin/user.scala.html
public/javascripts/Admin/src/Admin.GSVLabelView.js

Resolves #2626 
The agree/disagree/unsure buttons on the popup on LabelMap now appear to have been clicked if you've already validated this label with your currently logged in account. Validations you've contributed through any means count (validation page, gallery, labelmap, or admin page). We use the same popup in numerous places on the admin dashboard as well, and these changes work in all of those places.
Before (right after a page load, showing a label that I've already validated)
After (same situation)
1. Go to /labelMap and add a label
2. Refresh the page and click on the same label. The same button should look like it has been pressed!
3. Can be repeated for /admin/user/\<username\>. Can also be repeated in the Map, Contributions, and Label Search tabs on the /admin page.

Previous user validations now show up on LabelMap and admin pages

---

app/models/label/LabelTable.scala
app/models/label/LabelTypeTable.scala
public/javascripts/Gallery/src/cards/CardContainer.js
public/javascripts/Gallery/src/filter/Tag.js

Resolves #2617 
Partially #2639 
Removes Other and Can't See the Sidewalk from the All category in Gallery, while leaving it available in the label type drop down.
Before
After

Removes other/occlusion from Gallery All category

---

public/javascripts/Gallery/src/cards/CardContainer.js
public/javascripts/Gallery/src/filter/Severity.js
public/javascripts/Gallery/src/filter/Tag.js
public/javascripts/Gallery/src/modal/Modal.js

Resolves #2602
This PR aims to allow users to be able to iterate through gallery pages while remaining in modal view through the use of the modal arrows.

2602 Allow the use of modal arrows to navigate between pages.

---

public/javascripts/Gallery/css/modal.css
public/javascripts/Gallery/src/cards/Card.js
public/javascripts/Gallery/src/cards/CardContainer.js
public/javascripts/Gallery/src/modal/Modal.js
public/javascripts/Gallery/src/validation/ValidationMenu.js

Resolves #2651 
Adds a colored border to the interactive GSV area in the expanded view in Gallery that corresponds to the validation status of the label being shown. I also realized that the validation wasn't being updated on the expanded view when it was marked on the smaller card, so I had to restructure the code a bit to make that work correctly.
Before (mouse on GSV)
After (mouse on GSV)
Before (mouse not on GSV)
After (mouse not on GSV)

Adds border to interactive GSV in Gallery when label is validated

---

public/javascripts/Gallery/css/cards.css
public/javascripts/Gallery/css/gallery.css
public/javascripts/Gallery/css/modal.css
public/javascripts/Gallery/css/tags.css
public/javascripts/Gallery/src/filter/Severity.js

Resolves #2654 
This does a couple small things to the sidebar:
1. Decreases whitespace between smiley faces
2. Adds hover functionality to smiley faces to match the hover functionality for tags
3. Decreases the overall width of the sidebar slightly (screenshots below show the biggest change in the look of the tags that happens because of this, it's very minor).
4. Slightly increases the size of the cards and the expanded view given the decrease in the width of the sidebar.
Before (no expanded view)
After (no expanded view)
Before (expanded view)
After (expanded view)

Improve look of severity smileys in Gallery sidebar

---

public/javascripts/Gallery/src/displays/TagDisplay.js

Resolves #2612 
The tags on the cards in Gallery now end in an ellipsis if they don't fit. I set it up so that it requires a minimum amount of available space in order to show a truncated tag over putting it in the list of tags hidden in the '+n' tooltip.
Before
After

Tags on Gallery cards end in ellipsis when appropriate

---

app/controllers/AdminController.scala
app/models/label/LabelTable.scala

Resolves #2667 
Fixes the issue where the audit page became unusable because a query that was used to add labels to the database was taking minutes instead of milliseconds. A small side change: we had a divide by 0 error for neighborhoods with no streets in them that I've fixed.

Fixes audit page after postgres 12 postgis 3 upgrade

---

app/controllers/ProjectSidewalkAPIController.scala
app/controllers/RegionController.scala
app/controllers/UserProfileController.scala
app/models/gallery/GalleryTaskInteractionTable.scala

Fixes #2668 
Fixes how neighborhoods with holes look on our website. I had thought that the geometries themselves were messed up, but it turns out that we just were not using the GeoJSON spec correctly for polygons with holes! It's a little bit more complicated and there weren't functions to do it for me in one line, but it was only a couple extra lines to fix. I made this change for both the endpoint that we use for maps, and for the API endpoint that returns polygons.
Before
After

Fixes the look of neighborhoods with holes

---

app/controllers/ProjectSidewalkAPIController.scala
app/controllers/RegionController.scala
app/models/region/RegionTable.scala
conf/evolutions/default/120.sql

Resolves #2673 
Adds support for neighborhoods with disconnected parts. To support those types of geometries, we needed to change the data type for neighborhoods in the database from "Polygon" to "MultiPolygon", change the corresponding data types in Scala, and then update how we convert those geometries into GeoJSON. After that, everything we have on the front-end worked out of the box with multi-polygons :)
I created a test neighborhood by combining two neighborhoods that already existed in my local dev environment, so I know that it works. But I don't have any examples to show with neighborhoods from an actual deployment. My next steps are to make the database for Chicago using multi-polygons and update the wiki page documentation accordingly!

Adds support for neighborhoods w/ disconnected parts (multipolygons)

---

app/views/gallery.scala.html

Resolves #2663 
Fixed the persistance of the dropdown in the `/gallery` page (in firefox) by adding the `autocomplete="off"` tag to dropdown menu. I additionally verified that this bug no longer existed in Chrome, Firefox, and Edge. Are there any other browsers that I need to test this on?
Chrome:
https://user-images.githubusercontent.com/15069663/139382012-5d316a73-8b0f-4433-987f-3cb535771985.mp4
Firefox:
https://user-images.githubusercontent.com/15069663/139382055-6549f47c-081d-4b6f-a1a9-2c973f80522d.mp4
Edge:
https://user-images.githubusercontent.com/15069663/139382081-69499e16-446d-4a0e-85e1-0f2c74955ce9.mp4
1.  Select a filter in `/gallery` under the "Show" header
2. Refresh the page
3. The filter should now reset to "All"

Fix persistant filter on refresh

---

public/javascripts/Gallery/src/cards/Card.js

Resolves #2639 
I hid the severity on the occlusion cards in the gallery by adding a conditional statement. Should we also hide the severity on this view?
1.  Go to `/gallery` and filter based on "Can't See Sidewalk"

Hide severity on occlusion cards

---

app/views/developer.scala.html

Resolves #2689
Replaced the obsolete links with links to the updated document.
1.  check the links on https://sidewalk-sea.cs.washington.edu/developer to make sure they link to the right pages:
Three feature collection links should be changed from 
https://geojson.org/geojson-spec.html#feature-collection-objects
to
https://datatracker.ietf.org/doc/html/rfc7946#section-3.3
The Point features link should be changed from
https://geojson.org/geojson-spec.html#point
to
https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.2
The LineString features link should be changed from
https://geojson.org/geojson-spec.html#linestring
to
https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.4
The Polygon features link should be changed from
https://geojson.org/geojson-spec.html#polygon
to …

changed links on api page

---

public/javascripts/common/UtilitiesSidewalk.js
public/locales/en/audit.json
public/locales/es/audit.json

Resolves #2549 
This is a brief description of the problem solved or feature implemented and how you implemented it.
Before:
After:
1. On the main page, click on Start Exploring
2. Click on Let's Get Started
3. Click on curb ramp
4. Click on the image to place the curb ramp marker
5. Check/test to make sure the w is underlined for "narrow" and that pressing w will highlight the "narrow" keyword
6. Change the language to Spanish and follow the same steps, except the "narrow" keyword will now be called "muy angosta".

changed narrow tag keyboard shortcut for curb ramps from a to w

---

app/controllers/ValidationTaskController.scala
app/models/label/LabelValidationTable.scala
app/models/street/StreetEdgePriorityTable.scala
app/models/user/UserStatTable.scala
conf/evolutions/default/124.sql
conf/evolutions/default/125.sql

Resolves #2698
We are now including accuracy as determined by user validations into our heuristics for determining the quality of users' work. This is used primarily for routing right now. The new heuristic is that a user's data is considered "high quality" if they have a labeling frequency of at least 3.75 labels per 100 meters AND an accuracy of at least 60%. If less than 50 of the user's labels have been validated, then we revert to just the labeling frequency heuristic.
The new `accuracy` column of the `user_stat` table is being updated in real time as validations come in, but the `high_quality` column is only being updated nightly because it would require other things to update in real time as well.
This also adds a new `exclude_manual` column to the `user_stat` table. This is meant …

Validation accuracy is now used for determining street audit priority

---

public/javascripts/SVValidate/mobile/mobileValidate.css

Resolves #2536 
Users with long (or even medium length) usernames have their name cut off on the mobile validation page when they sign in. 
Fixes include changing the width to max-width so a username can only get so long before getting cut off into ellipses in the button.
Before: 
After:

2536 Long usernames cut off in mobile

---

app/views/leaderboard.scala.html

Toggles the team leaderboard's visibility based on whether the team leaderboard has any entries. 
Resolves #2733 
Before fix: 
After fix:

#2733 new team leaderboard visibility requirements

---

app/controllers/AdminController.scala
app/controllers/AttributeController.scala
app/controllers/LabelController.scala
app/controllers/ProjectSidewalkAPIController.scala
app/controllers/TaskController.scala
app/controllers/ValidationTaskController.scala
app/controllers/helper/ShapefilesCreatorHelper.java
app/formats/json/LabelFormat.scala
app/models/attribute/GlobalAttributeTable.scala
app/models/attribute/UserClusteringSessionTable.scala
app/models/daos/slick/UserDAOSlick.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala
app/models/region/RegionTable.scala
app/models/user/UserStatTable.scala
app/views/admin/index.scala.html
app/views/admin/user.scala.html
conf/evolutions/default/127.sql
public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/Admin/src/Admin.js
public/javascripts/SVValidate/src/label/Label.js
public/javascripts/SVValidate/src/mission/MissionContainer.js

Resolves #2699 
This PR does a few important things:
1. Adds validation info the our /attributes and /attributesWithLabels public APIs.
2. Adds columns for validation counts to the `label` table, making it easier to get information about validations going forward. These columns are updated in real time as validations are entered into the system.
3. I updated all places where we were using counts of validations to now use the precomputed values in the columns mentioned above.
4. Various small bug fixes related to validations, clustering, and the API.

Adds validation info to public APIs

---

public/javascripts/Gallery/css/cards.css
public/javascripts/Gallery/css/modal.css
public/javascripts/Gallery/src/displays/TagDisplay.js

Resolves #2644 
- Gallery tags will wrap to a maximum of two rows. 
- In the case where there are more tags that can fit within two rows, a vertical scrollbar appears. 
- Works on all screen sizes. 
Before:
After:
1. For testing, add many tags and see if intended functionality works. 
2. Check on many screen sizes.

#2644 Tags in Modal dont wrap

---

app/controllers/AdminController.scala
app/controllers/UserProfileController.scala
app/models/audit/AuditTaskTable.scala
app/models/label/LabelTable.scala
app/views/labelMap.scala.html
conf/routes

Begins to address #2786 
For now, we are simply filtering out all data from "low quality" users, and all labels with more disagree validations than agree validations. We are going to make this configurable in the UI in the next week or two, but this was a quick change we could make for now to improve the look of the map! From my two test databases, we're filtering about 7% of the labels in Columbus and 23% of the labels in Seattle (though we don't show LabelMap publicly in Seattle anyway).

Filter out low quality data from LabelMap

---

app/controllers/AdminController.scala
app/controllers/TaskController.scala
app/formats/json/TaskSubmissionFormats.scala
app/models/gsv/GSVDataTable.scala
app/models/label/LabelTable.scala
conf/evolutions/default/135.sql
conf/routes
public/javascripts/SVLabel/src/SVLabel/data/Form.js

Begins to fix #2485 
We are now recording a lot more metadata about the panoramas that we're using. This also fixes incorrect recording of the metadata that we had been doing in the past. Here's a list of changes:
* We are now correctly recording `image_width`, `image_height`, `tile_width`, and `tile_height` in the `gsv_data` table. We had previously been recording hard coded values of 13312, 6656, 512, and 512 respectively, but these are not actually constant across all panoramas. Going forward, we are recording the correct values from the StreetView API. I've marked all previous data as `NULL`, and I'm hoping that we can write a script to correct the metadata for the imagery that is still available.
* We are now also recording the `center_heading`, `origin_heading`, and `origin_pitch` …

Record more panorama metadata

---

public/javascripts/SVLabel/src/SVLabel/navigation/Compass.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js

Resolves #2825 
Adds smooth panning to the callback when clicking on the navigation messages in the bottom-right of the audit page.
It turns out that this feature had actually already existed! It was just not being used anywhere. And it was kinda broken and would sometimes spin in circles forever :grin: I fixed the bug and we're good to go now!

Clicking navigation message now does smooth panning

---

app/controllers/AdminController.scala
app/models/audit/AuditTaskTable.scala
conf/routes

Begins to address #808 
Adds a new admin-only API endpoint at /adminapi/auditedStreetTimes that shows every audit, along with the timestamp for the audit, and some metadata about the user who performed the audit.

Adds admin API to get times when all streets were audited

---

app/views/leaderboard.scala.html
conf/messages.en
conf/messages.es
conf/messages.nl
public/stylesheets/main.css

Resolves #2801:
Removed incorrect weekly leadership message along with its message and associated translations in the conf conf folder and adjusted css for weekly leaderboard header to add additional spacing to make weekly and overall leaderboard tables still align when shown horizontally
Before:
After:
1. Make sure a user has been active within the last week so the weekly leaderboard appears.
2. Go to the "leaderboard" page under the "data" tab to see the page.
3. Check overall leaderboard and weekly leaderboard table alignment when fullscreened (alignment not necessary when display is small enough to stack tables vertically).

#2801: Weekly Leaderboard Fix

---

conf/messages.nl
public/locales/nl/common.json

Resolves #2831
Adjusted Dutch language files to set measurement system to 'metric' instead of 'metriek' to allow metric calculations to be used on Dutch version of the webpage.
Before:
After:
1. Check the "Miles Covered" stat on the front page of the en-US version
2. Compare to the "Kilometers afgelegd" stat on the front page of the nl version
3. If the stats are significantly different (calculated properly between miles and kilometers) it should be working!

#2831: Fix Dutch Measurement System

---

public/javascripts/SVLabel/src/SVLabel/canvas/Canvas.js
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
public/javascripts/common/Utilities.js

Resolves #2791 
Instead of showing a broken tooltip on the Explore page when there is no example image available, we show no tooltip at all anymore.
Before
After

Hide broken tooltips when no example image available

---

public/javascripts/Gallery/src/cards/Card.js
public/javascripts/Gallery/src/filter/CardFilter.js
public/javascripts/SVLabel/css/svl-context-menu.css
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js

Resolves #2795 
Removes severity as an option for the Pedestrian Signal label type, as the severity metric doesn't make much sense for that type. This also removes severity from the list of filters for Pedestrian Signal in Gallery.
Before
After

Removes severity options for Pedestrian Signal label type

---

app/views/navbar.scala.html

Resolves #2816
Results map tab is now hidden whenever the current server is Chicago, IL. Also removed redundancy in hiding local map tab for Seattle server.
Before:
After:
1. Load up the Chicago Test Server
2. Click on the "data" tab in the navbar
3. If the first dropdown button is NOT "results map" then the button was hidden correctly!

2816: Temporarily hiding the Chicago Server "Results Map" button

---

app/controllers/AdminController.scala
app/models/label/LabelTable.scala
app/views/admin/index.scala.html
app/views/admin/user.scala.html
app/views/labelMap.scala.html
app/views/userProfile.scala.html
conf/routes
public/javascripts/Admin/src/Admin.Panorama.js
public/javascripts/Admin/src/Admin.js
public/javascripts/Choropleths/Choropleth.js
public/javascripts/Choropleths/InitializeMapLayerContainer.js
public/javascripts/Choropleths/InitializeSubmittedLabels.js
public/javascripts/Choropleths/MapUtilities.js
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
public/javascripts/SVLabel/src/SVLabel/label/Label.js
public/stylesheets/admin.css

Resolves #2786 
Adds validation status filters to the UI in Label Map. Also adds the ability to add back in users who have been marked as 'low quality' using the browser console. There are instructions for how to do the latter that get logged to the browser console when you load the page.
I reduced some padding in the legend since it was getting a bit unruly. There is an identical map on the admin page that has also been updated.
Before
After

Adds validation status filters to the UI in Label Map

---

public/javascripts/SVLabel/src/SVLabel/navigation/Compass.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js

Resolves #2850 
Fixes an issue with the smooth panning on the Explore page. Indeed, some function expected a positive angle as an input, and we were not always providing a positive number.

Fixes smooth panning

---

app/views/navbar.scala.html

Resolves #2829 
Changed city dropdown button to display current city's shortname.
Before:
After:
1. After loading in page, check the navbar buttons on the top right
2. If the 3rd to last button (after "Data" and before "Sign In") is the shortname of the current city, the change works. If it still says "city" then it did not go through.

#2829: Changing the Navbar's "city" button to the current city shortname

---

public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js

Resolves #2862 
Fixes an issue where label tags with no image to put in the tooltip on the explore page were showing a tooltip for a different tag altogether.
Before
After

Fixes tooltips showing up on the wrong tags

---

app/views/labelMap.scala.html

Resolves #2854 
Fixes the checkbox on LabelMap for the curb ramp labels! It was a small copy/paste error that I missed.

Fixes LabelMap curb ramp checkbox

---

app/controllers/AdminController.scala
app/formats/json/LabelFormat.scala
app/models/label/LabelTable.scala
build.sbt
conf/routes
package.json

Adds an API endpoint at `/adminapi/labels/cvMetadata` to get the metadata for labels that we need for our most recent computer vision project. Here is some example output:
```
[
{
"label_id": 173572,
"gsv_panorama_id": "qos0p3mBdh7Pynq2N-1SWw",
"label_type_id": 4,
"deleted": false,
"tutorial": false,
"agree_count": 0,
"disagree_count": 0,
"notsure_count": 1,
"sv_image_x": 9927,
"sv_image_y": -624,
"canvas_width": 720,
"canvas_height": 480,
"canvas_x": 384,
"canvas_y": 212,
"zoom": 3,
"heading": 267.84820556640625,
"pitch": -18.546875,
"photographer_heading": 180.2176055908203,
"photographer_pitch": 0.13916778564453125
},
...
]
```

Adds API endpoint for label metadata for CV project

---

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js

Resolves #2631 
- Disabled up/down arrow keys whenever walking is disabled (Keyboard.js, MapService.js)
- _Created "disableMovement" status parameter in Keyboard.js that enables/disables the up/down arrow keys which is enabled/disabled on calls to "enableWalking()" and "disableWalking()" in MapService.js._
- Fixed bug where timedMove() would disable walking buttons without re-enabling them or temporarily disable them unnecessarily (Keyboard.js)
- _"\_movePano()" function now returns true if google maps successfully moves, and false otherwise. The "timedMove()" function no longer disables walking during the tutorial, and instead temporarily disables walking only if a successful move in google maps occurs._
Before:
After:
1. Enter the tutorial by clicking the "Start Exploring" tab on the …

2631: Fixed tutorial malfunction due to arrow key inputs

---

app/controllers/ApplicationController.scala
app/controllers/TaskController.scala
app/models/audit/AuditTaskTable.scala
app/models/region/RegionCompletionTable.scala
app/models/street/StreetEdgePriorityTable.scala
app/models/street/StreetEdgeTable.scala
app/views/index.scala.html

Resolves #2872 
Most uses of completion percentage and distance on our site now include only audits from users who have provided "high quality data". This removes a lot of the confusion between what users see on the landing page and what they see on the audit page.
I also reduced the time before these cached numbers are recalculated from every hour to every 30 minutes, so that we get to see the total percentage increase over the course of a mapathon.
I will need to wipe the `region_completion` table on every server in order for this change to fully take effect.
Before/After Seattle stats (from January)

Fix inconsistent completion percentage

---

app/controllers/GalleryTaskController.scala
app/models/gallery/GalleryTaskEnvironmentTable.scala
app/models/gallery/GalleryTaskInteractionTable.scala
conf/evolutions/default/144.sql
public/javascripts/Gallery/src/validation/ValidationMenu.js

Resolves #2885 
Fixes the logging in Gallery so that we can connect logs back to users in the future. Adds a `user_id` column to the `gallery_task_interaction` and `gallery_task_environment` tables. We also start to actually record the `gsv_panorama_id`, and start recording the `label_id` in the `note` section for validation actions in Gallery here.
We aren't going back to try and fix old logs, since that would be impossible in some cases, and would be a lot of work either way. I recorded this issue on the [relevant wiki page](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Developer-notes).
Before
After

Fix Gallery logging

---

conf/cityparams.conf
conf/evolutions/default/146.sql
public/javascripts/common/UtilitiesSidewalk.js
public/locales/en/audit.json
public/locales/en/common.json
public/locales/es/audit.json
public/locales/es/common.json
public/locales/nl/audit.json

Resolves #2897 
Renames the tag from 'brick' to 'brick/cobblestone' for both the Surface Problem and Crosswalk label types.

Renames brick tag to brick/cobblestone

---

conf/cityparams.conf

Resolves #2909 
Switches the La Piedad server from 'private' to 'public', so it now shows up in the drop-down list of cities in the navbar.

Adds La Piedad to the list of publicly deployed cities

---

public/javascripts/SVLabel/src/SVLabel/Tracker.js
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
public/javascripts/SVLabel/src/SVLabel/label/LabelContainer.js

Resolves #2924 
Fixes a bug that prevented users from completing the final step of the tutorial, simply clicking the 'OK' button at the end.
The cause seemed to be that PR #2154 unknowingly introduced a requirement that all context menu related actions be logged before the context menu is closed. This isn't an issue in the normal course of labeling, since it takes time for a human to go from rating severity to closing the menu, for example. The problem with the tutorial is that we programmatically close the context menu immediately upon rating severity or adding tags, causing a race condition. And closing the context menu tended to win that race!
So I added a check when logging context menu related actions to put everything in the correct state depending on whether or not the context menu …

Fixes bug preventing users from completing tutorial

---

app/views/main.scala.html
conf/messages.en
conf/messages.es
conf/messages.nl
public/stylesheets/main.css

Resolves #2861 
Before English and Spanish Version:
After English Version:
After Spanish Version:
Changes Made:
1. Centered Text under NSF Logo (took care of mobile representations of website as well)
2. Added #2125087 with hyperlink
3. Added Spanish translation for text
Side-effects: None

#2861: NSF Funding Info Footer

---

public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js
public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js

Resolves #2734
Removed name key from onboarding states which caused the bug, and removed outdated section of onboarding which relied on the name parameter
Before:
After:
1. Load the tutorial
2. Pan the screen either through dragging or the arrow keys
3. If the arrow does not disappear, it works!

2734: Fixed issue where panning makes the first tutorial arrow disappear

---

app/models/label/LabelTable.scala

Resolves #2913 and #2929 
#2913 Changed the google panorama URL from http to https which fixes the incorrect labels for expired google panoramas and fixes the #2929 bug, both validate and gallery pages now load correctly. 
Before: 
After: 
1. In order to check /labelMap, first reset label values so that every label is not marked as expired. 
Open up a new terminal in the root directory of the Project Sidewalk code. run the following commands
`$ make ssh target=db `                                                                                          # opens db container
`# psql -U sidewalk -d sidewalk `                                                                                  # opens database connection
`# UPDATE gsv_data SET expired = FALSE;` …

Fixed #2913 and #2929 Fixes labelMap, gallery and validate page. Changed expired pano label http to https.  

---

app/controllers/ProjectSidewalkAPIController.scala
app/formats/json/UserFormats.scala
app/models/user/UserStatTable.scala
app/views/developer.scala.html
conf/routes

Resolves #2890 
Adds an API endpoint to get various statistics about Project Sidewalk users. Mostly around counts of labels, validations, as well as accuracy, distance audited, etc. Here's some sample output:
```
[
{
"user_id":"0047c5c4-fc44-4843-9453-b79389b15246",
"labels":40,
"meters_explored":2565.70068359375,
"labels_per_meter":0.015590283088386059,
"high_quality":false,
"high_quality_manual":null,
"label_accuracy":0.7599999904632568,
"validated_labels":25,
"validations_received":88,
"labels_validated_correct":19,
"labels_validated_incorrect":6,
"labels_not_validated":15,
"validations_given":44,
"dissenting_validations_given":36,
"agree_validations_given":6,
"disagree_validations_given":2,
"notsure_validations_given":10,
"stats_by_label_type":{
"curb_ramp":{
"labels":13, …
```

Adds an API endpoint to get user stats

---

app/controllers/AdminController.scala
app/models/daos/slick/UserDAOSlick.scala
app/models/label/LabelValidationTable.scala
app/models/region/RegionCompletionTable.scala
app/models/street/StreetEdgePriorityTable.scala
app/models/street/StreetEdgeRegionTable.scala
app/models/street/StreetEdgeTable.scala
app/utils/actor/RecalculateStreetPriorityActor.scala

Resolves #2872 
Fixes an issue with the maps on our site, where they would sometimes show up as "100% audited" when they really were not! I also added in a nightly wipe of the `region_completion` table, which is where those completion percentages come from. We recalculate the priority for street edges every night, so we should be recalculating these completion percentages as well, since they are based on the audit priority of streets.
This before/after is on a local database dump, where I've done some extra fake auditing. So the change is more drastic locally than it will be on the production servers. The nice part is that it makes it easier to see the changes ;)
Before
After

Fix completion percentage on maps

---

app/views/signIn.scala.html
app/views/signUp.scala.html

Resolves #2762 
If you were to try to change the language using the navbar on either the sign-in or sign-up page, it would take you to the home page (in the language you changed it to) rather than just staying on the sign-in or sign-up page. To fix this, I just added "some(\signIn)" or "some(\signUp)" (depending on page) so that when the language is changed, it doesn't go to home, but just goes to the page that it is on.
Before:
Goes from sign-in/sign-up page to home page when language changed.
After:
Stays on sign-in/sign-up page with page language changed.
Testing instructions
1.  Run locally
2. Go to /signUp
3. Change language (to see if language changes, but page stays the same)
4. Try creating an account (to see if sign-up form still works)
5. Go to another page using navbar (ie: …

#2762: Changing language on the sign in/up pages sends you to landing page

---

public/locales/nl/common.json

Resolves #2947 
There was a line of code in public/locales/nl that had the tag set as "brick" instead of "brick/cobblestone", and therefore couldn't be identified for translation. I changed it to be "brick/cobblestone".
1. Navigate to the Gallery page and filter for Sidewalk Problems. The brick/cobblestone tag should be translated. If the brick/cobblestone tag is attached to a validation label, it should also be translated.

#2947 Dutch brick/cobblestone tag

---

public/javascripts/SVLabel/src/SVLabel/label/Label.js

Resolves #2949 
if (properties.severity === undefined) {
showSeverityAlert(ctx);
}
The function above was not being called. I changed the triple equals (===) to be only a double equals (==) and that seemed to fix the issue.
The question mark only shows on labels that have an available severity rank.
1. Place a label that has a severity rank option (e.g., curb ramp, missing curb ramp) and the red question mark should automatically show
2. If you click off of the label without submitting a severity rank, the question mark should remain
3. Once you select a severity rank, the question mark should disappear

#2949: Reinstated question mark when severity rating is missing

---

app/controllers/CredentialsAuthController.scala
app/controllers/SignUpController.scala
conf/evolutions/default/156.sql

Fixes #326 
Login email addresses are no longer case sensitive!
The only thing left to do is deal with the five instances where users signed up multiple times with the same email address using a different capitalization. In all cases, there is an account that clearly has more work put into it. I'll just change the email address for their less used account to a dummy email address so that the names don't clash.
1. Create an account on the develop branch with a capital letter in the email address
2. Log out and try to sign back in, changing the capitalization (it should fail)
3. Switch to this branch and try signing back in with a different capitalization (it should work)
4. On this branch, make a new account, sign out, and sign back in with a different capitalization (it should work)

Email address is no longer case sensitive

---

app/models/user/UserStatTable.scala

Fixes #2965 
Fixes a bug in the /v2/userStats API where column names were not matched up to the correct data.
Before
After

Fixes dissenting validations column in /v2/userStats API

---

app/models/daos/slick/UserDAOSlick.scala
app/views/admin/index.scala.html

Resolves #2966 
1. Open the Users tab on the admin page
2. Scroll to the far right, and there should be a high-quality column with true and false values

#2966: Added high quality column to user table in admin dashboard

---

app/views/userProfile.scala.html
public/javascripts/Choropleths/MapUtilities.js
public/javascripts/SVLabel/src/SVLabel/status/StatusFieldNeighborhood.js

Resolves #2783
Corrected the hyperlink url in `public/javascripts/SVLabel/src/SVLabel/status/StatusFieldNeighborhood.js`
Added turf script in `app/views/userProfile.scala.html` for the map zoom in. 
Corrected if statement inside `public/javascripts/Choropleths/MapUtilities.js` in order to focus on the region. 
For :  <img width="223" alt="image" src="https://user-images.githubusercontent.com/95188914/182269190-96e8d9c6-483c-4042-bebf-1e8edb5a823c.png">
**Before:** 
**After** :
1.  Sign into Project Sidewalk
2. Click Start Exploring Tab
3. Click the hyperlink under Current Neighborhood. 
- I've written a descriptive PR title.
- I've included before/after screenshots above.
- I've tested on mobile (only needed for validation page).

Fixes #2783 Neighboorhood Hyperlink Page 

---

app/controllers/ForgotPasswordController.scala

Resolves #2981 
Password reset email is no longer case sensitive.
1. Create an account, then sign out
2. Click the "Forgot Password" option and input your account email with random capital letters (not all lowercase)
3. When you click "Send Email" it should send a password reset

#2981: Password reset email is no longer case sensitive

---

app/models/label/LabelTable.scala
app/models/user/VersionTable.scala

Resolves #2995 
Fixes a couple issues that caused Gallery, Validate, and the user dashboard to try and show labels on GSV imagery that had expired.
There were two causes. The first is that Google seems to have made a change to the response to their `https://maps.google.com/cbk?output=tile` API, such that it always returns a 200 OK response code, with just a black image if the imagery is no longer available.
The second was an issue in the way in which we generate URL signatures. We have some code that gets an HMAC-SHA1 Mac instance and initialize it with the HMAC-SHA1 key, and we were doing that only once. It turns out that we need to create that instance every time we want to generate a new URL signature -- Don't ask me why, it's just how their example code works, and when I switched ours …

2995 fixing missing imagery errors

---

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
public/javascripts/SVValidate/src/panorama/Panorama.js

Resolves #2993 
Google switched up some of the DOM structure and number of links they have on the bottom of their GSV windows. I've adjusted our code to appropriately deal with these changes.
They added a new keyboard shortcuts link that we don't want to show. And we had to change how to raise these links to the top layer so that the terms of use remain clickable. I also updated things to remove some of the unnecessary links on the mini map on the Explore page, raising the little bug report link to the top so that it's now clickable.
Explore before
Explore after
Validate before
Validate after

Fixes location of GSV terms of use links

---

app/models/label/LabelTable.scala
public/javascripts/Progress/src/MistakeCarousel.js

Resolves #3000
Fixes an issue where you might see the same label multiple times in the carousel of recent mistakes on the user dashboard.
Before -- notice that there are three images (you can see three white dots near the bottom of the img), and the first two are the same
After -- you can see only two images, no dups

Remove duplicate images from mistakes on User Dashboard

---

app/models/attribute/UserClusteringSessionTable.scala
app/models/user/UserStatTable.scala

Resolves #3003 
Filters out labels that have been validated as incorrect, even if they come from users marked as "high quality".
On my local dev environment that's using a database from Seattle in 2021, here's how clustering changed.
* Labels into clustering: 107,108 (before) -> 96,750 (after)
* Clusters created from single-user clustering: 86,008 -> 78,452
* Time for single-user clustering: 19.2 minutes -> 17.9 minutes
* Final number of clustered attributes from multi-user clustering: 74,802 -> 68,020
* Time for multi-user clustering: 22.9 minutes -> 21.2 minute

Removes labels validated as incorrect from the API

---

app/models/label/LabelTable.scala

Resolves #3018 
Validate now prioritizes recently added labels, in an attempt to more quickly fill the 'recent labeling mistakes' on the User Dashboard, and fill in accuracy numbers in the 'weekly' table on the Leaderboard page.
It is the least important factor in the prioritization algorithm, after the user having fewer than 50 of their labels validated overall, the labeler being "high quality", and the label having no previous validations.

Validate now prioritizes recently added labels

---

app/controllers/AttributeController.scala
app/controllers/helper/AttributeControllerHelper.scala
app/models/attribute/GlobalAttributeTable.scala
app/models/attribute/GlobalClusteringSessionTable.scala
app/models/attribute/UserClusteringSessionTable.scala
app/models/audit/AuditTaskTable.scala
app/models/daos/slick/UserDAOSlick.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala
app/models/street/StreetEdgePriorityTable.scala
app/models/street/StreetEdgeTable.scala
app/models/user/UserStatTable.scala
app/utils/actor/ClusterLabelAttributesActor.scala
conf/evolutions/default/161.sql
conf/routes

Resolves #3013
We improve the quality of the data that we show on pages like Gallery and the API by removing labels from low quality users (unless their labels are marked as correct), and improve the consistency across our site and reusability of our code by making this consistent across the site.
We had been slowly rolling out filters to remove data from low quality users on various pages on the site, which led to inconsistencies and more custom code. This PR greatly improves on that issue. Full details can be found in #3013.

Improve consistency/quality of data across the site

---

app/controllers/ProjectSidewalkAPIController.scala
app/controllers/helper/ShapefilesCreatorHelper.java
app/models/street/OsmWayStreetEdgeTable.scala
app/models/street/StreetEdgeTable.scala
public/javascripts/developer.js

Resolves #2874
Adds a flag to the `/streets/` API representing whether each street has been audited yet. The API now returns all streets in the bounding box, rather than just audited streets.
- A street is marked as audited as long as it has at least one corresponding audit task and that audit task is complete. It is marked false otherwise.
-  The `StreetAttributeSignificance` class used by the `/streets/` API is also used in the calculations for the `/neighborhoods/` API, so some of its code also had to be updated to ignore the added flag. I could also add a similar metric the the `/neighborhoods/` API to represent the percent of streets audited if that's of interest.
Before:
After:
1. Run branch locally
2. Navigate to the API page (`/api/`)
3. Click on the example requests under …

#2874 return all streets in api

---

app/controllers/ProjectSidewalkAPIController.scala
app/controllers/TaskController.scala
app/controllers/helper/ShapefilesCreatorHelper.java
app/formats/json/LabelFormat.scala
app/models/attribute/GlobalAttributeTable.scala
app/models/label/LabelTable.scala
app/models/street/OsmWayStreetEdgeTable.scala
app/models/street/StreetEdgeTable.scala
conf/evolutions/default/163.sql

Resolves #3032
This fixes a few bugs introduced by our recent PRs in the `/v2/access/score/streets` and `/v2/access/score/neighborhoods` APIs, particularly on streets with no label data.
Here's a mostly comprehensive list of bugs I found. All of these are new as of the most recent version.
* There were cases where we were returning duplicate attributes in the `attributes` and `attributesWithLabels` endpoints
* If there are no labels on a street/neighborhood, we were returning an incorrect timestamp. Now we are just returning `null`
* If a street or neighborhood had no labels, sometimes there would just be a server error
* For the streets API, we were computing the average image and label age based on any type of label on the street, whereas AccessScore only uses our four primary label …

Fixes various street and neighborhood API bugs

---

public/javascripts/Admin/src/Admin.GSVLabelView.js

Fixes #3015 
Comment submitted popover no longer pushes content down when visible.
1.  Go to /labelMap.
2. Click on a label.
3. Submit a comment through the interface.

comment submitted popover no longer pushes down content

---

public/javascripts/Gallery/src/displays/TagDisplay.js

Resolves #2761 
This is a brief description of the problem solved or feature implemented and how you implemented it.
Modified the condition to compute extra space needed while displaying tags to account for the presence of hidden tags.
Before
After
1. Add the following tags to a 'Surface Problem' card—bumpy, grass, uneven/slanted, very broken. This combination of tags should show the PLUS_N (in this case '+1') in the next line on a Macbook Pro 13.3-inch (2560 × 1600) display.
2. With the new fix, the PLUS_N should be '+2' and should be shown on the same line as tags.
3. Add different combination of tags to cards and verify that the PLUS_N indicator doesn't get pushed to the next line in any case.

#2761: Fix for keeping the PLUS_N indicator in the same line on the gallery page.

---

app/models/label/LabelValidationTable.scala
app/models/user/UserStatTable.scala

Fixes #3069 
If accuracy should have been 0% or 100% in our database, it was showing up as null. The issue is that in our queries to compute accuracy, we would count the number of correct labels as:
```
SUM(CASE WHEN correct THEN 1 END)
```
But if there were no correct labels, then we were basically taking the sum of a bunch of nulls, which gave us null! There are two correct ways to do this, either of the following:
```
SUM(CASE WHEN correct THEN 1 ELSE 0 END)
COUNT(CASE WHEN correct THEN 1 END)
```
I went with the latter, since it changes our code the least :shrug: I also did a quick search through our code, and it looks like I only made this mistake when calculating accuracy. We do it correctly everywhere else.

Fixes bug where accuracy was null when it should be 0% or 100%

---

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js

Resolves #3073 
Google recently added panning/moving using WASD in Streetview, but this most notably conflicts with our Surface Problem (S) and Crosswalk (W) shortcuts. There is no setting to disable keyboard shortcuts in Streetview (though there is in the overhead Google Map), but I was able to prevent the firing of those events.
1. Pan so that you are aligned head-on with the navigation arrows
2. Move forward by clicking on an arrow
3. Hit the 'S' key. You should _not_ move backwards!

Fixes bug from conflicting GSV keyboard shortcuts

---

conf/cityparams.conf

Resolves #3086 
Adds the "stairs" and "garage entrance" tags for Obstacle labels in our Zurich deployment.
Before
After

Add stairs and garage entrance tags in Zurich

---

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js

Resolves #1449 
This (should) _finally_ prevent the neighborhood complete message from showing erroneously when loading the audit page! We had a check in there that was meant to check that we had loaded the list of streets in the neighborhood, but that check really only checked that the object that holds the list of streets was created. I added a boolean that gets set when the streets have _actually_ finished loading, and it solved the issue!
In addition to this being a race condition, the other reason that this was hard to reproduce, was because this code only gets called when the user was being started near the end of the street they were assigned. This only happens when resuming a mostly finished street, or if you are assigned a very short street segment. There are many such short …

Fixes neighborhood complete message showing erroneously

---

app/controllers/AdminController.scala
app/controllers/UserProfileController.scala
app/models/audit/AuditTaskTable.scala
app/models/mission/MissionTable.scala
app/models/user/UserCurrentRegionTable.scala
app/models/user/UserStatTable.scala
app/models/utils/CommonUtils.scala
app/views/admin/user.scala.html
public/javascripts/Admin/src/Admin.User.js
public/javascripts/Choropleths/InitializeStreets.js
public/javascripts/Progress/src/Progress.js

Resolves #3085
Update some of our distance calculations so that they all use the length of the streets, combined with the list of completed tasks in the `audit_task` table. Prior, we were using the `distance_progress` column in the mission table for some of these calculations. But it's better to keep them consistent! It only makes the code a tiny bit more complex :)

Standardize audited distance calculation

---

public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js

Resolves #[3068](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/3068) 
This is a brief description of the problem solved or feature implemented and how you implemented it:
Added an if prior to calling ratingReminderAlert on svl to ignore calling ratingReminderAlert if the prop's labelDescription is a Pedestrian Signal.
1. Place 4 Pedestrian Signal labels to confirm if the severity rating reminder popup appears.
2. Place 4 of any other label (besides "Can't see the Sidewalk") to confirm if the severity rating reminder popup still appears.
- [X ] I've written a descriptive PR title.
- [ X] I've included before/after screenshots above.

3068 - remove severity label for pedestrian signal

---

public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/neighborhood/Neighborhood.js
public/javascripts/SVLabel/src/SVLabel/task/Task.js

Resolves #3087 
Fixed Region ID not showing on GSV info popup on the Explore page.
Before:
After:
1. Navigate to Explore page and click on the GSV info button to see popup.

Fix getRegionId

---

public/javascripts/SVValidate/css/validate-mission-start-tutorial.css

Resolves #3103 
The validate mission screens were looking bad at different zoom levels. This PR fixes it with some CSS changes and media queries.
Before
After
1. Open the validate mission tutorial.
2. Change the browser zoom to the following levels: 110%, 125%, and 133%. 
3. Ensure that the layout is optimum in all cases.

Fixing mission screens for browser zoom levels: 110%, 125%, and 133%.

---

app/views/missionStartTutorial.scala.html
public/javascripts/SVValidate/css/validate-mission-start-tutorial.css

Resolves #3115 
Tightening the vertical spacing on the validate mission screen.
Before
After
1. Test that the new layout looks good with all the label types and locales.
2. Test that the new layout looks good at 110%, 125%, and 133% zoom levels.

3115: Validate mission screen new layout

---

public/javascripts/SVLabel/src/SVLabel/task/Task.js

Resolves #3133 
Fixes a bug that caused no data to be sent to the back end in Firefox. No data was saved, and you couldn't move on to a second mission. The issue was a different implementation of the `Date.parser()` in JavaScript between different browsers.

Fixes Explore page not working on Firefox

---

app/views/forgotPassword.scala.html
conf/messages.en
conf/messages.es
conf/messages.nl

Resolves #3059 
Added message above textbox for email to reminder users that project sidewalk accounts are not transferable between cities.  
1. Go to Forgot Password page in each respective language and view updated text

3059 - added reminder user regarding accounts not being transferable between cities

---

app/controllers/ForgotPasswordController.scala

Resolves #3062 
Added logging using the info level of logging to the ForgotPasswordController so all emails are logged when users are trying to reset their password on the forgot password page. (Note to self: Scala logging documentation [here](https://www.playframework.com/documentation/2.8.x/ScalaLogging))
1. Go to "Forgot password" page and type in email
2. Check logs to confirm "Logging user's email: " + email entered is present
Future steps: If time permits, I want to explore the database option and making this an activity in the webpageactivity table. For now this is just to get the ticket resolved but this can be innovated in the future for sure.
- [TBD] I've updated any logging. Clicks, keyboard presses, and other user interactions should be logged. If you're not sure how (or if …

3062 - adding logging for all emails to forgot password controller via logger

---

app/models/label/LabelTable.scala

Fixes #3128 
Fixes the default Gallery view where we show assorted label types. The label types are not mixed randomly again!
Before
After

Gallery assorted labels are now randomized again

---

app/views/main.scala.html
public/javascripts/Gallery/css/filter.css
public/javascripts/Gallery/css/tags.css
public/javascripts/Gallery/src/cards/CardContainer.js
public/javascripts/Gallery/src/filter/CardFilter.js
public/javascripts/Gallery/src/filter/Tag.js
public/javascripts/Gallery/src/filter/ValidationOption.js
public/javascripts/Gallery/src/filter/ValidationOptionBucket.js

Resolves #3122 
Adds a dedicated hover state to Gallery filters that is separate from the selected v deselected states.  A few other minor issues were fixed, like the validation options not looking like they were disabled when we were waiting for new images to load, and the browser console error about not having a callback func for Google Maps is now gone!
Before (oops my screenshot doesn't show my mouse, but it is hovering over the 'missing tactile warning' tag!
After

Improves Gallery hover and disable UI for filters

---

public/javascripts/SVLabel/src/SVLabel/label/Label.js

Resolves #3177 
Fixes a bug where you were unable to label on the Explore page in Safari (outside of the tutorial). It seems that Google's `StreetViewPanorama` objec'ts `getPov()` method will return an integer `1` in Chrome/Firefox, but `1.0000000000000002` in Safari. I must have removed rounding it to an integer. The rounding has been reinstated!

Fixes a bug where you can't label in Safari

---

public/javascripts/SVLabel/src/SVLabel/ribbon/RibbonMenu.js

Resolves #3180 
Fixes a visual issue where the Other label type was not visible on the Explore page in Safari, it was being pushed down to the next row, below the Explore button.
This is very much a hotfix. When I changed the CSS `display` attribute to something different, and then back to `inline-block` (which is where it should be), then the button gets put in the right place! So there is clearly enough space for the button... It might just be that when it is first rendered, some other element may not have fully loaded yet, which is causing the issue.
I don't think that digging into the root cause is important enough right now, so I just added some code the toggles the `display` attribute back and forth. It puts the button in the right place, and you never see it missing now 🤷 
Before …

Fixes hidden Other label type on Explore page Safari

---

public/stylesheets/main.css

Resolves #3047 
Clamps the neighborhood name in the right sidebar to 1 line (hiding overflow text) so that label counts don't get cut off when neighborhood name is longer than 1 line.
Before: 
After:
1. Navigate to Results Map page
2. Choose neighborhood with long name (ex. Central Business District) and click "Click here" to explore neighborhood
3. Observe right sidebar neighborhood name and label counts

Fixes sidebar label counts getting cut off

---

conf/cityparams.conf

Resolves #3158 
Removes missing crosswalk tag from "Other" label on Explore by adding missing crosswalk to excluded tags.
Before: 
After: 
1. Navigate to Explore page
2. Add "Other" label - see tags available

Removes missing crosswalk tag from "Other" label on Explore.

---

conf/cityparams.conf

Resolves #3186 
Adds the configs for a new server in Cuenca, Ecuador! I also realized that the HOCON syntax for our config files lets us reference values in other parts of the config, so I updated it a bit to have few values copied in multiple places. In particular, it's nice that we now have a `united-states-default` and `mexico-default` list of excluded tags! :grin:

Adds configs for Cuenca, Ecuador server

---

public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js

Fixes #3187 
Fixes an issue where the instructions in the tutorial would cover UI elements that you needed to click to progress. @jonfroehlich suggested changing the z-index of the instructions / context menu when hovering over the context menu, which worked great!
Before
After

Instructions no longer cover UI in tutorial

---

app/controllers/AdminController.scala
app/controllers/ApplicationController.scala
app/controllers/RegionController.scala
app/controllers/UserProfileController.scala
app/controllers/helper/ControllerUtils.scala
app/models/audit/AuditTaskTable.scala
app/models/label/LabelTable.scala
app/models/region/RegionCompletionTable.scala
app/models/region/RegionTable.scala
app/views/labelMap.scala.html
app/views/navbar.scala.html
conf/routes

Resolves #3190 
Adds a query parameter to LabelMap to filter for only data in given neighborhoods (`/labelMap?regions=1,2,3`).
We had talked about centering the map on the filtered data and zooming into it, but I cut that out in the interest of time. Especially since I'm not sure how frequently we plan on using this. Plus I like having the context of the whole city!
Before
After

Adds region query param for LabelMap

---

app/views/validation.scala.html
conf/messages.en
conf/messages.es
conf/messages.nl
conf/messages.zh
public/javascripts/SVValidate/src/panorama/Panorama.js

Resolves #3096 
Added text in the comment box on the validation page as a nudge to include reasoning when selecting disagree.
Before:
After:
All text fits within textbox except for Dutch as shown:
1. Go to validation page and check the textbook

3096 - noting that validation comments are seen

---

public/javascripts/SVLabel/src/SVLabel/canvas/Canvas.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
public/javascripts/SVValidate/src/util/PanoProperties.js
public/javascripts/common/UtilitiesPanomarker.js

Fixes #1764 
Further work towards #2485 
This fixes a bug that cause labels to move slightly after placing them.
The issue was that there was a function where we were rounding the heading at pitch to an integer before calculating where it should be placed. Actually worse than that: we were just truncating the number to an integer using `parseInt()`. And since we restrict the pitch between 0 and -35, we were always treating the pitch like it was higher than it actually was (-12.99 truncated to -12), which is why labels always moved upwards. This is also more pronounced at higher zoom levels because of the smaller field of view; the same change in pitch had a bigger effect.
This also propagates to the `sv_image_x/y` values that we use for CV. These are changes by less than 100 pixels for …

Fixes bug where labels moved after placing them

---

conf/evolutions/default/181.sql
public/javascripts/SVLabel/src/SVLabel/label/Label.js

Resolves #3201 
Fixes a bug where labels weren't showing on the mini map because the lat lng estimation was broken. I broke when updating how we record the `pano_y` location for labels; I forgot that it's used when estimating lat/lngs! Easy fix, and I'm retroactively fixing labels from that past two days that were messed up using this PR.
Before
After

Fixes labels not showing on mini map

---

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js
public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js

Fixes #3208
Fixes the tutorial where annotations were in the wrong place, and placing labels correctly didn't move you forward!
When I updated the `pano_y` values to range from 0 to `pano_height` (instead of `-pano_height/2` to 0), I forgot to update that in the tutorial since all of that is hard-coded! Big apologies on my part, I really should be testing the tutorial before every push to prod :pray: 
Before
After

Fixes broken tutorial

---

app/views/serviceHoursInstructions.scala.html

Resolves #3215 
Adds a link to a training DOs and DONTs slide deck to the instructions for new volunteers who are earning service hours.
Before
After

Adds do and dont slides to service hours instructions

---

app/controllers/TaskController.scala
app/models/label/LabelTable.scala
public/javascripts/SVLabel/src/SVLabel/Tracker.js
public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVValidate/src/Tracker.js

Fixes #3222 
This should prevent a bug that happened when a user had multiple Explore pages open at the same time, where metadata for labels were being overwritten instead of new ones being created.
The issue: The front end keeps track of a "temporary label id", which should uniquely identify a label for each user. When loading the page, it's given a temp label id, and it increments it whenever a label is placed. The back end then uses the `user_id` and `temporary_label_id` to uniquely identify a label; this is how the back end knows whether you're submitting a new label or editing an old one. If you open the Explore page in two different locations, you could start adding labels with the same `temporary_label_id`. The back end would then think that you're just updating an old label; it …

Fixes a bug where labels had the wrong tags

---

conf/cityparams.conf
conf/evolutions/default/190.sql
public/javascripts/common/UtilitiesSidewalk.js
public/locales/de/audit.json
public/locales/de/common.json
public/locales/en-NZ/audit.json
public/locales/en-NZ/common.json
public/locales/en/audit.json
public/locales/en/common.json
public/locales/es/audit.json
public/locales/es/common.json
public/locales/nl/audit.json
public/locales/nl/common.json
public/locales/zh/audit.json
public/locales/zh/common.json

Resolves #3258 
Renames "pedestrian arcade" to "covered walkway", renames "painted sidewalk" to "pedestrian lane marking", and moves those tags from the Obstacle and SurfaceProblem label types to the NoSidewalk label type. I also changed the keyboard shortcuts to work well with our translations, which is more of an option for the NoSidewalk label type given how few tags it has.
Before/After No Sidewalk
Before/After Surface Problem
Before/After Obstacle

Updates Taiwan tags: covered walkway & pedestrian lane marking

---

app/views/developer.scala.html
public/javascripts/developer.js

Resolves #3236 
Adds lat/lngs that encompass the entire city to the API page. I included some text explaining that this is to get data for the entire city, and that it may take a long time to run.
Before
After

Adds full city lat/lngs to the API page

---

app/views/index.scala.html
app/views/navbar.scala.html
conf/messages.de
conf/messages.en
conf/messages.es
conf/messages.nl
conf/messages.zh

Resolves #3152 
Reorganizes items in the navbar and adds RouteBuilder to it. Full list of changes:
1. Start Exploring renamed to Explore
2. Start Validating renamed to Validate
3. Sidewalk API renamed to API and moved out of the Data menu
4. Data menu renamed to Tools
5. RouteBuilder added to the Tools menu
6. I also reorganized the items in the Tools menu to put the ones that we use the most higher up.
Before
After

Reorganizes navbar, adds RouteBuilder to navbar

---

build.sbt
conf/evolutions/default/192.sql
conf/evolutions/default/193.sql
public/javascripts/SVValidate/src/mission/MissionContainer.js

Fixes #3271 
Fixed a bug that I caused after #3262 that prevented users from moving on after their first Validate mission.
It seems that one line of code I was using locally while testing that PR was never included, which caused the catastrophic bug! Easy one line change.

Fixes bug preventing users from doing a 2nd Validate mission

---

app/controllers/AdminController.scala
app/controllers/ProjectSidewalkAPIController.scala
app/models/attribute/GlobalAttributeTable.scala
app/models/label/LabelTable.scala
public/javascripts/Admin/src/Admin.js

(hopefully) fixes #3224 
This PR improves the performance of two of our biggest API calls: /adminapi/labels/cvMetadata and /attributesWithLabels. Instead of trying to convert all of the labels to JSON in one go like we had before, which forces us to load everything into memory, we are now writing 10k labels at a time to JSON files. We can then transfer the JSON files with much less memory.
I tested this out on my dev environment by artificially lowering the amount of memory available to Java so that I could test with smaller datasets. This seems to be solving the issue. Will only know for sure once it is on production.
Additionally, I only did this with two API endpoints to start. If we determine that the method is working, it's pretty easy to add that workflow to other endpoints!
In the …

Hopefully preventing server crashes from running out of memory

---

app/views/navbar.scala.html
conf/cityparams.conf

Resolves #3277 
Adds initial configs for New Taipei and Keelung servers. I copied a bunch of map centering params over from the Taipei server since we haven't settled on which neighborhoods to deploy in quite yet.
I also added in a bit of hacky code that forces all the Taiwan servers to show up in the city drop down list for any other Taiwan server. We've talked about having a separate Taiwan landing page, but this should do for day 1!

Adds configs for New Taipei and Keelung servers

---

conf/cityparams.conf

Resolves #3305 
The lat/lngs for all of the maps (except for those on the API page) have been updated to be centered on the revealed neighborhoods in Taiwan (Taipei, New Taipei, and Keelung servers).

Maps in Taiwan now pointing to revealed villages

---

app/models/attribute/ConfigTable.scala
app/views/index.scala.html
conf/cityparams.conf

Here's a quick look!
This also revealed some bugs from our recent PR to set up the `config` table (#3320), so this was a helpful debugging session before pushing to prod :)

Adds configs for new Burnaby server

---

app/controllers/ConfigController.scala
app/models/attribute/ConfigTable.scala

Resolves #3322 
Cleaned up the config table with two generic classes for data, an ApiField and LatLngPair case class. Removed the many getter methods. Refactored ConfigController to reduce queries.

config table fix

---

conf/application.conf

Resolves #3316 
Updates the following database connection pooler configs, with the goals of reducing the number of idle connections we hold on to, and reducing the likelihood that a server fails to ever connect to a database after an auto-deploy.
```
db.default.idleMaxAge=2 minute  # default is 10 minutes
db.default.acquireRetryDelay=5 second  # default is 1 second
db.default.acquireRetryAttempts=42  # default is 10
db.default.minConnectionsPerPartition=4  # default is 5
```
1. Make sure the server is running and you've loaded a webpage
2. SSH into db container: `make ssh target=db`
3. Connect to a db: `psql -U sidewalk -d sidewalk`
4. Run this command to list open connections
```
SELECT datname, SUM(numbackends) AS "num_conn"
FROM pg_stat_database
GROUP BY datname
HAVING SUM(numbackends) …
```

Update DB connection pooler config

---

app/controllers/AdminController.scala
app/controllers/ProjectSidewalkAPIController.scala

Resolves #3334
Fixes an issue where a comma was being missed every 10k labels in the `/v2/access/attributes`, `/v2/access/attributesWithLabels`, and `/adminapi/labels/cvMetadata` APIs. In #3276 I switched us to adding 10k labels at a time to a JSON file to prevent the server from running out of heap space, but I forgot to include a comma between every 10k :facepalm: 
I tested on a database that had 35k labels on my local dev env and tried each of the three API endpoints. I used [this site](https://codebeautify.org/jsonvalidator#) to validate the JSON.

Fixes missing commas in JSON APIs

---

public/javascripts/SVLabel/src/SVLabel/PredictionModel.js

Adds some randomized tips to the prediction model suggested mistakes UI.

Adds randomized tips to Prediction Model UI

---

app/views/explore.scala.html
conf/messages.de
conf/messages.en
conf/messages.es
conf/messages.nl
conf/messages.zh
public/javascripts/SVLabel/css/svl-status.css
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/status/StatusFieldMission.js
public/locales/de/audit.json
public/locales/en/audit.json
public/locales/es/audit.json
public/locales/nl/audit.json
public/locales/zh/audit.json

Partial resolution to #3272 
Adds the current Route ID in the Explore page sidebar if you're on a user-created route. UI looks the same if you're doing a normal mission.
On a route
Not on a route

Adds route ID to the Explore sidebar

---

conf/application.conf

Resolves #3328 
Our email sender is rebranding from "sendinblue" to "brevo", so we needed to update our smtp relay address accordingly. I was actually not able to test this, because pw reset emails still do not work in our dev environment or test servers (#3124). But the change is very straightforward, so I'm not expecting an issue. I'll test after pushing to prod later today to make sure it worked!

Updates email SMTP relay address

---

public/javascripts/SVLabel/src/SVLabel/modal/ModalMissionComplete.js
public/locales/de/audit.json
public/locales/de/common.json
public/locales/en/audit.json
public/locales/es/audit.json
public/locales/nl/audit.json
public/locales/zh-TW/audit.json

Resolves (partially) #3351 
Updates some German translations so that they fit better on the mission complete map on the Explore page. Also added translations in all languages for the mission complete titles for completing a route or a neighborhood.
#3351 Also asks us to add a new tag in Zurich. I'm going to do that in a separate PR so that I have an example to give to interns for how we add new tags that doesn't have other things mixed in to the PR.
Before
After

German translation fixes on Explore mission complete

---

conf/evolutions/default/198.sql
public/javascripts/common/UtilitiesSidewalk.js
public/locales/de/audit.json
public/locales/de/common.json
public/locales/en/audit.json
public/locales/en/common.json
public/locales/es/audit.json
public/locales/es/common.json
public/locales/nl/audit.json
public/locales/nl/common.json
public/locales/zh-TW/audit.json
public/locales/zh-TW/common.json

Resolves #3351 
Adds "outdoor dining area" tag in Zurich only. Unfortunately, we have run out of any sensible keyboard shortcuts for the tags, so this one just has the letter Q :+1: 
Before
After

3351 add outdoor dining area tag

---

conf/evolutions/default/199.sql
public/javascripts/common/UtilitiesSidewalk.js
public/locales/de/audit.json
public/locales/de/common.json
public/locales/en/audit.json
public/locales/en/common.json
public/locales/es/audit.json
public/locales/es/common.json
public/locales/nl/audit.json
public/locales/nl/common.json
public/locales/zh-TW/audit.json
public/locales/zh-TW/common.json

Resolves #3363 
Adds a new tag called "parallel lines" (working title) to the Curb Ramp label type for the Burnaby server only. Screenshot below of the thing we are trying to tag with this label type. It's a type of tactile warning.
Before
After

Adds "parallel lines" tag for Curb Ramps in Burnaby

---

README.md

No issue associated with commit.
WSL's vm uses tons of memory in the background, sometimes upwards of 1500-2000 mb of memory. When not working on Project Sidewalk, shutting down WSL and Docker greatly speeds up your computer by not eating up memory from your computer unnecessarily. 
For those that don't know much about WSL or Docker, this can be confusing since nowhere explicitly mentions this drawback and how to solve it. Adding this to the README brings the issue to everyone's attention as they're onboarding!

Updated README to include WSL shutdown instructions

---

public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/SVValidate/src/label/Label.js
public/javascripts/SVValidate/src/panorama/Panorama.js
public/javascripts/SVValidate/src/util/PanoProperties.js
public/javascripts/SVValidate/src/zoom/PinchZoomDetector.js
public/javascripts/SVValidate/src/zoom/ZoomControl.js
public/javascripts/common/Panomarker.js

Fixes #3309 
Fixes some zooming bugs on the Validate page. I believe that Google must have changed the underlying API at some point without documenting it... The crux of the issue is that there is a `getZoom()` function for the `StreetViewService` object that can return the wrong zoom level if the zoom level was set using the `setPov()` function. However the `getPov()` function always returns the correct zoom level, so I've replaced all uses of `getZoom()` with `getPov().zoom`!

Fixing zooming bugs on Validate

---

app/controllers/ProjectSidewalkAPIController.scala
app/models/attribute/GlobalAttributeTable.scala

Resolves #3390
Neighborhood names containing commas would break the CSV file formatting, acting as an unintended delimiter. This PR adds double quotes around each instance of neighborhood names being referenced in CSV files, namely in these API calls:
- /v2/access/attributes
- /v2/access/attributesWithLabels
- /v2/access/score/neighborhoods
Before:
After:
1. Check the Label Map to find the coordinates of an area populated with labels. Choose a min/max lat and min/max long.
2. Use this URL to fetch the csv file from the API: 
- `localhost:9000/v2/access/attributes?lat1=<x1>&lng1=<y1>&lat2=<x2>&lng2=<y2>&filetype=csv`
- `localhost:9000/v2/access/attributesWithLabels?lat1=<x1>&lng1=<y1>&lat2=<x2>&lng2=<y2>&filetype=csv`
- `localhost:9000/v2/access/score/neighborhoods?lat1=<x1>&lng1=<y1>&lat2= …

Fixed neighborhood name commas breaking csv formatting

---

public/javascripts/common/MissionStartTutorial.js

Resolves #3401 
Fixes a bug that broke the "Validate more labels" button when the only labels left to validate are No Sidewalk labels.
The issue is that in the Mission Start Tutorial code, "NoSidewalk" was written as "NoSideWalk". Not sure how I missed that when testing the Mission Start Tutorial when it was first added, but this bug has been there from the beginning!
Since we only show No Sidewalk labels if all our main label types have already been fully validated by a user, this is only showing up on servers with very little data (like our new Walla Walla deployment).

Fixes bug preventing validating NoSidewalk labels

---

app/controllers/ProjectSidewalkAPIController.scala
app/formats/json/APIFormats.scala
app/models/label/LabelTable.scala
conf/cityparams.conf

Resolves #3375 
Launch date of a city is currently not available. To show this information, the date of the first label in each city was found and added to the city params config file. The info is then drawn from the config file to the API call.
Before:
No info displayed for city launch date.
After:
CSV format:
JSON format:
1. Use the `/v2/overallStats` and `/v2/overallStats?filetype=csv` API calls.
2. Check that the `launch_date`/Launch Date fields are displayed correctly.

Added launch date to overallStats API call

---

public/javascripts/SVValidate/src/modal/ModalNoNewMission.js
public/locales/de/validate.json
public/locales/en/validate.json
public/locales/es/validate.json
public/locales/nl/validate.json
public/locales/zh-TW/validate.json

Resolves #3126
Fixes broken "no more validation missions left" screen when there are no more labels to validate. Adds different functionality for mobile, as well as translations.
Before:
After:
1. Force else case in getDataForValidationPages() in ValidationController.scala by temporarily editing if statement to 'if (false)'
2. Navigate to Validate webpage
3. Use Dev Tools to test mobile version

Fixes no new missions

---

public/javascripts/SVValidate/src/label/Label.js

Resolves #3400
Fixes a bug where Validate wouldn't submit the validation when adding a comment. This _was_ my fault from a previous PR; I forgot to test validations with comments!

Fixes Validate not working when adding a comment

---

app/controllers/AdminController.scala
app/controllers/UserProfileController.scala
app/formats/AdminUpdateSubmissionFormats.scala
app/models/daos/slick/UserDAOSlick.scala
app/models/label/LabelValidationTable.scala
app/models/user/UserOrgTable.scala
app/views/admin/index.scala.html
conf/routes
public/javascripts/Admin/src/Admin.js
public/stylesheets/admin.css

Resolves #3398 
Adds an Org column to the Admin User table. Also removes the audit_count, mission_count, % Own Labels Notsure, and % Own Labels Disagree columns to make space. I also decreased the font size from 12px to 11px to fit even more on screen.
The org column functions the same way as the role column, so we can now set users' org from the Admin page! I included the ability to fully remove a user's org as well.
Before
After

Adds Org column to Admin User table

---

app/controllers/ProjectSidewalkAPIController.scala

Resolves #2988
Before, the computation for the access streets score was done as follows:
```
for every street s:
for every clustered attribute c:
create a jts Point object from the c's latitude and longitude, Point(c)
if the Point(c) is within 10 meters of s:
increase cluster count for s
```
which duplicated the Point creation step for all labels on every street. The computation was modified to follow this scheme:
```
for every clustered attribute c:
create a jts Point object from the c's latitude and longitude, Point(c)
for every street s:
for every Point(c):
if Point(c) is within 10 meters of s:
increase cluster count for s
```
to reduce the amount of creations of Point objects to just one per label.
1. Go to the API page (http://localhost:9000/api) and use the drop down in the "Access …

Implemented performance improvement to access scores API call.

---

package.json

A previous change upped the JVM memory allocation to 1536MB to temporarily mitigate issues with API calls.  However, these issues were only being encountered on the largest of the city sites (Seattle), while the change upped the memory allocation for all sites, both in test and prod.  We are currently in the process of moving all of the test and prod servers to a single host, and with 24 of the 40 sites moved, it is starting to bump up against its total RAM, and use swap.
This change allows us to configure JVM memory allocations for individual server instances.  Thus, we can raise the allocation only for Seattle, and save ~20GB of resident memory, which will help keep us from heavily using swap as we move the rest of the sites over.

Allow sbt -mem arg to be configured in start-no-docker

---

app/controllers/ProjectSidewalkAPIController.scala
app/formats/json/APIFormats.scala
app/models/label/LabelTable.scala

Resolves #3430 
Takes the 100 most recent labels in the city, takes the average of those dates, and adds it to the Overall Stats API. 
Field is called "Recent Labels Average Timestamp" in csv format for readability, but "avg_timestamp_last_100_labels" for detail in JSON format and the case class fields.
1. Call the OverallStats API (http://localhost:9000/v2/overallStats)
2. Check that the "Recent Labels Average Timestamp"/"avg_timestamp_last_100_labels" field and ensure that the date makes sense with the current labels in the database.
3. Check all filetype formats (CSV, JSON) to make sure field comes through on all formats.

Added recent labels average timestamp to overall stats API

---

app/controllers/TaskController.scala
app/controllers/ValidationTaskController.scala
app/formats/json/TaskSubmissionFormats.scala
app/formats/json/ValidationTaskSubmissionFormats.scala
app/models/audit/AuditTaskEnvironmentTable.scala
app/models/validation/ValidationTaskEnvironmentTable.scala
app/views/main.scala.html
app/views/missionStartTutorial.scala.html
conf/evolutions/default/209.sql
public/javascripts/SVLabel/css/svl.css
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/data/Form.js
public/javascripts/SVValidate/css/svv.css
public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/data/Form.js
public/javascripts/SVValidate/src/panorama/GSVOverlay.js
public/javascripts/common/GSVInfoPopover.js
public/javascripts/common/Utilities.js
public/stylesheets/common/missionStartTutorial.css
public/stylesheets/main.css

#303 is the issue we're working on here. This is a temporary fix because it doesn't work for Firefox.
Adds automatic zoom on the Explore and Validate pages using the CSS zoom property instead of browser zoom. This doesn't work on Firefox. I've tested that it works on Chrome and Safari thus far, so that's all I've enabled. I'll test it on Edge in the next couple of weeks and enable it there if it works well too. Everything below the navbar gets zoomed.
I also removed the footers on both of those pages, which makes the app take up basically the entire screen with no scrolling ever happening on the page. Easy enough to add the footers back in, but I really like how it looks/feels with no scrolling.
Before (80% zoom)
After (80% zoom)

Adds automatic CSS zoom for Explore/Validate pages

---

app/models/utils/Configs.scala
app/views/leaderboard.scala.html
conf/messages.de
conf/messages.en
conf/messages.en-NZ
conf/messages.es
conf/messages.nl
conf/messages.zh-TW

Resolves labeling guide links point to different places https://github.com/ProjectSidewalk/SidewalkWebpage/issues/3420
This fix was made by writing a parameter into the text for the links to the labeling guide on the leaderboard, and inserting the proper link in as the argument.
The following screenshots are for the taiwan country id: 
BEFORE: We go from the first screen to the second after clicking the labeling guide link:
to
AFTER: This is the new flow (for taiwan):
to

3420 leaderboard lableing guide link update

---

public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js

Resolves #3341: navigation system (arrows) spinning at the end of custom routes
In this PR, I fixed the issue of the navigation system spinning randomly at the end of a custom route. I found that the cause of the error was the fact that the nextTask is null at the end of a custom route, which was causing various errors on the console and throwing everything out of whack. So, to combat this, before switching to the next task, I simply added and if statement to check if it was null, and only allowed moving to the next task in the case that it is not null. In the null case, nothing happens, which I think is appropriate since the user is prompted to click to finish their route anyway.
Before:
After:
Watching this video may help to show how to recreate the error (you can see it in the final …

Added extra null checking for next mission to solve navigation system error for custom routes

---

app/views/developer.scala.html
app/views/labelingGuideCurbRamps.scala.html
app/views/labelingGuideNoSidewalk.scala.html
app/views/labelingGuideObstacles.scala.html
app/views/labelingGuideOcclusion.scala.html
app/views/labelingGuideSurfaceProblems.scala.html
public/stylesheets/labelingGuide.css
public/stylesheets/main.css

**Resolves #3299** 
There were no anchor links for each API subsection before the addition of these anchor links. Additionally, CSS was added so that the anchor links directed users to the accurate portion of the subsection.
**Before Video (File Too Large to Upload Directly)**
https://drive.google.com/file/d/1pqih7p6HPmNFettPXhMOmSfsnCSv26SF/view?usp=sharing
**After Video (File Too Large to Upload Directly)**
https://drive.google.com/file/d/1a_ejcy8gjrGQJc21cqi_rNhqmZU0VbqB/view?usp=sharing
**Things to check before submitting the PR**
**Remaining checklist items did not apply to this pull request.**

Adds anchor links to API subsections

---

app/controllers/ProjectSidewalkAPIController.scala
app/controllers/helper/ShapefilesCreatorHelper.java
app/models/attribute/GlobalAttributeTable.scala
app/models/street/OsmWayStreetEdgeTable.scala
app/models/street/StreetEdgeTable.scala
conf/evolutions/default/211.sql

Resolves #3413
Shapefile format doesn't allow integers longer than 9 digits 
Fixed the bug!
Also changed the data type for "osmWayId" to BIGINT as INT data type does not take more than 9 digits.
Added Evolutions file for Database migration.

#3413 Shapefile format doesn't allow integers longer than 9 digits 

---

public/javascripts/SVLabel/css/svl-onboarding.css
public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js
public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js
public/stylesheets/animate.css

Resolves #3378
In this PR I align the arrow of the text box that prompts the user to zoom in in the tutorial to the center of the zoom in button. I did this by setting the top of the box to be where the center should be, and adding another parameter in OnboardingStates that translated up the box by 50% of it's height. I also had to replace the fadeInDown/Left/Right animation settings for each arrowed text box with a simple fadeIn animation, since the transformation component of the fadeInDown/Left/Right was overwriting the base transform needed to position each box properly.
Before: 
After:
1. Choose a language
2. Step through the tutorial until you get to the point where the text box pops up telling the user to zoom in and observe if it points to the center of the button.

Updating the vertical position of the zoom-in text box to have its arrow point to the center of the zoom-in button

---

app/controllers/ApplicationController.scala
app/controllers/GalleryController.scala
app/formats/json/GalleryFormats.scala
app/models/label/LabelTable.scala
app/views/gallery.scala.html
app/views/navbar.scala.html
conf/routes
public/javascripts/Gallery/src/cards/CardContainer.js
public/javascripts/Gallery/src/data/Tracker.js
public/javascripts/Gallery/src/filter/CardFilter.js

Partially resolves #3206 
Adds a neighborhood filter to Gallery. I didn't add any UI, but I've added it as a URL parameter that anyone can use. It should look like `neighborhoods=<comma-separated list of region IDs>`.  For example, in Newberg, the Oak Knoll neighborhood's region ID is 6, so you could search for all labels in that neighborhood using:
https://sidewalk-newberg.cs.washington.edu/gallery?neighborhoods=6.
If you wanted to search in both Oak Knoll and Jaquith Park, you could use:
https://sidewalk-newberg.cs.washington.edu/gallery?neighborhoods=4,6.
You can find the region ID using the /v2/access/score/neighborhoods API.
In the future, we will add a UI to select neighborhoods for filtering. But we are setting up just the URL parameters for internal use, and to send direct links …

Adds neighborhood filter URL parameter to Gallery

---

app/controllers/AdminController.scala
app/views/admin/label.scala.html
conf/routes
public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/Admin/src/Admin.LabelSearch.js
public/javascripts/Admin/src/Admin.js

Resolves #3469 
Adds a page that will show you a label if you include the label ID in the URL. I also included a search box so it's basically a copy of the Label Search tab on the Admin page that doesn't require the whole Admin page to use :) And it defaults to showing the label in the URL.
I used the url `/admin/label/<label-id>`.
Though it can be viewed even if you aren't an admin! There are just a few rows in the table that only show up for admins.

Adds a dedicated page to view a label and search for them

---

app/controllers/ImageController.scala

Resolves #3467 
To avoid saving images of different resolutions based on the user's browser zoom level, we are resizing the images on the server side right before saving it. This way we will have uniform size for all the crops saved. 
1. Change the browser zoom to more than 100%. Place a label. Make sure that the crop saved is of size 1440x960.
2. Change the browser zoom to less than 100%. Place a label. Make sure that the crop saved is of size 1440x960.

Resizing crops before saving.

---

public/javascripts/SVLabel/src/SVLabel/label/Label.js

Resolves #3508
Fixes the issue where &shy; was showing when hovering over most labels in German. Solved it by filtering that text out of translations when displaying in this location. It works differently here bc we're drawing the text instead of it being in HTML.
Before
After

Fixes &shy; showing in German when hovering over label

---

app/controllers/AdminController.scala
app/controllers/ValidationController.scala
app/controllers/ValidationTaskController.scala
app/controllers/helper/ValidateHelper.scala
app/formats/json/LabelFormat.scala
app/models/label/LabelTable.scala
app/views/mobileValidate.scala.html
app/views/validation.scala.html
public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/SVValidate/mobile/mobileValidate.js
public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/status/StatusField.js

Resolves #2530
Fixes #3513 
This PR ends up doing a few related things since they came up while I was already working on this...
1. We now prioritize which label type to choose for a Validate mission based on need. Each of our 6 primary label types have at least a 3% chance of being selected (if there are any such labels left for the user to validate). The remaining probability of being chosen is split up proportionally based no the number of labels remaining of that label type that either has no validations or needs a tie breaking vote. As before, we only assign No Sidewalk missions if there is nothing available for the other label types.
As an example, I tested on my Seattle db dump, and the probabilities for the various label types were: 48% Curb Ramp, 15% Missing Curb Ramp, 9% …

Validate prioritizes label types based on need, other Validate fixes

---

public/javascripts/SVLabel/src/SVLabel/canvas/Canvas.js

Fixes #3506 
Fixes naming of our crops from .jpg.png to .png. They were being successfully being saved as PNG files, just not without the correct filename. Once this is up on servers, we'll just need to run this bash command to fix all existing files:
```
for f in *.jpg.png; do
mv "$f" "${f%.jpg.png}.png"
done
```

Crops now saved as .png instead of .jpg.png

---

app/controllers/ImageController.scala
public/javascripts/SVLabel/src/SVLabel/canvas/Canvas.js

Resolves #3502 
Crops will now be split into subdirectories based on their city and label type. Instead of
`crop_temp_<city-id>_<user-id>_<temp-label-id>_<label-type>.png`, they will be stored as
`<city-id>/<label-type>/crop_temp_<user-id>_<temp-label-id>.png`.
Once this is on the servers, I will just need to run the following script to update all past data:
```
#!/bin/bash
shopt -s nullglob
for city in seattle-wa columbus-oh cdmx spgg pittsburgh-pa newberg-or chicago-il amsterdam la-piedad oradell-nj validation-study zurich taipei new-taipei-tw keelung-tw auckland cuenca crowdstudy burnaby teaneck-nj walla-walla-wa; do
for label_type in CurbRamp NoCurbRamp Obstacle SurfaceProblem NoSidewalk Crosswalk Signal Occlusion Other; do
mkdir -p "${city}/${label_type}"
for file in …
```

Adds city subdirectories for crops

---

app/views/index.scala.html
app/views/main.scala.html
app/views/navbar.scala.html
conf/messages.de
conf/messages.en
conf/messages.es
conf/messages.nl
conf/messages.zh-TW
public/javascripts/homepage.js
public/stylesheets/homepage.css
public/stylesheets/main.css

Resolves #3523 
Adds links to our new https://accessiblecommunities.org/ website in the navbar, footer, and landing page!
1. About Us in footer now link [here](https://accessiblecommunities.org/about/)
2. Replaced the "We are also in: <list of cities>" with "[Click here](https://accessiblecommunities.org/use-project-sidewalk/) to learn about deploying Project Sidewalk in your city."
3. In the drop down list of cities in the navbar, added "[Your city here](https://accessiblecommunities.org/use-project-sidewalk/)" as an option. I don't love how the styling turned out, but it will do for now!

adds links to new Accessible Communities website

---

conf/evolutions/default/223.sql
public/javascripts/common/UtilitiesSidewalk.js
public/locales/de/audit.json
public/locales/de/common.json
public/locales/en/audit.json
public/locales/en/common.json
public/locales/es/audit.json
public/locales/es/common.json
public/locales/nl/audit.json
public/locales/nl/common.json
public/locales/zh-TW/audit.json
public/locales/zh-TW/common.json

Resolves #3518 
Renames "pooled water" tag to "debris / pooled water". Made sure to update in all languages.
Before
After

Renames "pooled water" tag to "debris / pooled water"

---

app/models/daos/slick/UserDAOSlick.scala

Resolves #3419 
In this PR, I edited the UserDAOSlick file in the backend to send anonymous users that have validated data to the admin dashboard frontend, which it did not do previously (only anon users that had done labels and non-anonymous users were sent). This took adding one subquery to the usersMinusAnonUsersWithNoLabels method to include those new anonymous users. 
1. Make a new user
2. Go into the database and change their role to id = 6 (anon)
3. log into an admin user and go to the admin dashboard. Here you can check that that new user you just made does NOT come up.
4. log back into the new user you made & do one validation mission
5. log back into the admin user again and go to the admin dashboard. This time, the new user we just made should be visible in the dashboard!

Including Anon Users With Validations in Admin Dashboard

---

app/views/labelMap.scala.html
public/javascripts/Admin/src/Admin.GSVLabelView.js

Resolves #3542
I removed the modal clean up code in the labelmap file and I added a check when resetting the panorama in the gsv label view file. When I removed the _resetModal call in the showLabel method the code works fine for all four of the locations(labelMap, admin dashboard, contributions, adminmap). However, I found a bug on the contributions tab which occurs when a gsv is deleted by google. 
The steps to reproduce this bug(with screenshots below), is to go to the admin contributions tab and go to the very last page and click on a gsv that is deleted(NoCurbRamp severity 3 on the last page), then click on another gsv that is not deleted(any of the top curb ramps) and these should log a 404 error to the console. After I click on a few other gsv's that are not deleted the issue fixes …

Added check for 404 bug, and removed labelmap breaking code

---

public/stylesheets/main.css

Resolves #3524 
The problem was that the navbar button turned grey after clicking out of it. The only way to get it back to the original white color was to click elsewhere on the screen. The same thing applies to the mobile view except that the color stays yellow instead of grey.
Image of the grey background
Image of the white background
Image of the yellow background
Image of the white background
1. Click the main navbar "Tools" or "City" dropdown button to open menu
2. Click it again to close the menu (color now switches back to white)

Issue 3524 Fix Dropdown Color

---

public/javascripts/PSMap/AddNeighborhoodsToMap.js
public/stylesheets/main.css

Resolves #3495 
For many neighborhoods, the value severityVal was undefined. This variable is passed into getColorFromGradient and is supposed to be an int used to determine the color in a loop. Since this variable was undefined, the loop didn't work and there was no resulting color to load. This fix sets severityVal to 100 (the default value) whenever it is undefined.  
1. Load the results map before and after the fix.

3495 results map

---

app/controllers/ApplicationController.scala
app/controllers/AuditController.scala
app/controllers/ValidationController.scala
app/models/utils/Configs.scala
app/views/explore.scala.html
app/views/gallery.scala.html
app/views/mobileValidate.scala.html
app/views/validation.scala.html
public/javascripts/Gallery/src/Main.js
public/javascripts/Gallery/src/modal/Modal.js
public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVLabel/src/SVLabel/onboarding/InitialMissionInstruction.js
public/javascripts/SVValidate/src/Main.js
public/javascripts/common/GSVInfoPopover.js
public/locales/de/common.json
public/locales/en/common.json
public/locales/es/common.json
public/locales/nl/common.json
public/locales/zh-TW/common.json

Resolves #3568 
Adds the city name and the GSV URL to the data when copied to the clipboard on the GSV info button. This applies to the button as shown on Gallery, Validate, and Explore.
Before
```
Latitude: 40.9007798662525°
Longitude: -74.02539685791724°
Panorama ID: CCNJnMDAiD2D_uHkgVGFWQ
Street ID: 1751
Region ID: 12
Label ID: 5790
```
After:
```
Latitude: 40.9007798662525°
Longitude: -74.02539685791724°
Panorama ID: CCNJnMDAiD2D_uHkgVGFWQ
Street ID: 1751
Region ID: 12
City: Teaneck, NJ
GSV URL: https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=40.9007798662525%2C-74.02539685791724&heading=94.1875&pitch=-23
Label ID: 5790
```

Adds city and GSV URL to image info button when copied to clipboard

---

public/javascripts/Admin/src/Admin.GSVLabelView.js
public/javascripts/Admin/src/Admin.Panorama.js

Resolves #3564
Added method to clear labels extra labels when showing a new label pop up. 
1.

Removing Extra labels on LabelMap panoramas

---

app/models/label/LabelTable.scala

Fixes #3588 
Fixes a bug in Gallery where the query to find labels would fail and the page would get stuck on the loading GIF forever.

Fixes bug when querying for more labels in Gallery

---

public/javascripts/SVValidate/src/keyboard/Keyboard.js

Resolves #3592 
Fixes broken keyboard shortcuts in Validate (not the new one) when using the old A/D keys to validate.

Fixes keyboard shortcuts in Validate

---

public/javascripts/SVValidate/src/keyboard/Keyboard.js
public/javascripts/SVValidate/src/menu/RightMenu.js

Resolves #3596
Adds a keyboard shortcut (S) to submit a validation to reduce mouse travel on new Validate UI.

Adds S keyboard shortcut to submit validation in new UI

---

app/views/newValidateBeta.scala.html
public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/keyboard/Keyboard.js
public/javascripts/SVValidate/src/label/Label.js
public/javascripts/SVValidate/src/menu/RightMenu.js
public/locales/en/validate.json
public/stylesheets/newValidateBeta.css

Resolves #3581 
Adds buttons with 'Unsure' reasons to the new Validate page. We can and should iterate on the options that I've added in for now. The options came from Jon and I brainstorming, and looking through reasons that users have manually entered during previous Unsure validations. I'm starting with the following showing up for all label types:
* Need a better image
* This has an associated tooltip with the text: "This could be because the image is blurry, what's being labeled is too far away, or a different angle is needed"
* Label placement looks incorrect
And then a third option for a few label types:
* Curb Ramp: Alley or parking lot entrance
* Missing Curb Ramp: Not sure if a curb ramp is required
* Obstacle: Not sure if sidewalk is wide enough to avoid the obstacle
* Surface …

Adds 'unsure' reasons buttons to new Validate beta

---

app/views/newValidateBeta.scala.html
public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/keyboard/Keyboard.js
public/javascripts/SVValidate/src/label/Label.js
public/javascripts/SVValidate/src/menu/RightMenu.js
public/stylesheets/newValidateBeta.css

Resolves #3595
In the new Validate beta, adds an optional comment box in the "agree" section.
Before
After

Adds optional comment box for agree validations

---

public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVValidate/src/Main.js
public/javascripts/common/Utilities.js

#3626 (HOTFIX)
Removes automatic CSS zoom from Explore/Validate on Chrome. Remains enabled on Safari for now.
The way that CSS zoom works has been changed in the latest version of Chrome, breaking our Explore/Validate pages. I have made a bit of progress on getting it working again, but it needs tweaking and then very thorough testing. Given that the Explore page will be essentially broken as users update their browsers, I think it's best to just remove the automatic zoom from Chrome users until we have a fix ready.

CSS zoom disabled on Chrome temporarily

---

public/javascripts/Gallery/src/cards/CardContainer.js

Resolves #3621
In gallery queries with not enough entries to form more than one page, the gallery system was falsely enabling the next label button and next page button. They should be disabled because there is no next page, and no next label at the end. The issue was that the system did not check if there was enough labels until `updateCardsNewPage` was called. This was fixed by adding a check in the `_init` function.
Before:
After:
1. Find a query that doesn't have enough entries to make a page
2. Verify that the next page and next label (for the last label on the first page) buttons are disabled.

Fix issue in gallery when there's not enough labels to display more than 1 page

---

public/javascripts/Gallery/css/cards.css
public/javascripts/Gallery/css/tags.css

Resolves #3464
Previously, on the gallery page, long tags were not limited and could overflow out of the card container. Adding CSS to limit the tags to only fill up the rest of the flexbox space fixed this.
**Before**
**After**
1. Go to the gallery page
2. Find labels with long tag names
3. Confirm that they're being limited properly

Properly truncate long gallery tags in flexbox

---

public/javascripts/Gallery/css/tags.css

Resolves #3636
Short gallery tags were not being displayed properly, and they were taking up too much space. This was fixed by removing the `flex: 1` css property which was never necessary in the first place (I accidently added this in my first PR which fixed long gallery tags). I tested both short and long gallery tags this time.
**Before**
**After**
1. Go to gallery
2. Find a label with short tags
3. Verify that the short tag is not filling up the whole space, as seen in the before screenshot

Prevent short gallery tags from taking up too much space

---

app/formats/json/APIFormats.scala

Resolves #3630 
An issue where double quotes in the field description of attributes with labels were not properly escaped, this causes CSV rows to break/extra rows. To solve this I added an escape sequence to add another quote following each double quote. This was suggested by [RFC-4180](https://www.ietf.org/rfc/rfc4180.txt), to test this I used Valentina studio to reproduce the bug by adding a " in a description and then compared the code before and after. 
1.

Added an escape sequence to add double quotes after each double quote in the description field of AttributesWithLabels CSV files. 

---

app/models/utils/Configs.scala
conf/cityparams.conf
conf/evolutions/default/244.sql
conf/messages
conf/messages.de
conf/messages.es
conf/messages.nl
conf/messages.zh-TW

Resolves #3644 
Resolves #3648 
Adds configs for the new LA and Mendota, IL servers. I also fixed a bug where city/state/country names weren't being translated correctly due to a caching issue.
I also added a database evolution to fix the `mission_type_id` in our db. This was an issue because of how we wrote our evolutions in the past. It had no impact on any of the code running on our servers, but it would cause problems when trying to manually run queries on the dbs because IDs weren't consistent between cities.

Adds configs for LA & Mendota, fixes internationalization bug in navbar

---

app/controllers/LabelController.scala
app/controllers/TaskController.scala
app/formats/json/LabelFormat.scala
app/models/label/LabelTable.scala
app/models/label/TagTable.scala
conf/evolutions/default/245.sql
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
public/javascripts/SVValidate/src/label/Label.js
public/javascripts/SVValidate/src/menu/RightMenu.js

Fixes #3635 
Fixes a bug where conflicting tags (like "no alternate route" and "alternate route present") could both be added to a label through the new Validate page. Some more specifics:
* I added a new `mutually_exclusive_with` column to the`tag` table, so that these mutual exclusivity relationships are recorded in the db. This helps us deal with the more programmatically, and I'm hoping that it makes it easier to remember to address them when this comes up again.
* I'm using this new column to check for mutual exclusivity before inserting/updating on the `label` or `label_history` table. If we fail to prevent this issue on the front-end, we'll now log a warning on the back-end and remove both of the mutually exclusive tags before inserting/updating. This way we'll never have …

Prevent conflicting tags being added in new Validate

---

public/javascripts/SVValidate/src/menu/RightMenu.js

Resolves #3610 
Fixes the bug where you couldn't remove tags in the New Validate Beta unless your language was set to English. Instead of using the text in the HTML elem to determine which tag to remove, I added a tag-id data attribute that is the same across languages.

Fixes removing tags in new Validate when not using English

---

app/views/newValidateBeta.scala.html
public/javascripts/SVValidate/src/label/LabelVisibilityControl.js
public/stylesheets/newValidateBeta.css

Resolves #3645
Adds a hide/show label button to the New Validate Beta page.
Before
After

Adds hide/show label button to new Validate

---

public/javascripts/SVLabel/src/SVLabel/zoom/ZoomControl.js
public/javascripts/SVValidate/src/zoom/ZoomControl.js

Resolves #3646 
As suggested in the issue, I changed the zoomLevel variables in the zoomControl in validate to wrap them with Math.round() so that they were rounded to the appropriate decimal value. I also went into the zoomControl in explore and looked through the commit history to see why we were doing parseInt(zoomLevelIn), and I found that it's been like that since the very first commit where no reasoning was provided. So I went ahead and changed that to a Math.round as well. 
Before (couldn't zoom sometimes even if the button wasn't grayed out)
After (can always zoom until the button is grayed out)
I was able to reproduce this issue, albeit occasionally, whenever I went through validate and kept zooming in and zooming out. The exact way I tested this was by going through 4 different …

Fixed occasional zoom in/out in validate bug

---

app/views/explore.scala.html

I recently noticed that we are importing the onnxruntime lib that we used for LabelAId through a CDN no matter what. It's a pretty big lib and was taking like 100ms to load. No need to do this anywhere but the crowdstudy server right now. Should speed up page load slightly.

Now only importing onnxruntime on crowdstudy server

---

app/models/daos/slick/UserDAOSlick.scala
app/models/user/WebpageActivityTable.scala

Resolves #3664
Updated queries in admin view statistics (last login date in Users tab, logins per user in Analytics) to account for "SignInSuccessEmail=" which was introduced as new logging values. 
Before
After
1. Login to your account
2. Sign out of your account
3. Login to your account
4. Go to Admin view and check "last login" date of your alias in "Users" tab
5. Go to Admin view and check "logins per user" graph in "Analytics" tab

Updated Admin sign in statistics to account for new sign up/sign in logging values

---

public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js

Partially addresses #2478 
Ensures that the zoom level is always recorded as integer value, and the _correct_integer value on the Explore page. Zoom values like 1.999 and 0.999 were being used on the front end, then were being automatically truncated to values of 1 or 0 when being sent to the back end. We now make sure to round those values consistently!

Ensures that zoom is always set to an integer value on Explore page

---

public/javascripts/Gallery/src/cards/CardContainer.js

Resolves #3674
Fixed bug that caused the expanded view of a card to go out of view in Gallery view when the currently expanded card is clicked on again. 
You click once on the card you want the expanded view of to get the following display.
If you click on the same card again through the side bar in expanded view, the expanded view shifts up the page so it is out of view. The higher the index of the card on the current page, the more the expanded view shifts. Image 1 is card 2 on the page and image 2 is card 3 on the page.
You click once on the card you want the expanded view of to get the following display.
If you click on the currently expanded card again, the expanded view remains unaffected.
1. Start local instance
2. Click into Gallery view
3. Click on any card on the page to open …

Bug Fix for expanded view going out of view when current expanded card is clicked again

---

app/controllers/AdminController.scala
app/controllers/ApplicationController.scala
app/controllers/UserProfileController.scala
app/models/audit/AuditTaskTable.scala
app/models/label/LabelTable.scala
app/views/labelMap.scala.html
app/views/routeBuilder.scala.html
conf/messages.de
conf/messages.en
conf/messages.es
conf/messages.nl
conf/messages.zh-TW
conf/routes
public/javascripts/routeBuilder.js
public/stylesheets/routeBuilder.css

Resolves #3694
Adds a button after you finish creating a route in RouteBuilder to view the data for just that route in LabelMap. This is done via a URL parameter, so you view data for any route (or routes) at any time. The URL might look like `/labelMap?routes=12,8,44` or simply `/labelMap?routes=12`.
Before
After
And in LabelMap
And then in LabelMap if you selected multiple routes

Adds button to view data for a route in LabelMap

---

Gruntfile.js
app/controllers/AdminController.scala
app/models/street/StreetEdgeTable.scala
app/views/admin/index.scala.html
conf/routes
public/javascripts/Admin/src/Admin.js

Working towards #380 
I called that API route in Admin.js and loaded that data onto the Admin page after its initial load from the server. I also made it so that the spinner stops the loading animation only after that API call happens so we won't get any proxy errors, but everything will still be loaded once the spinner stops.
This reduces the initial load time of the page by ~10 seconds, but the total load time remains the same since that data is queried after the initial page load. I have the Seattle database, but this change should induce speedups in every city's Admin page.
1. Load the admin page and verify that everything looks good! Additionally, you can time the amount of time it takes

Reduce Admin Page Initial Load Time by ~10s (Seattle) by Moving Coverage Data to new API Route

---

public/javascripts/SVValidate/src/menu/RightMenu.js

Fixes #3691
When we encountered an "excluded" tag on the new Validate page, the page would break since it didn't have all the necessary data to render it. Since we are trying to hide those tags in the UI anyway, I just added a condition to skip trying to render tags if we don't have the appropriate metadata.
An excluded tag would be one where we collected data on it, but subsequently removed it from the UI while keeping the old data in the db. The most notable example comes from our rework of the Pedestrian Signal tags (PR #3501), where we switched from "button waist height" to "hard to reach button". We kept the old data, but aren't showing it in the UI.

New Validate no longer breaks when trying to show excluded tags

---

app/controllers/CredentialsAuthController.scala
app/controllers/SignUpController.scala
app/controllers/TaskController.scala
app/controllers/ValidationTaskController.scala
app/models/label/LabelTable.scala
app/models/label/LabelValidationTable.scala
app/models/street/StreetEdgePriorityTable.scala

Fixes #3728 
Fixes an issue where Exploring and Validating didn't work correctly if you were logged into a city that you had never logged into before. I added checks in a bunch of places to make sure that an entry exists for the current user in the `user_stat` table. We now do this check when signing in, when adding a label, when validating a label, etc.

Fixes unified login when logging into a new city

---

app/views/forgotPassword.scala.html
conf/messages.de
conf/messages.en
conf/messages.es
conf/messages.nl
conf/messages.zh-TW

Resolves #3717 
Removes some text on the forgot password page that is no longer relevant after implementing unified login.
Before
After

Removes text on forgot password page post unified login

---

conf/application.conf

Resolves #3714
This should give us _real_ unified login, where you login in one city, and it keeps you logged in as you switch between cities.
It's now working correctly on my local environment, but I need to test it out on the test servers to know for sure, especially when it comes to using http vs https!

Authentication cookie should now be shared across subdomains

---

app/models/label/LabelTable.scala

Fixes #3745
Fixed the divide by zero error in the /overallStats API when the city has no labels! We now deal with this case and output "N/A" for the `avg_timestamp_last_100_labels` attribute if there are no labels.
@jonfroehlich you may have to take this into account in your dashboard!
Here's a look at the output if there are no labels.

Fixes divide by zero error in overallStats API when there are no labels

---

app/controllers/ValidationController.scala
conf/routes

Working towards #3584 
Adds URL parameters matching those for /adminValidate, allowing admins to specify which label type, users, and neighborhoods for the labels they're validating. I'm adding these quickly so that our partners can make use of them over the next couple of weeks, so I didn't include anything in the UI to show that extra info like we're doing for /adminValidate. For reference, here's an example 
```
/newValidateBeta?labelType=CurbRamp&users=user1,user2&neighborhoods=3,Downtown,6
```

Adds admin params for /newValidateBeta

---

public/javascripts/SVValidate/src/modal/ModalMissionComplete.js

Resolves #3704
The keyboard was being incorrectly enabling during the screen right before the Validation missions and increasing the count even before the mission started. I commented out the extra keyboard enabling. 
1.

Code to ensure keyboard isn't incorrectly enabled during the Mission Start screen

---

public/stylesheets/choropleth.css

Resolves #3776 
Updated cx and cy presentation attributes to the circle as mentioned here. 
https://stackoverflow.com/questions/51551729/styling-of-svg-circle-doesn%C2%B4t-work-in-firefox-browser-removes-radius-property
1. Run locally on firefox and go to labelmap page. http://localhost:9000/labelMap
- [x ] I've written a descriptive PR title. 
- [ x] I've added/updated comments for large or confusing blocks of code.
- [ x] I've included before/after screenshots above.
- [ x] I've asked for and included translations for any user facing text that was added or modified.
- [ x] I've updated any logging. Clicks, keyboard presses, and other user interactions should be logged. If you're not sure how (or if you need to update the logging), ask Mikey. Then make sure the documentation on [this …

resolved issues with labelmap in firefox due to circle css

---

app/controllers/ValidationController.scala
app/controllers/ValidationTaskController.scala
app/controllers/helper/ValidateHelper.scala
conf/routes

Resolves #3784
Adds the ability to use the "neighborhoods" URL parameter on both Validate and Mobile Validate. Example uses:
```
/validate?neighborhoods=2
/validate?neighborhoods=North Oakland
/validate?neighborhoods=North Oakland,Central Business District
/mobile?neighborhoods=North Oakland
```

Adds neighborhoods URL param to Validate and Mobile Validate

---

app/views/main.scala.html
public/javascripts/Admin/src/Admin.Panorama.js
public/javascripts/Gallery/src/expandedview/GalleryPanorama.js
public/javascripts/SVLabel/src/SVLabel/navigation/MapService.js
public/javascripts/SVValidate/src/panorama/Panorama.js

Resolves #3620 
I am _hoping_ that this update will prepare us for the upcoming changes to the Google Maps controls. Unfortunately, I had to do a bit of guesswork because their documentation says to test on the beta channel, but there's a bug in the beta channel that prevents the zoom UI from ever closing. Once the new API update comes out, we'll just make a new ticket of UI elements appear that shouldn't be there.
I also updated from the "quarterly" release cycle to "weekly" from Google Maps. After reading through the documentation, it was clear that the weekly cycle is the one that we want to be on.

Switches google maps to weekly release, adds cameraControl opts

---

app/views/userProfile.scala.html
public/javascripts/Progress/src/Progress.js
public/locales/de/dashboard.json
public/locales/en/dashboard.json
public/locales/es/dashboard.json
public/locales/nl/dashboard.json
public/locales/zh-TW/dashboard.json

Resolves #3778
I added an unescape HTML method so that special characters like & can be displayed correctly in the teams list.
1.

3778 fixed user dashboard teams list not displaying special characters correctly for team name and description

---

app/views/missionStartTutorial.scala.html

Resolves #3743
Start mission button in validate page recognized by audio control by setting div attribute role="button", which allows the audio control to recognize it as a button rather than just a div text element.
1. If on mac, turn on voice control in accessability with overlay set to item numbers. 
2. See that a number pops up for the start mission button in validate page.

Start mission button in validate page recognized by audio control

---

public/javascripts/PSMap/AddNeighborhoodsToMap.js

Resolves #3777 
Configured tooltopTimout variable to handle flickering on toolbox when hovered by adding slight delay when removing tool tip which gives the user time to move their mouse onto the tooltip.
https://github.com/user-attachments/assets/4bb58cc7-68e9-4445-97af-ea614b63a8fa
https://github.com/user-attachments/assets/9bdae156-b64e-4f8d-bf05-353244bf01c4
1. Open up firefox and hover over label map and check whether there is flickering.

Neighborhood hover not working on our maps in Firefox #3777

---

public/javascripts/SVValidate/src/Main.js

Resolves #3746
The problem was that when the validate page is reloaded and there are no missions to start with, the screen is blank. To fix this, I added ternary operation to ensure that if the initial length of missions is 0, it will display the no new mission modal.
Before:
Web Browser-
Mobile-
After:
Web Browser-
Mobile-
1. Force else case in getDataForValidationPages() in ValidationController.scala by replacing labelTypeId.isDefined && missionSetProgress.missionType == "validation" with false.
2. Navigate to validation page and reload the screen.

Fixed blank screen issue when there are no missions to validate initially

---

app/controllers/AttributeController.scala
app/models/attribute/GlobalAttributeTable.scala
app/models/attribute/GlobalAttributeUserAttributeTable.scala
app/models/attribute/UserAttributeLabelTable.scala
app/models/attribute/UserAttributeTable.scala

Resolves #2499 
Replaced individual row inserts with a single bulk insert call that returns all newly inserted IDs, vastly reducing the number of queries and ~doubling the speed of nightly clustering.  
TODO: Implement bulk region clustering.
1. Run nightly clustering, and check time compared to original code

2499 - Speeding up nightly label clustering with bulk processing

---

public/javascripts/SVValidate/src/menu/RightMenu.js

Resolves #3801
- Small typo in fetching unsureOption
https://github.com/user-attachments/assets/38b7027f-60b8-423d-a4eb-53014a349ab9
https://github.com/user-attachments/assets/cc0e7dcb-3d41-4a02-8499-91bc1913571d
1. Go on newValidateBeta and go to unsure tab and choose an option and click submit
2. Go back and check there is the previous chosen option.

Unsure reason selection isn't being kept when undoing a validation

---

app/models/daos/slick/UserDAOSlick.scala

Resolves #3726 
I believe that I've found the problematic query that's been slowing down the Users tab on the Admin page. I combined it with another query in order to filter it down, since it was grabbing a row for every user account, instead of just those that we want to show. Took the query time locally from 25 seconds to 5 seconds.

Improves query performance for Admin page Users tab

---

app/models/daos/slick/UserDAOSlick.scala

Resolves #3802
Users tab on admin page having issues since merging authentication info into a centralized schema. Quick fix was commenting out code that showed anonymous users, only displaying validated ones.
1. Sign in as admin
2. Profile -> Admin -> Users
3. See if only verified users are being displayed.

Showing only validated users on admin page #3802

---

public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/keyboard/Keyboard.js
public/javascripts/SVValidate/src/menu/RightMenu.js
public/javascripts/SVValidate/src/util/ConstantsValidate.js

Resolves #3639 
- Added additional cases to handle (1,2,3) option choices for agree, disagree, unsure options under documentKeyDown function. if there are only 2 options, 3 will go to the comment box.
- c,4 key deselects the other options and go to the input box.
- Implemented keydownListener handlers for the escape key as it was not being recognized within input element.
- Added numbers to corresponding tooltips to help guide users to shortcuts.
- Added attributes to unsure disagree options button to keep track they have the defaultOption.
https://github.com/user-attachments/assets/e1db2099-2609-49ec-b706-5d62482fc5d0
https://github.com/user-attachments/assets/4e9c0dc8-17f6-46d7-b631-f42cedbc8124
1. Go to /newValidateBeta page with admin account
2. Go to /validate to make sure it did not …

Keyboard shortcuts for new validate page

---

public/javascripts/Gallery/src/expandedview/ExpandedView.js
public/javascripts/Gallery/src/keyboard/Keyboard.js

Resolves #3798 
- Implemented zoomIn zoomOut functions.
- If the view is in expanded view, fetches current zoom and increment/decrement. 
- Min/Max functions so level stays between 1 and 3. 
1. Go to Gallery page and select one of the items.
2. Press Z and shiftZ to see if zoom works in the panorama. Also check it caps out at 3x zoom and does not go less than 1x.

Add zoom keyboard shortcuts to Gallery

---

app/models/daos/slick/DBTableDefinitions.scala

Resolves #3715 
The `auth_tokens` table was centralized along with the rest of authentication in PR #3712, but it wasn't actually useful for this specific table. This PR just reverts that change. Once I verify that password resets are still working as expected on test/prod, I'll delete the `auth_tokens` table that's part of the centralized `sidewalk_login` schema.

Reverts using centralized auth_token tables, now separate by city again

---

public/locales/de/audit.json
public/locales/en/audit.json
public/locales/es/audit.json
public/locales/nl/audit.json
public/locales/zh-TW/audit.json

Resolves #3811 
Changed text in /en/audit.json, along with corresponding translations in de, es, nl, zh-TW 
Before:
After (Signed in, although it doesn't matter):
After (Anon user): 
1. Open localhost:9000
2. Navigate to 'explore' -> Start mission
3. Click 'OK' on the popup
4. Pan around in main street view window to get mini map text to appear
5. Observe mini map text correctly shows new text
- [NA] I've added/updated comments for large or confusing blocks of code.
- [NA] I've updated any logging. Clicks, keyboard presses, and other user interactions should be logged. If you're not sure how (or if you need to update the logging), ask Mikey. Then make sure the documentation on [this wiki page](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Descriptions-of-Logged-Events) is up to …

Change minimap fog of war text, along with respective translations

---

public/javascripts/SVLabel/src/SVLabel/Main.js
public/javascripts/SVValidate/src/Main.js
public/javascripts/common/SpeedLimit.js

Resolves #3670 
Problem: The speed limit display in the validation view is irrelevant for some labels. We want to make it only display for certain labels (as of now, only `NoCurbRamp`).
Fix: Pass in label type to `SpeedLimit.js`, which now has a list of speed limit-relevant labels. It will hide the speed limit for all labels not included in this list. 
For the 'label' view, since we always want to display the speed limit, I have added the tag `AlwaysDisplay` as a label type, and the SVLabel/main will just pass in `AlwaysDisplay` as its label type. 
Question: Is there a more elegant way to do this? Instead of `AlwaysDisplay`, should it just be `null`?
Note - Since this is an edit to the "Validation" page, normally it would also apply to mobile. However, speed limit is, by default, hidden …

Add speed limit relevant check for validation

---

app/formats/json/APIFormats.scala

Resolves #3756 
Added quotation marks around name field in the rawData to CSV API call.
Before (The neighborhood is called School , 5):
After:
1. Check the Label Map to find the coordinates of an area populated with labels. Choose a min/max lat and min/max long.
2. Use this URL to fetch the csv file from the API:
localhost:9000/v2/rawLabels?lat1=<x1>&lng1=<y1>&lat2=<x2>&lng2=<y2>&filetype=csv
3. check that the CSV file matches with correct formatting for any row with neighborhood name that contains ,

Add quotation marks around commas in API CSV calls.

---

app/models/user/TeamTable.scala
app/views/userProfile.scala.html

Resolves #3693 
Used the scala sortBy method to sort the names of the teams listed in the user dashboard.
Before (added a couple random team names)
After:
1.  Go to http://localhost:9000/dashboard
2.  Make sure that the team names under the dropdown are alphabetical and all teams are listed as expected.

Sort list of teams by name in dashboard

---

public/javascripts/SVLabel/src/SVLabel/navigation/Compass.js

Resolves #3773
To fix the compass message inconsistency, I normalized the targetAngle and removed any overlap with the angle for "slightly left" and "left"
Before:
After:
1. Revert all changes in this PR to original state except changes in _angleToDirection function (remove my edits)
2. Add console.log for heading angle and target angle in the function _getCompassAngle after the respective variables are declared
3. Some streets where you can see this error: http://localhost:9000/explore/street/44336 , http://localhost:9000/explore/street/62878 , http://localhost:9000/explore/street/62877
5. Look to the left relative to the direction you are trying to go (left of the red line)
6. Compass message should be "Go Straight"
7. Add my changes and messages should say Turn Right or Turn Slightly …

removed angle overlap in angleToDirection and normalized targetAngle

---

public/javascripts/PSMap/AddNeighborhoodsToMap.js

Resolves #3755 
Simply increased tooltip timeout for users to have enough time to hover over the tooltip before it timesout for small cities when zoomed out.
After screenshot:
https://github.com/user-attachments/assets/220d9422-0fc6-4a25-885d-dadb357b5300
1. Go to black hawk hills to hover over a small city while being fully zoomed out.

Increased tooltip timeout for small neighborhoods

---

app/controllers/ExploreController.scala
public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js

Fixes #3937
Fixes the issue where the Neighborhood Complete screen would show up after every street that you audit, forcing a page refresh each time.
It seems that I updated the /tasks endpoint to produce correctly formatted GeoJSON at some point, but didn't catch the place we use it on the Explore page that assumes that it's in the wrong format :upside_down_face: Fixed this to assume the correct format (and then updated the /routeTasks endpoint to return correctly formatted GeoJSON as well).

Fixes neighborhood complete message after every street

---

app/controllers/AdminController.scala
app/controllers/UserController.scala
app/models/user/LoginInfoTable.scala
app/models/user/SidewalkUserTable.scala
app/models/user/UserRoleTable.scala
app/models/user/UserStatTable.scala
app/service/AuthenticationService.scala

Resolves #3939 
Fixes two main issues with account creation.
The first is that we were creating duplicate entries in the `user_login_info` and `user_stat` tables. This is due to the way that we "create" accounts for users when they register. What we actually do is to transfer the anonymous user account that we automatically created for them over to their new login credentials that they provided. This way we can keep the contributions that they made anonymously in that session associated with the new account that they created.
I've fixed this by creating separate flows when creating new accounts vs transferring accounts. New accounts get db inserts, transferred accounts get db updates.
The second problem was, although entries to the `user_role` table were being inserted and then updated …

Fixes various issues with account creation

---

app/controllers/AdminController.scala
app/controllers/ApiDocsController.scala
app/controllers/ApplicationController.scala
app/controllers/ClusterController.scala
app/controllers/ExploreController.scala
app/controllers/GalleryController.scala
app/controllers/GeminiController.scala
app/controllers/UserController.scala
app/controllers/UserProfileController.scala
app/controllers/ValidateController.scala
app/controllers/api/AccessScoreApiController.scala
app/controllers/api/CitiesApiController.scala
app/controllers/api/LabelApiController.scala
app/controllers/api/LabelClustersApiController.scala
app/controllers/api/RegionApiController.scala
app/controllers/api/StatsApiController.scala
app/controllers/api/StreetsApiController.scala
app/controllers/api/ValidationApiController.scala
app/controllers/base/CustomBaseController.scala
app/service/LoggingService.scala
conf/evolutions/default/278.sql

Resolves #465
Instead of logging the full IP address list that includes proxies, we're now just logging the first IP address in the list (which should be the correct one). I also added a database evolution that fixes this for all past entries in every table that stores IP addresses.
To enable these changes, I added a new method to the `RequestHeader` object called `ipAddress`, which does all of this cleaning automatically. So wherever we used to use `request.remoteAddress`, we should just use `request.ipAddress` instead! I've changed this everywhere in the code, and I'm hoping that it's pretty easy to remember going forward.

Fixes list of IP addresses being logged

---

app/controllers/ValidateController.scala
app/controllers/helper/ValidateHelper.scala
app/formats/json/ValidateFormats.scala
app/models/label/LabelTable.scala
app/service/LabelService.scala
app/views/apps/expertValidate.scala.html
app/views/apps/mobileValidate.scala.html
app/views/apps/validate.scala.html
conf/routes
public/javascripts/SVValidate/src/Main.js
public/javascripts/SVValidate/src/data/Form.js
public/javascripts/SVValidate/src/panorama/PanoramaContainer.js

Resolves #3774 
Adds a new URL parameter to all Validate pages, `unvalidatedOnly`. You can set it to `unvalidatedOnly=true` to only see labels that have no validations, or an even number of agree and disagree validations. This works on Validate, Admin Validate, and Expert Validate! An example URL:
https://sidewalk-chicago.cs.washington.edu/adminValidate?labelType=Obstacle&unvalidatedOnly=true
Note that the `labelType` and `users` parameters are admin-only, while the `unvalidatedOnly` and `neighborhoods` parameters can be used by anyone. Not committed to that setup, but that's what we have at the moment!

Adds Validate URL param: unvalidatedOnly

---

app/controllers/api/LabelApiController.scala
app/controllers/api/StatsApiController.scala
app/models/api/LabelApiModels.scala
app/models/label/LabelTable.scala
app/models/user/UserStatTable.scala
app/service/ApiService.scala
app/views/apiDocs/labelClusters.scala.html
app/views/apiDocs/rawLabels.scala.html
conf/routes

Resolves #2967 
This PR consists of three small changes:
1. Adds a new `highQualityUserOnly` param to the `/v3/api/rawLabels` API. If set to `true`, it excludes labels from any user marked as low quality.
2. Fixes the behavior of the `highQualityOnly` param in the `/v3/api/userStats` API. The parameter name and documentation implied that it would exclude low quality users if set to `true`, and include all users otherwise. Setting it to `false` was actually filtering out high quality users. I've fixed the way it works to match the parameter name, documentation, and the way that the new `highQualityUserOnly` parameter works in the rawLabels API.
3. Adds a Data Cleaning section to the labelClusters API docs page, which outlines all the filtering that we do before clustering in detail. I also …

Adds highQualityUserOnly param to rawLabels API

---

public/javascripts/SVLabel/src/SVLabel/canvas/Canvas.js
public/javascripts/SVLabel/src/SVLabel/canvas/ContextMenu.js
public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js
public/javascripts/SVLabel/src/SVLabel/label/Label.js
public/javascripts/SVLabel/src/SVLabel/onboarding/Onboarding.js
public/javascripts/SVLabel/src/SVLabel/onboarding/OnboardingStates.js

Fixes #4021
Here are a few of the bugs that were fixed
* Rating severity wasn't disabled during that tagging step, allowing you to complete steps out of order (this was introduced in PR #3845)
* You could edit labels from earlier in the tutorial when you were supposed to edit the current one (because "enabling tagging" wasn't tied to a specific label). This also meant that editing the severity for a prior label could progress the tutorial as if you had rated the current one correctly
I made a few other improvements to keyboard shortcuts while I was looking at the relevant code:
* The `enter` and `esc` keys now close the context menu even if you're focused on the description text box
* 1/2/3 on the number pad will now add severity ratings as it does for the typical 1/2/3 keys
* zooming …

Fixes various bugs in the Explore tutorial
